### ISSUE TITLE
Normative language in Security Considerations

### ISSUE THREAD

**Issue by rhiaro** [w3c/did-core#107]
There's a bunch of normative language about the security considerations of DID methods, in the Security Considerations section (which is traditionally, and labelled as, a non-normative section). Should this be moved to the DID Methods section?

**Comment by rhiaro** [comment]
Ditto Privacy Considerations

**Comment by msporny** [comment]
> Should this be moved to the DID Methods section?

Yes, we should avoid normative language in the security considerations and privacy considerations sections. I don't think implementers scan those sections for normative statements.

**Comment by rhiaro** [comment]
Fixed by #130
