### ISSUE TITLE
Specification needs to be compliant with WCAG 2.0

### ISSUE THREAD

**Issue by burnburn** [w3c/did-core#118]
We are required to ensure that the document, when published, satisfies the WCAG 2.0 requirements.  See https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0

At a minimum this must be done before CR publication.  If done earlier, it needs to be kept up to date.  While technically editorial, this is a non-trivial piece of work, especially as we add diagrams, so additional volunteers are encouraged.

**Comment by rhiaro** [comment]
I will do a first pass through applying these guidelines this week and make a PR. We can leave this issue open to audit again before CR.

**Comment by rhiaro** [comment]
(WIP)

* [x] 1.1 Non-text content alternatives: n/a
* [x] 1.2 Time-based media: n/a
* [ ] 1.3 Adaptable
  * [ ] structure conveyed by presentation available programmatically
  * [ ] reading sequence available programmatically
  * [x] content not depends on sensory characteristics: n/a
* [x] 1.4 Distinguishable
  * [x] meaningful color: n/a
  * [x] resizeable text
  * [x] contrast of images: n/a
  * [x] images of text: n/a
  * [x] audio: n/a
* [ ] 2.1 Keyboard accessible
* [x] 2.2 Timing: n/a
* [x] 2.3 Physical reactions: n/a
* [ ] 2.4 Navigable
  * [ ] bypass repeat blocks
  * [x] titles
  * [ ] focus order
  * [ ] link purpose
  * [x] multiple ways to locate page: n/a
  * [ ] headings and labels
  * [ ] focus visible
  * [x] user location within set of pages: n/a
  * [x] section headings
* [ ] 2.5 Input modalities
* [ ] 3.1 Readable
  * [ ] programmatic language determination
  * [ ] identifying unusual phrases
  * [ ] expanding abbreviations
  * [ ] reading level lower than secondary education
  * [ ] pronunciation identified where necessary for meaning
* [ ] 3.2 Predictable
  * [ ] on focus doesn't change context
  * [x] on input doesn't change context: n/a
  * [x] consistent nav: n/a
  * [x] consistent identification of components with same func.
  * [ ] change of context on request only
* [x] 3.3 Input assistance: n/a
* [x] 4.1 Compatible
  * [x] valid markup
  * [x] `name` and `role` of elements

**Comment by rhiaro** [comment]
(Will complete this audit closer to CR, but if anyone knows which of the markup/structure related things respec covers automatically please say so)

**Comment by msporny** [comment]
> if anyone knows which of the markup/structure related things respec covers automatically please say so

Unfortunately, I don't know... looking now in ReSpec's documentation...

**Comment by msporny** [comment]
Still waiting on CR...

**Comment by msporny** [comment]
I have done an WCAG2 analysis on the document. The readability scores are borderline... requiring ~11 years of education (or 7th grade US level) to understand.

That said, we pass all checks. Closing.
