### ISSUE TITLE
DID Method discovery mechanism requirement

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#12]
@gklyne moved from CCG (https://github.com/w3c-ccg/did-spec/issues/83)

**Comment by msporny** [comment]
This issue has been floating out there for a year with an intent to close. The initial issue submitter was happy with the response in w3c-ccg/did-spec#83, no one objected. The DID WG should close this issue.

**Comment by jandrieu** [comment]
Agreed. This is best suited for discussion in the DID Resolution spec and it looks like it has already been picked up for discussion in https://github.com/w3c-ccg/did-resolution/issues/26 and ttps://github.com/w3c-ccg/did-resolution/issues/198.

+1 for closing

**Comment by msporny** [comment]
Closing in 14 days (due to WG work start delay, would normally be 2 days) unless there are objections.
