### ISSUE TITLE
Regarding PII Embedded in Key Formats

### ISSUE THREAD

**Issue by OR13** [w3c/did-core#124]
https://www.w3.org/TR/did-core/#keep-personally-identifiable-information-pii-private

Recently the risk of PII that is embedded in keys was discussed, both JWK and GPG keys support this possibility.

https://tools.ietf.org/html/rfc7517#section-4

https://tools.ietf.org/html/rfc4880#section-5.11

Its also possible that services could be abused to include either base64url or non encoded PII, such as query strings params, etc...

And of course, I can always embed anything I want in hex/multibase data if there is no validation... and even then, I can use encryption, and pay to anchor PII to a ledger or DID Method.

Consider the attack where a user encodes emails collected from a breach in RSA 4096 keys... indeed it is possible to construct a stenographic covert communication channel inside any data that appears random using encryption...

Since the DID Core spec is about a data model and syntax, I believe forensic analysis of user supplied input / data validation is outside of the scope of the spec, but DID Method implementers may find it desirable to consider such attacks or otherwise protect against covert channels... (good luck?).

It may be in scope to advise method implementers that rely on JWK / GPG key formats to NOT use features of these formats that allow for PII / correlation...

_I'm not sure how that could be enforced given that validation is neither a syntax nor a data model issue._

I will concede that copying a GPG key or a JWK without reviewing auditing/minimizing its information into a DID Document, is much like sharing a Word Document or Image with EXIF GPS coordinates or other meta data in it, and supporting any format which may contain sensitive metadata creates the inevitability that someone will unknowingly disclose it... as many journalists have already done.

@dlongley @msporny @selfissued Per our conversation regarding key formats, I'd prefer we tackle the GDPR/PII issues with DID Documents in a more general context (separate from the supported key format discuss), since there are clearly many ways a DID Method implementer could make mistakes, and in fact they may have no control over what information a controller/subject chooses to disclose.

**Comment by awoie** [comment]
IMO, the bigger risk is that PII can be included anywhere in the DID
Document itself. Nobody can prevent anyone from defining a DID method that
can include PII. Remember, we are talking about the representation of the
public key in the DID Document and NOT of the representation of the key in
the ledger. So, even if PII was included in the DID Document this does not
mean it has to be recorded on the ledger itself. Some DID methods don't
even use ledgers or follow a hybrid approach. Furthermore, JOSE defines how
certain key types are encoded as JWK and they don't contain any PII, see
https://tools.ietf.org/html/rfc7518, https://tools.ietf.org/html/rfc7517
 etc.

I agree with Orie to tackle the PII discussion in much broader context.

Oliver

**Comment by awoie** [comment]
Whether public keys are considered to be PII depends certainly on the
linkage risk, i.e., are you able to correlate the public key with some PII
reference data that identifies an individual, but this is out of scope of
this spec.

Oliver

**Comment by OR13** [comment]
I think the path to resolution for this issue is to add a section to security considerations advising DID Method implementers and library developers to take the following BCPs.

1. When receiving user supplied input that may contain PII / correlation parameters, software SHOULD reject any version of structured data that leverages optional fields.

2. DID Methods should always reject DID Documents that contains properties that are not defined in the DID Core spec or the DID Method spec (JSON-Schema additionalProperties: false).

**Comment by OR13** [comment]
Worth noting that sidetree attempt to solve this by being very strict about what can be added to a did document, IMO, its not really the right approach. If a user wants to put some PII in a did document, thats their right, just like if the want to add PII to a TXT record on a domain they own. I'd be comfortable closing this with no changes to the spec.

**Comment by msporny** [comment]
> If a user wants to put some PII in a did document, thats their right, just like if they want to add PII to a TXT record on a domain they own. 

Well, ledgers are different in that there could be GDPR implications for doing that to the organizations that operate the ledger. For example, Veres One is going to be very strict about what you can put in a DID Document and we should probably document the reasoning behind that decision. The same might not apply for DID Documents that exist on other systems under the control of the DID controller.

> I'd be comfortable closing this with no changes to the spec.

We need to say something about this in the spec.

**Comment by OR13** [comment]
Why do we need more than what we have for: 
- https://www.w3.org/TR/did-core/#keep-personally-identifiable-information-pii-private

Any method that lets user define arbitrary strings will support PII injection, how do we know that 555555555 is a social security number and not a public key identifier?

A data model that supports arbitrary strings, supports PII injection.

Public ledgers are censorship resistant, the ability to write what you want is a feature not a defect. With great power comes great responsibility.

Private ledgers or DID Methods might choose to be more strict, but strategies around implementation are out of scope for the core spec imo.

**Comment by msporny** [comment]
> Why do we need more than what we have for

So, I just scrolled up to see who opened this issue, and it was you. :)

If you're happy to close the issue because you're happy with what's in the spec, then let's close it.
