### ISSUE TITLE
Allow DID documents to be retrieved using any URI scheme

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#13]
@gklyne moved from CCG (https://github.com/w3c-ccg/did-spec/issues/84)

**Comment by msporny** [comment]
This issue is resolved via this other issue:

https://github.com/w3c/did-core/issues/1#issuecomment-583645102

I think we have clarity, closing this issue and the MIME Type issue above will resolve this one and @gklyne's original question.

**Comment by msporny** [comment]
The MIME Type section of the spec #196 has been merged, which addresses this issue. Closing.
