### ISSUE TITLE
Inconsistent normative language around `id` on public keys

### ISSUE THREAD

**Issue by rhiaro** [w3c/did-core#134]
`id` on public keys is optional (SHOULD): https://github.com/w3c/did-core/issues/47

but the algorithm for processing [public keys](https://w3c.github.io/did-core/#public-keys) says:

> If result does not contain at least the id, type, and controller properties as well as any mandatory
> public cryptographic material, as determined by the result's type property, throw an error. 

which reads to me like `id` is mandatory.

I think this is an oversight (and therefore editorial), but would like confirmation please (@peacekeeper?).

**Comment by peacekeeper** [comment]
@rhiaro

I think maybe we want to rewrite this paragraph later or move it elsewhere, since it may better fit in with DID Resolution than the core spec.

But for now, I agree with you this looks like an oversight and should be changed.

**Comment by OR13** [comment]
I think the spec should clearly state that `id` is mandatory, and should also address the conventional use of qualified and non qualified `id` values... 

For example, some may wish to rotate a `primary key`, and may only use `#primary` for the `id` value... others, especially those wishing to maintain linked data conformance, will require the `id` always be a uri, and that all `id` values be "fully qualified"... like so:

`did:example:123#primary`

... this allows for a single id to be reused for rotated keys, whereas:

`did:example:123#<publicKeyThumbprint>` provides a compound identifier that might be more useful for keystore systems which are not away of DIDs.

I would love to see more guidance on this in the spec.

**Comment by OR13** [comment]
The spec should say that `id` is mandatory.

**Comment by msporny** [comment]
`id` should be mandatory for verification methods. We need a PR that does that.

**Comment by peacekeeper** [comment]
After some discussion and support in https://github.com/w3c/did-core/issues/47, a PR https://github.com/w3c/did-core/pull/66 created by me was merged by @msporny that made `id` optional for service and public keys / verification methods.

See e.g. https://github.com/w3c/did-core/issues/47#issuecomment-539574396 and https://github.com/w3c/did-core/issues/47#issuecomment-539610575 for explanations.

I agree there are many good reasons for having `id`s, but can you explain why they need to be mandatory?

**Comment by OR13** [comment]
`id` should be mandatory, because allowing it to be optional will cause implementers to rely on them less, and encourage external software systems to come up with their own ways of identifying keys.... which might cause conflicts, such as the issue with `kid`, `fingerprint`, and `publicKey.id`...

**Comment by peacekeeper** [comment]
I wrote the original PR last year that changed MUST to SHOULD for `id`s of public keys and service endpoints, but I also find the arguments in this thread convincing.. So no opposition from my side; if there is consensus, who wants to write a new PR to make them mandatory again?

**Comment by rhiaro** [comment]
I will write the PR this week

**Comment by rhiaro** [comment]
PR #225 merged, closing
