### ISSUE TITLE
What are the differences between Verifiable Credentials and DID document? 

### ISSUE THREAD

**Issue by YueJing95** [w3c/did-core#147]
The VC is made of multiple claims. should we call DID, Publickey, service endpoint in the DID document also claims?

**Comment by pensivej** [comment]
Short answer would be 'No'.

VC and DID Document are different because authentication of DID and verification of VC is not the same.
Also, VC is not written on any blockchain or DLT while DID Document is.
They might contain similar form of data, but their usage/purpose is totally different.

**Comment by haidedang** [comment]
Is it allowed to add attributes and claims to the DID Document though other then the listed core properties of a DID Document?

**Comment by YueJing95** [comment]
@haidedang  It depends on how you define the term **"attribute"** and **"claim"**, if it refers to **service endpoints**, it should be there. 
Personally, I assume the DID document as a tool, while the VC as an application of this tool

**Comment by agropper** [comment]
I tend to think of the DID Document being public and the VCs less than public. It parallels the difference between public blockchains and a private ones.

**Comment by peacekeeper** [comment]
> Is it allowed to add attributes and claims to the DID Document though other then the listed core properties of a DID Document?

@haidedang yes that is possible, see section "Extensibility" in the DID Core spec: https://w3c.github.io/did-core/#extensibility
