### ISSUE TITLE
Does a did method have to implement all CRUD operations?

### ISSUE THREAD

**Issue by gjgd** [w3c/did-core#149]
It seems to me that there is some inconsistent language in the [did core spec](https://www.w3.org/TR/did-core/) about the need for a did method to support all CRUD operations.

On the one hand, the spec says:
-  `The DID method specification MUST specify how a client creates a DID (...)` -> ([link](https://www.w3.org/TR/did-core/#create))
-  `The DID method specification MUST specify how a client uses a DID to request a DID document (...)` -> ([link](https://www.w3.org/TR/did-core/#read-verify))
- `The DID method specification MUST specify how a client can update a DID document (...)` -> ([link](https://www.w3.org/TR/did-core/#update))
- `The DID method specification MUST specify how a client can deactivate a DID on the DID registry (...)` -> ([link]( https://www.w3.org/TR/did-core/#deactivate))

On the other hand, the spec also says:`Any DID method specification that does not support a specific operation, such as update or deactivate, MUST clearly state these limitations.` which suggests that it is ok not to support update or deactivate.

We should either change the MUST language to a SHOULD language for update and deactivate, or remove the latter sentence

**Comment by gjgd** [comment]
It looks like the SHOULD language was chosen at some point: https://github.com/w3c-ccg/did-spec/pull/55

**Comment by iherman** [comment]
The way I read this is that the method specification MUST specify how a certain action is done and that covers the case when that action is not available. Ie, it MUST inform the clients when, say, deactivation is not available. I do not see a real contradiction.

If SHOULD was used, it would allow a client to be simply silent on what it does on deactivation. I guess this is what we would prefer to avoid...

**Comment by iherman** [comment]
I would agree, however, that this fine point must be made clearer in the spec.

**Comment by kdenhartog** [comment]
Here's an example of how `did:key` [handles this](https://digitalbazaar.github.io/did-method-key/#update). Of note, it cannot support did document update or deactivation events. With that said, I think the language could be further improved. I've submitted an initial draft text to improve this wording.

**Comment by rhiaro** [comment]
The wording in the spec currently is:

> The DID method specification MUST specify how a client can update a DID document on the DID registry, including all cryptographic operations necessary to establish proof of control, *or* state that updates are not possible. 

ie. it MUST (a) OR (b). I think the language is unambigious, SHOULD was deliberately not used. Can we close this issue?

**Comment by gjgd** [comment]
Agreed, we can close this. Someone who disagrees can feel free to reopen
