### ISSUE TITLE
Allowing embedded custom contexts

### ISSUE THREAD

**Issue by gjgd** [w3c/did-core#153]
Currently [the spec](https://w3c.github.io/did-core/#contexts) says
`
The value of the @context property MUST be one or more URIs, where the value of the first URI is https://www.w3.org/ns/did/v1. If more than one URI is provided, the URIs MUST be interpreted as an ordered set. It is RECOMMENDED that dereferencing each URI results in a document containing machine-readable information about the context. 
`

which means, in order to extend the did core context, a did method's did document must do so by referencing a custom context, like this
```json
{
  "@context": [
    "https://www.w3.org/ns/did/v1",
    "https://example.com/custom-context.jsonld"
  ],
  "id": "did:elem:EiC_H1NwXPlS5C-JSPJJtdZpHUzbIcOW_w0dUc5jv5ZO7Q",
  ...
}
```

I suggest that the spec also allows embedded custom contexts, such as:
```json
{
  "@context": [
    "https://www.w3.org/ns/did/v1",
    {
      "foo": "https://example.com/foo#",
      "bar": "foo:bar",
    }
  ],
  "id": "did:elem:EiC_H1NwXPlS5C-JSPJJtdZpHUzbIcOW_w0dUc5jv5ZO7Q",
  ...
}
```

Context embedding is a useful JSON-LD feature that we should be leveraging.

I don't see any immediate downsides, but open to have my mind changed.

**Comment by OR13** [comment]
IMO, this is blocked by the did core registry... we should define the type of `@context` there.

**Comment by OR13** [comment]
Partially addressed here: https://github.com/w3c/did-core-registry/pull/4

**Comment by OR13** [comment]
Blocked by DID Core registies: https://github.com/w3c/did-core-registries

**Comment by OR13** [comment]
Recommend not embedding context like this. I suggest we close this.
