### ISSUE TITLE
Use of undefined terms "graph-based" and "tree-based"

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#161]
The specification has numerous uses of the undefined terms "graph-based" and "tree-based".  They are apparently used to attempt to define semantic properties of DIDs, but that goal isn't accomplished by using terms that are not commonly understood.

Example uses of these terms include:

- "These documents are graph-based data structures that are typically expressed using [JSON-LD], but can be expressed using other compatible graph-based data formats."

- "Implementations need not rely on graph-based processing of DID documents to locate metadata contained in the DID document when the DID includes a DID fragment. Tree-based processing can be used instead."

- "Modelling of complex multi-entity relationships is provided through the use of a graph-based data model."

Please either define these terms and say why they are relevant to DIDs and their semantics or remove their uses from the specification.

**Comment by selfissued** [comment]
I will write a PR removing the use of these undefined terms.

**Comment by selfissued** [comment]
These terms do not provide actionable information.  They are more philosophy than normative statements.  Therefore, their usage should be removed.

**Comment by kdenhartog** [comment]
Given our current approach of supporting lossless conversion, I think it's acceptable to move away from these descriptions as well. The underlying data model shouldn't play as large of a role anymore if we get lossless conversion correct.
