### ISSUE TITLE
We should find a better term than "DID Registry" and better define what it refers to

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#162]
The Terminology section includes the term "DID Registry", although what it refers to is not actually a registry in the normal standards use of the term.  We should find a different term that doesn't cause this semantic confusion.

Furthermore, as described at https://github.com/w3c/did-use-cases/issues/14, there isn't a clear explanation of what it means for the DID to be recorded, or what properties a registry has.  For instance, using database terminology, if the registry is a database, what consistency and/or atomicity and durability properties of the database entries are assumed and are necessary?  I suspect there's a lot here that bears fleshing out.

**Comment by rhiaro** [comment]
The DID Registry has at times been known as the "target system" and before that just "the ledger" (I think, before we nailed down that DIDs don't require DLT). See https://github.com/w3c-ccg/did-spec/pull/184 for the history and some links to related issues. It's pretty clear still not everybody is happy with the term, so proposals for something better would be welcome.

**Comment by peacekeeper** [comment]
I agree we should try to replace the term, especially considering that at last week's [DID WG F2F meeting](https://www.w3.org/2019/did-wg/Meetings/F2F/2020.01.Amsterdam) we agreed that we would introduce registries for interoperability of extensions.

When we introduced the term ["DID registry"](https://w3c.github.io/did-core/#dfn-decentralized-identifier-registry) to the spec, the first goal was to simply have a single term for this across the entire spec, but I think many of us were never completely happy with it.

Here are some ideas:

- DID network
- DID (data) source
- DID origin
- DID storage/store

Others?

**Comment by selfissued** [comment]
Others:

- DID Authority
- DID Repository
- DID Backing Store
- DID Storage Agent

**Comment by talltree** [comment]
I propose we use the same term as the Verifiable Credentials spec:

- Verifiable data registry

Reasons:

- It is general enough to cover all the potential back-end systems or networks that could be used for DIDs.
- It doesn't suggest that the system needs to be a blockchain, DLT, distributed file system, or any other specific type of back-end.
- It reuses a term already defined in the VC spec and underscores the synergy with VCs.
- It suggests that DIDs can be used with all kinds of verifiable data, not just VCs, which is true.
- No one is going to confuse a verifiable data registry with the W3C DID Extension Registry.

**Comment by talltree** [comment]
A note that I had this terminology discussion at last week's Hyperledger Global Forum in Phoenix and found strong support for the term **verifiable data registry** because it aligns with the same term used by the Verifiable Credentials spec.

**Comment by peacekeeper** [comment]
I think **verifiable data registry** makes sense, +1

**Comment by rhiaro** [comment]
My understanding was that we picked DID Registry as a more specific _type of_ verifiable data registry (and it's [defined as so](https://w3c.github.io/did-core/#dfn-decentralized-identifier-registry)). I also thought it is primarily the word 'registry' that is contentious.

(Not an objection, just a point of interest.)

**Comment by talltree** [comment]
@rhiaro It is true that "DID Registry" was defined as being a more specific type of verifiable data registry. But IMHO therein actually lies the problem. The term "DID Registry" makes it sound like: a) the only type of data supported by such an animal is DIDs and DID documents, and b) that a DID Registry operates like a conventional registry for other types of identifiers, e.g., domain names. 

In practice, neither of those is true. Almost every system for which a DID method has been written deals with more than just DIDs/DID documents, and none of them operate like conventional centralized identifier registries.

Both of those problems are ameliorated by using the term **Verifiable Data Registry**. The "Verifiable Data" part generalizes the type of data that might be stored/managed. It also suggests (at least to me) a broader definition of how a system might function as a registry.

Finally, I believe there is significant benefit of having alignment with the same term being used by the Verifiable Credentials Data Model 1.0 specification.

If there are no objections, I propose to submit a PR to add this term to the Terminology section and update the term throughout the spec.

**Comment by kdenhartog** [comment]
I'm sure this isn't a novel idea, so I'm curious why we opted away from the term DID Directory or Verifiable Data Directory?

**Comment by rhiaro** [comment]
I like "repository", "store" and "source". "Directory" is also fine I think. Whether it is prefixed with DID or Verifiable Data is fine. I take Drummond's point that we don't want to imply the system in question is _only_ for DIDs. 

The main thing is I think we're asking for trouble if we keep using "registry" here because of the easy conflation with the Property/Parameter/Method Registries.

**Comment by peacekeeper** [comment]
Another argument against using the term "registry" (besides 1. confusion with the Property/Parameter/Method Registries, and 2. traditional association of the term "registry" with centralized systems) may be that new ideas for DID methods are becoming broader. E.g. the thread in https://github.com/w3c/did-core/issues/233 suggests that DIDs could be used to identify hashed software, or atoms in the periodic table. For those types of DIDs, the term "registry" does not seem appropriate.

**Comment by panickervinod** [comment]
I do think verifiable data Registry makes sense +1
If you see this Registry as associated with a domain or organisation I suggest Verifiable Organization DID Registry for an organisation or a particular domain.

**Comment by kdenhartog** [comment]
I've had moderate degree of success describing ledgers similar to certificate transparency logs. What about something like identifier transparency logs or transparent identifier directory to have the name indicate the similarities?

**Comment by selfissued** [comment]
When creating #277, it was glaringlyobvious, given the proximity of the uses of normal industry term "registry" and the term "DID Registry", which has an unrelated meaning, that we must replace the term "DID Registry" with something more accurate and more descriptive.  Otherwise, we're just sowing needless confusion.

**Comment by rhiaro** [comment]
@selfissued how do you feel about "Verifiable Data Registry" to align with the VC spec?

**Comment by rhiaro** [comment]
"DID registry" has been replaced with "verifiable data registry" throughout.

**Comment by brentzundel** [comment]
No comments since marked pending close, closing.

**Comment by OR13** [comment]
This ship has sailed: https://www.w3.org/TR/did-core/#dfn-verifiable-data-registry
