### ISSUE TITLE
Unmotivated statement about JSON pointers

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#164]
Section 5.7 on Fragments https://w3c.github.io/did-core/#fragment contains this sentence:
> Implementations SHOULD NOT prevent the use of JSON Pointer ([RFC6901]).

As a reader, this statement appears to come from out of the blue, without any motivation.  Why would one use or not use JSON Pointers?  If this is relevant to implementers and interoperability, we need to explain this better.  If it's not relevant, we should remove this statement.

**Comment by rhiaro** [comment]
For reference, the history of this statement is here: https://github.com/w3c-ccg/did-spec/issues/86. 

It looks like the prior paragraph is the motivation for the normative statement, but the link is not completely clear. Perhaps just removing the line break will be enough. I'll look into if there's anything else we can do make it less out-of-the-blue. The person who raised the original issue is @SmithSamuelM - any thoughts?

**Comment by rhiaro** [comment]
Related: https://github.com/w3c/did-core/issues/200

**Comment by selfissued** [comment]
@SmithSamuelM can you say what actions would and would not prevent use of JSON pointers so we can make this statement actionable to developers?

**Comment by SmithSamuelM** [comment]
JSON PTR is well documented standard that allows traversal of a JSON document mapping structure from a URL.
https://tools.ietf.org/html/rfc6901
These means anyone using clean JSON can create an URL that references a particular field in a document. JSON PTR uses the fragment. It uses it in a way that is unambiguous wrt to normal use of the fragment by starting with a #/  .    Because special semantics were being given to DID Fragment in early versions of the DID Doc there was a temptation to use special syntax that might break a JSON Ptr parser.  So the guidance is look at RFC6901 and make sure that any special syntax attached to fragments in DID URL references do not break  a JSON PTR parser. There must be an unambiguous set of rules to parsing a DID URL that allows an implementer to determine the the DID URL was meant to use JSON PTR or not.  Currently that means if the first character after the # is a / then its a JSON PTR.

**Comment by iherman** [comment]
Putting my w3c admin hat on...

At this moment, the status of the [JSON Pointer spec](https://tools.ietf.org/html/rfc6901) is "Proposed Standard". I am not really familiar with the IETF process (@msporny, can you help me out on this?), ie, I do not know what this means in term of becoming a real standard. What worries me is that the date on the document is 2013.

Formally a (W3C, but also true for other organization like ISO) standard _cannot_ refer _**normatively**_ to a document that is not a standard itself. While it is perfectly o.k. to refer to a draft now, when it comes to the DID Core spec going to Rec, this rule must be followed. There are some special derogation to this rule (e.g., the WhatWG HTML, fetch, or DOM documents), JSON Pointer is not, at present, one of the special cases (nor is JSON Schemas, b.t.w.!).

I am not sure how that translates to our document, though, i.e., what role JSON Pointer plays. If it is not a normative reference, then there is no problem.

**Comment by ChristopherA** [comment]
Actually in IETF a “Proposed Standard” is a mature standard, toughly
equivalent today to W3C Recommendation.

Many well used standards do not get past Proposed. TLS is still only a
Proposed Standard and it has been 21 years.

Internet Standard is for things that are so mature that they are going to
never change, like SMTP.

See
https://tools.ietf.org/html/rfc7127

— Christopher Allen [via iPhone]

**Comment by iherman** [comment]
@ChristopherA the issue has pushed me to look for a more 'official' W3C position. The answer I have got:

- there isn't a blanket approval for IETF Proposed Standards
- in the absence of the previous, [the general W3C policy](https://www.w3.org/2013/09/normative-references) is applicable.

Looking at the general W3C policy, and based on the stability of JSON Pointers, I believe we can argue that this normative reference would be indeed fine.

**Comment by peacekeeper** [comment]
The meaning and dereferencing rules of the fragment are determined by the MIME type of the representation of the DID document (or other resource identified by a DID URL). We cannot "override" this rule for fragment processing in either the DID Core or DID Resolution spec.

See this paragraph from the [JSON Pointer spec](https://tools.ietf.org/html/rfc6901):

> Note that a given media type needs to specify JSON Pointer as its fragment identifier syntax explicitly (usually, in its registration [RFC6838]).  That is, just because a document is JSON does not imply that JSON Pointer can be used as its fragment identifier syntax.  In particular, the fragment identifier syntax for application/json is not JSON Pointer.

Also, keep in mind that we will have different representations of DID documents. Whatever is identified by the fragment should be consistent across all of those representations (JSON, JSON-LD, CBOR, XML, etc.). This is obviously not the case if we use JSON pointers.

Issue https://github.com/w3c/did-core/issues/200 also discusses this.

The use of JSON Pointer in fragments would of course not be impossible (other uses have also been suggested, e.g. using symmetric keys in fragments to decrypt a DID document). But those uses would either override the MIME type's standard fragment rules, or would not be consistent across representations.

For these reasons, I'd also support removing the statement about JSON Pointer, or alternatively add an explanation of the implications as described above.

**Comment by SmithSamuelM** [comment]
Yes now that we have multiple encodings. The JSON ptr is limited to applicability for JSON documents mime type. The critical point is that overloading the syntax of the #  for DID fragments causes these sorts of downstream dependency.  If we remove DID fragment from the spec then we have no need to protect downstream dependencies on the fragment like JSON Ptr.  Its not that JSON ptr is impossible in other encodings that is the problem. Its the DID fragment that is the problem.  We are imposing a restriction on the fragment that is not mime typable.

**Comment by SmithSamuelM** [comment]
DID Fragment should be encoding specific. Like JSON-LD whereas JSON-PTR for clean JSON

**Comment by kdenhartog** [comment]
See PR #257

**Comment by peacekeeper** [comment]
I think the following section of [RFC3986](https://tools.ietf.org/html/rfc3986#section-3.5) is relevant here:

>    If the primary resource has multiple representations, [...] then whatever is
>    identified by the fragment should be consistent across all of those
>    representations.  Each representation should either define the
>    fragment so that it corresponds to the same secondary resource

Using JSON Pointers in fragments is not compatible with this recommendation, since it would not work consistently across multiple representations.

**Comment by SmithSamuelM** [comment]
But then doesn’t that apply to DID Fragmanet as well?   That means that we can’t have DID fragment because it DID fragment does not work consistently well across representations other than JSON-LD

**Comment by msporny** [comment]
> But then doesn’t that apply to DID Fragmanet as well? That means that we can’t have DID fragment because it DID fragment does not work consistently well across representations other than JSON-LD.

My read isn't exactly the same as Markus' read. I do agree that /if you want compatibility across representations/ then you really should use a fragment identifier that is compatible across all representation.

However, if you don't care about other representations and just want to use JSON Pointer, there is nothing stopping you from doing so. SHOULD is not a MUST, so if your reason for breaking that SHOULD is "I don't care about other representations like JSON-LD", then use JSON Pointer. You could also be compatible with fragment identifiers used across all syntaxes *and* use JSON Pointer.

I'm not seeing a problem here... what am I missing?

We just want to remove the JSON Pointer language because it's unnecessary and comes out of nowhere. There have been multiple reviewers now that felt the comment was strange and out of place.

**Comment by SmithSamuelM** [comment]
I agree that the JSON ptr  language is out of place.  I added it out of concern that the DID fragment was abusing the fragment notation.  Removing did fragment and replacing with and ID service parameter would be the appropriate solution. Then There is no need to protect clean JSON from the abuse of fragment.  Removing DID fragment also greatly simplifies resolution  logic .

**Comment by msporny** [comment]
@SmithSamuelM wrote:
> I agree that the JSON ptr language is out of place. 

There is a PR to remove it:

https://github.com/w3c/did-core/pull/257

One way to read what you wrote is that you would object to PR #257 if there isn't also language to remove DID Fragments and replace them with an "ID service parameter".

Another way to read what you wrote is that you don't object to PR #257. Removing DID Fragments is a separate issue, as is "ID service parameter"s, and you will pursue that separately.

Which one is it? We have approval to merge #257, but I don't want to do that if you're going to immediately object to it being merged.

**Comment by msporny** [comment]
I'll add text to the PR so that it's clear that things like JSON Pointer can still be used if one isn't concerned about compatability of fragments across representations.

**Comment by msporny** [comment]
Done in af251b68868ffb43855a8b480f363c59135f75f0.

**Comment by kdenhartog** [comment]
I propose we close this issue if @SmithSamuelM feels satisfied with the language in the Commit @msporny referenced in the comment directly above.

**Comment by SmithSamuelM** [comment]
I concurr
