### ISSUE TITLE
What are entityship and start-of-authority (SOA) problems?

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#165]
Section 5.9 on Persistence https://w3c.github.io/did-core/#persistence includes this statement:
> However, registering the same identifier on multiple DID registries introduces extremely hard entityship and start-of-authority (SOA) problems.

Many readers will have no idea what is meant by "entityship problems" or "start-of-authority (SOA) problems".  If these problems are relevant to readers and implementers and if we retain the uses of these terms, we need to explain them better and say why they matter.

**Comment by selfissued** [comment]
I will write a PR to remove the unclear language.

**Comment by OR13** [comment]
https://support.dnsimple.com/articles/soa-record/

for context.

**Comment by kdenhartog** [comment]
I think these problems are worth describing in a non-normative section. Had I not read it in the spec, I would have that it would have been acceptable to anchor DIDs to multiple ledgers using multiple methods. @selfissued if you want I'll take a stab at adding addition text to describe these problems in better detail.

**Comment by selfissued** [comment]
Have at it, @kdenhartog .  Otherwise, I'll write a PR to remove this unclear language soon.  Thanks.

**Comment by selfissued** [comment]
I still need to write the PR.

**Comment by rhiaro** [comment]
The languages is updated in https://github.com/w3c/did-core/commit/4a0bd8b74a1b63ea9ca644bb024996da3bdb1fd6#diff-eacf331f0ffc35d4b482f1d15a887d3bL796 so this issue can probably be closed if no objections
