### ISSUE TITLE
Statement on stable DID Registries not actionable

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#166]
Section 5.9 on Persistence https://w3c.github.io/did-core/#persistence contains this statement:
> it is RECOMMENDED that DID method specifications only produce DIDs and DID methods bound to strong, stable DID registries capable of making the highest level of commitment to persistence of the DID and DID method over time.

We should not be making normative statements that are not actionable.  Judging whether a particular system structure is likely to go defunct, be abandoned, or cease operations is a highly subjective and questionable activity.  We should not require architects or implementers to do so, as they will invariably often get it wrong.

At the very least, this should become an informational suggestion in a note, which doesn't use normative language such as "RECOMMENDED".

P.S.  Even decentralized infrastructures may cease operations for business reasons.  Individuals and organizations will make decisions about whether to pay the power bills for the servers hosting a particular decentralized infrastructure.  If they no longer see benefit from participating, they may withdraw, and if enough withdraw, the entire decentralized infrastructure may cease to operate.

**Comment by rhiaro** [comment]
I agree, this is not testable and shouldn't be normative. We could also perhaps point to the DID Rubric which offers further guidance on how to choose DID methods.

**Comment by selfissued** [comment]
I can write a PR removing the non-actionable statement and pointing to the rubric.

**Comment by kdenhartog** [comment]
took a stab at this in PR #231 can I have someone double check to make sure I did the references properly because the did-rubrics weren't included in the normative or non-normative references already. 

Also, for what it's worth the did-rubric respec doc is currently empty. I think everyone is still working in the google docs.
