### ISSUE TITLE
Term "CRUD operations" is used without being defined

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#167]
Please either define the term "CRUD" or remove its use from the specification.

**Comment by rhiaro** [comment]
The acronym CRUD occurs twice and in both places is expanded using the `<abbr>` html syntax. Is this sufficient?

**Comment by selfissued** [comment]
@peacekeeper volunteered on the 10-Mar-20 call to add the definition in the terminology section.

**Comment by peacekeeper** [comment]
@selfissued I created this PR: https://github.com/w3c/did-core/pull/226. I propose to remove the term "CRUD" altogether, rather than adding a definition.

**Comment by peacekeeper** [comment]
This has been addressed by https://github.com/w3c/did-core/pull/226 and can therefore be closed I think.

**Comment by brentzundel** [comment]
Marked pending close for more than a week. Closing.
