### ISSUE TITLE
Use of undefined term "verification method"

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#172]
The spec contains many uses of the term "verification method" but its meaning is never defined.  Furthermore, its syntax is also never defined.

The closest the spec comes to defining it is in Section 3.3 - Cryptographic Keys and Other Verification Methods https://w3c.github.io/did-core/#cryptographic-keys-and-other-verification-methods - where it states:
> A DID document can express cryptographic keys and other verification methods

So it's clear that public keys are one kind of verification method, but no others are listed or defined.

Please:

- Define the meaning of the term  "verification method"
- Define the syntax and semantics of the term
- Create a registry listing the initial set of verification methods that we intend to standardize
- Give at least one example of a verification method that is not a public key

**Comment by rhiaro** [comment]
This is a duplication of #57 which may be at least partially addressed by #123

**Comment by msporny** [comment]
PR #123 has been merged. The following requests remain from the original comment:

* Create a registry listing the initial set of verification methods that we intend to standardize
* Give at least one example of a verification method that is not a public key

**Comment by OR13** [comment]
Seems done: https://w3c.github.io/did-core/#dfn-verification-method

**Comment by selfissued** [comment]
I agree that this is done.
