### ISSUE TITLE
Should multiple "controller" values be expressible?

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#173]
Section 6.5 Delegation and Authorization https://w3c.github.io/did-core/#authorization-and-delegation states:
> A DID registry could implement a coarse-grained controller pattern by enabling DID documents to express the DID of another DID controller that controls it

Might there not be multiple such controllers for a DID?

**Comment by rhiaro** [comment]
My understanding is that this is correct, and the value of the `controller` property could be an array. This is updated in PR #123 ([preview](https://pr-preview.s3.amazonaws.com/w3c/did-core/pull/123.html#authorization-and-delegation) which is currently under review.

**Comment by msporny** [comment]
PR #123 has been merged and clearly states that the controller property allows one or more values (an array). Closing.
