### ISSUE TITLE
Meaning of statement about augmenting X.509 certificates unclear

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#175]
Section 10 Security Considerations https://w3c.github.io/did-core/#security-considerations says:
> As the root identifier records for decentralized identifiers (DIDs) and DID documents are a vital component of decentralized identity management. They are also the foundational building blocks of decentralized public key infrastructure (DPKI) as an augmentation to conventional X.509 certificates.

In what way do DIDs augment conventional X.509 certifications?

**Comment by OR13** [comment]
I'm in favor of not mentioning X.509...

**Comment by rhiaro** [comment]
This text is no longer in the spec.

**Comment by selfissued** [comment]
Closing, having verified @rhiaro 's comment that the text in question is gone.
