### ISSUE TITLE
Unsubstantiated statement about protecting against attacks when compromised

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#176]
Section 10 Security Considerations https://w3c.github.io/did-core/#security-considerations says:
> Protecting against an attack when a system is compromised requires external key-signing hardware.

First, a reference substantiating this assertion should be provided.  Second, is the ability to reliably use DIDs on compromised systems really in scope for this specification?  Why or why not?

**Comment by selfissued** [comment]
I will re-read this in context and create a PR.

**Comment by OR13** [comment]
Consider pulling from:

- http://www0.cs.ucl.ac.uk/staff/I.Brown/pfs2.html
- https://debian-administration.org/article/450/Generating_a_revocation_certificate_with_gpg

**Comment by burnburn** [comment]
Mike reaffirms he will create a PR.
