### ISSUE TITLE
Use of undefined term "object capabilities"

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#177]
Section 8.4 Security requirements https://w3c.github.io/did-core/#security-requirements states:
> It is currently expected that there will be an attempt to create a generalized authorization mechanism that is build on object capabilities.

But the term "object capabilities" isn't defined or commonly understood.  That makes the intended meaning of the note fairly opaque.

**Comment by rhiaro** [comment]
Would adding an informative reference to [the wikipedia article about object capabilities](https://en.wikipedia.org/wiki/Object-capability_model) solve this issue?

**Comment by rhiaro** [comment]
I just noticed that text is in an ISSUE block, suggesting it is likely temporary anyway.

**Comment by selfissued** [comment]
Please do remove it, as @rhiaro suggests.
