### ISSUE TITLE
Underspecified statement on combining timestamps with signatures

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#178]
Section 10.2.1 Proving Control of a DID and DID Document says:
> It is good practice to combine timestamps with signatures.

The specification contains no guidance on how or why one might do that or what the benefits of doing so would be.  Please add that guidance.

**Comment by OR13** [comment]
For example:

- https://tools.ietf.org/html/rfc7519#section-4.1.6

**Comment by kdenhartog** [comment]
Does this PR #227 which is meant to address issue #181 address the issue or are you looking for it to just be defined in the terminology section?

**Comment by rhiaro** [comment]
> Does this PR #227 which is meant to address issue #181 address the issue or are you looking for it to just be defined in the terminology section?

That PR didn't address #181, just fixed a typo in a link. I think this issue is separate, but a one or two sentence editorial addition.

**Comment by yancyribbens** [comment]
This one can be assigned to me.

**Comment by yancyribbens** [comment]
I think the purpose behind this is to timestamp update and create operations using a secp256k1 commitment for example which proves the did controller performed this operation and when.

**Comment by rhiaro** [comment]
A PR ^ that addresses this was merged

**Comment by brentzundel** [comment]
No comments since marked pending close, closing.
