### ISSUE TITLE
[PURPOSE OF THE SPECIFICATION] Is this draft specification trying to address too many topics when there should be more than 1 spec

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#18]
@mwherman2000 moved from CCG (https://github.com/w3c-ccg/did-spec/issues/121)

**Comment by talltree** [comment]
I reviewed the discussion in https://github.com/w3c-ccg/did-spec/issues/121. While I believe that a case could be made for the DID spec to be broken into multiple specifications, I note the consensus reached on the [DID WG Charter](https://www.w3.org/2019/09/did-wg-charter.html):

> The Working Group will:
> 
> 1. Define the DID URI scheme.
> 2. Recommend a data model and syntax(es) for the expression of Decentralized Identifier Documents, including one or more core vocabularies.
> 3. Recommend a set of requirements for DID Method specifications that are conformant with the data model and syntax(es). The DID Method specification authoring requirements will recommend a list of mandatory and optional operations, with associated descriptions, which are expected to be defined in DID method specifications.

As an editor who has been working on the DID spec from the very start, I can attest that all three of these parts are so closely related that they are best defined in one specification. Reasons:

- First, the DID URI scheme definition section is quite short and simple. 
- Second, the ABNF rules used to define the DID scheme need to be referenced throughout the DID document definition and DID method definition sections.
- Third, the DID document definition needs to be referenced throughout the DID method definition section.
- Fourth, all of these sections need to be reference by one set of Privacy Considerations and Security Considerations sections.
- Fifth, if they are defined together, then one uniform set of terminology can be defined to be used across all of these sections.
- Lastly, putting them all in a single specification makes it much easier to explain how the three parts relate.

Given this, I believe there would need to be a very strong reason to break them into separate specifications.

**Comment by msporny** [comment]
> I believe there would need to be a very strong reason to break them into separate specifications.

This was reiterated in the most recent W3C DID WG F2F meeting in Amsterdam. The specification isn't going to broken apart at this point. Closing.
