### ISSUE TITLE
Confusing statement about key revocation on DLTs

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#180]
Section 10.7 Key Revocation and Recovery https://w3c.github.io/did-core/#key-revocation-and-recovery says:
> In general, checking for key revocation on DLT-based methods is expected to be handled in a manner similar to checking the balance of a cryptocurrency account on a distributed ledger. That is, if the balance is empty, the entire DID is deactivated.

This is a very confusing explaination.  In what sense would a DID have a cryptocurrency balance?  Please rework this description so that its intended meaning is clearer.

**Comment by msporny** [comment]
> In what sense would a DID have a cryptocurrency balance?

The BTCR DID Method has cryptocurrency balances.

**Comment by OR13** [comment]
Related: https://github.com/w3c/did-core/pull/224

DID ETHR has balance...

**Comment by peacekeeper** [comment]
This could potentially be moved into the DID Implementation Guide (https://github.com/w3c/did-imp-guide), since it may be relevant to certain DID method implementations but not generically applicable to all DIDs.

**Comment by selfissued** [comment]
The fact that some specific methods have cryptocurrency balances doesn't make this statement comprehensible to most readers.

**Comment by dlongley** [comment]
Not every DLT-based DID method will use cryptocurrency ... perhaps it can say "DLT-based DID methods that use cryptocurrency" or something along those lines.

**Comment by OR13** [comment]
its an example, or how to consider something revoked... given that the specific method of revocation is up to the DID Method, I see this as sufficient, for the purposes of providing an example...

**Comment by kdenhartog** [comment]
I wrote a PR to use a more common example that aligns with section 7.3 of the text. Of note, Issue #168 addresses a similar subject and may make this example a bit more contentious to include.
