### ISSUE TITLE
Use of undefined term "verifiable timestamps"

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#181]
Section 12.3 Timestamps https://w3c.github.io/did-core/#timestamps opens with a use of the term "verifiable timestamps" but doesn't say what those are, what their properties are, or why their use would be beneficial.  Please define this term and explain what its significance is.

**Comment by OR13** [comment]
See also:

- https://blog.cloudflare.com/roughtime/

**Comment by selfissued** [comment]
Someone who understands the intent of the term should add a definition.

**Comment by yancyribbens** [comment]
The URL in the paragraph is outdated and is now here: https://github.com/bitcoin/bips/blob/master/bip-0113.mediawiki.

**Comment by yancyribbens** [comment]
A new PR to close this issue is open [here](https://github.com/w3c/did-core/pull/271)

**Comment by kdenhartog** [comment]
closing this. Looks like we've had a PR address @selfissued original concerns and it's been labeled as pending close for a week now.
