### ISSUE TITLE
Use of undefined term "resource"

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#182]
The specification is replete with uses of the term "resource" but doesn't define it, its syntax, or its properties.  An example use of term is:
> A DID URL always identifies the resource to be located.

What things can be resources and what things cannot be?  For instance, might the resource sometimes be the DID Subject?  Might it sometimes be the DID Document?  etc.

**Comment by philarcher** [comment]
I suggest that the definition of resource given in RFC7231 would probably suffice https://tools.ietf.org/html/rfc7231#section-2 - it's certainly my working definition.

**Comment by rhiaro** [comment]
The definition in RFC7231 is very HTTP centric, so I think it'd need adapting for DIDs although the basic premise is the same. Something like..?

> The target of a DID resolution or dereferencing request is called a "resource".  This specification does not limit the nature of a resource, but defines an interface that might be used to interact with resources.

**Comment by msporny** [comment]
This has been fixed in #243. Closing unless there are objections.

**Comment by brentzundel** [comment]
No objections raised, closing
