### ISSUE TITLE
Add support for experimental context

### ISSUE THREAD

**Issue by OR13** [w3c/did-core#188]
(edited to remove snark)

We have integration and interoperability tests for did methods that use JSON Schema and/or JSON-, here: https://github.com/decentralized-identity/context

It has been requested that I open a PR to move this work to did-core.

>The following is a non-exhaustive list of public key properties used by the community: publicKeyPem, publicKeyJwk, publicKeyHex, publicKeyBase64, publicKeyBase58, publicKeyMultibase, ethereumAddress.

Many of these are still not supported today, and fixing the documentation for them using the current URL structure is prohibitively difficult... I will not trace down w3id.org redirects to several repos to fix security context documentation... nobody else is going to do this either.

Here is my proposal:

1. W3C hosts a "did-latest.jsonld" which at regular intervals is finalized in versions, like v0.12..
2. W3C hosts a "did-latest.md" of the human readable documentation for all terms used by DIDs.
2.1 We can update this to respec, after definitions are resolvable for all properties, not before.
3. w3id.org redirects to w3c hosted context files and human readable definitions.

I won't open a PR until we have a clear agreement on how to document security related concepts like `publicKeyJwk`... for example using the DIF context, we have;

https://identity.foundation/context/did-latest#publicKeyJwk

and 

```
"dif": "https://identity.foundation/context/did-latest#",
...
 "publicKeyJwk": {
          "@id": "dif:publicKeyJwk",
          "@type": "@json"
        },
```

**Comment by msporny** [comment]
The DID WG Chairs need to schedule time for interested participants to discuss this item in a separate call. We need an encompassing proposal.

**Comment by OR13** [comment]
I propose storing all JSON-LD,  JSON-Schema, CBOR definitions in the core registry, and establishing a versioning, caching / redirect strategy for the registry and that the registry will have minimal human readable definitions, mostly pointing to did-core, or ccg references... attempting to avoid repetition while also consolidating documentation.

**Comment by OR13** [comment]
I'm closing this, its basically blocked by the did core registries setup process. and its not actionable by itself.
