### ISSUE TITLE
[Design Goals] all references to *identifier* management etc. should be changed to *DID Entity* management, etc.

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#19]
@mwherman2000 moved from CCG (https://github.com/w3c-ccg/did-spec/issues/123)

**Comment by talltree** [comment]
In section 1.2 (Design Goals) of the [Final Community Group Report DID spec](https://w3c-ccg.github.io/did-spec/), it says the following under the goal of "Decentralization" (emphasis added):

> Eliminate the requirement for centralized authorities or single points of failure in **identifier management**, including the registration of globally unique identifiers, public verification keys, service endpoints, and other metadata.

I reviewed the discussion in https://github.com/w3c-ccg/did-spec/issues/123. I don't see any case (nor did anyone except the original poster of the issue) to change "identifier management" to "DID entity management". "DID entity" is not a defined term in the Final Community Group Report DID spec, nor it is proposed to be a defined term (the closest term would be "DID Subject").

I propose that this issue be closed if there is no objection in the next week.

**Comment by msporny** [comment]
Agreement to close issue as the specification states what the DID WG intended it to state, no objections, closing.
