### ISSUE TITLE
Seeking clarification around authentication, public keys, and verification apparatus

### ISSUE THREAD

**Issue by ewelton** [w3c/did-core#193]
Reading through @jandrieu and @dlongley excellent conversation in #190 caused me to review what has been said about 'verification methods', 'verification relationships' - including authentication and public_keys sections, etc.

I see that there is still a large disconnect in the DID community around these issues - and while there is work that is being done to address these issues, it is not well integrated with the broader community and this causes a significant amount of repetitive and unnecessary friction.

Let's look issue #57 and #172 - @selfissued provides a very sensible list (that we should address!) in #172 as follows:

> - Define the meaning of the term "verification method"
> - Define the syntax and semantics of the term
> - Create a registry listing the initial set of verification methods that we intend to standardize
> - Give at least one example of a verification method that is not a public key

And thankfully, efforts to do most of that have been in place to address exactly this set of concerns since November 2019 - although the [PR](https://github.com/w3c/did-core/pull/123/files/24244d19a1f8fc13f005f354d6bbc7bc7d20fdd7) from #123 was not integrated until 7 days ago, or almost a week after @selfissued 's request.  @dlongley also provided a nice description of verification methods in #57 - in fact, #57 has a lot of very compelling text, including notes by @selfissued, @dlongley, @dhh1128 and @awoie - suggesting that ethereumAddresses might provide an example of a verification method that is not a public key. 

And verification methods are the things that are clustered by verification relationships.   The 'authentication' VR is the one we talk about all the time, to the point that I think the community is, generally speaking, not aware that there are others - instead we are thinking of attaching proof-purposes to the keys listed in the authentication section and "stretching" the semantic of authentication to fit this new understanding.  This begs the question then, why have a public_keys section at all because what would be the sense of a public_key that is *not associated in any way* with a verification relationship?

This is the confusion that played out yet again, in issue #190 which was born out of this same confusion in issue #4 .  So that's #123, #57, #4, #190, #172 - and perhaps others, all revolving around the same general theme - confusion over these "DID-document" fields

- authentication
- public_keys
- capabilityInvocation
- capabilityDelegation
- keyAgreement
- assertionMethod

and the concepts of
- proof purpose
- verification relationship
- verification method

I believe that sorting out the concepts involved is a requirement if we are going to have a shot at a spec.  So I hope we can do something like that here.  I'm not sure a github issue is the right venue, but if not, it is, at least, a good starting point from which we can link to a solution.

Question:
- what is a non-public key version of a verification method
I think I saw some references to non-public key based verification methods in one of the comment streams, but I would value any pointers.  One comment in #57 mentioned the use of ethereumAddresses, which opens the door to 'method specific' verification.  Would a biometric verification, or an external process be viable, or are DIDs effectively restricted to "crypto and crypto-like" material?

- how do verification relationships and proof-purposes differ
These terms get tossed around a lot - perhaps we can identify some of the active discussion around the issue.  Would a side-document or appendix in the spec, or as some sort of Note make sense?  Should these be linked with use-cases highlighting where a VR and a PP diverge?

- what is the point of the public_keys element
I find the public_keys element curious, in that it specifies public_keys outside of the context of a verification-relationship.  At present the spec really does not address why the element is there but iit expresses a lot about public keys, leaving the concept of a publicKey outside of the context of a verification-relationship puzzling.  It is as if to say ```this is a key associated with the subject in some way, and I want to publicize it, i just don't want to say why or how to use it, just tell you it is there```.  I had previously assumed that it would just contain the public_keys and that the various verification-relationships would "point into it" so that you didn't have to duplicate the key material over and over.  It seemed like a simple "structural issue" - albeit one that makes the mistake of viewing the DID-document as a physical document.

- can we inventory verification-relationships
Before we build the `@context` describing the verification-relationships, and before we use that `@context` to populate the central registry supporting the LD-allergic, we will benefit from a simple, local, inventory of verification-relationships.  I think this inventory might have helped streamline the discussion in #190 .

I am not sure how to tackle this confusion - but there does seem to be a clear, and relatively simple model here, and one that pretty much fits everything I've seen in the comment stream - the problem is only that we're viewing it differently.   Kinda like this : https://www.thingiverse.com/thing:15232

So first, and foremost - any suggestions on how to address the above questions - alternatives to github issue?  Multiple github issues?  Internal/temporary reference document in the repository?

**Comment by ewelton** [comment]
i think we can close this issue.  It was just a request for information and clarification about what is happening to DIDs - i'm confident that I have sufficient information to address my engineering concerns moving forward - so figure we can close?

**Comment by msporny** [comment]
Closing issue based on issue submitter's suggestion.
