### ISSUE TITLE
[Public Keys] re: referenced keys: Is multiple level recursion allowed?

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#20]
@mwherman2000 moved from the CCG (https://github.com/w3c-ccg/did-spec/issues/143)

**Comment by selfissued** [comment]
What is the specific question being asked?  A key has a specific value and there's nothing recursive about it.

**Comment by selfissued** [comment]
I propose that we close this, because the question makes no sense.

**Comment by dlongley** [comment]
I suggest we close -- request doesn't make sense. And you can reference anything you want via identifiers as many times as you like (open world data model), but that doesn't mean we will specify any thing like that in the core.

**Comment by peacekeeper** [comment]
I wanted to mention that @kdenhartog did a presentation during a recent DID Resolution meeting that involved referencing keys across different DID documents:

- https://github.com/w3c-ccg/meetings/tree/gh-pages/2020-01-23-did-resolution
- https://docs.google.com/presentation/d/1zUkE7Awc84C9ZVahPsmg0fk9IOcdANz1MdEfF95ywKQ/

This presentation envisions a property called `publicKeyRef`, which I think matches closely the intention of @mwherman2000 's original request.

So I don't agree that this issue doesn't make sense - it does to me. However I believe that the proposed functionality can be implemented via extensions of representations such as JSON-LD, and/or that it can be added to the [DID Implementation Guide](https://github.com/w3c/did-imp-guide). Therefore I'd say that this doesn't necessarily belong into DID Core and that we can close this issue.

**Comment by msporny** [comment]
I don't think we even need publicKeyRef... why can't you just point to a key in another DID Document? In any case, I agree w/ Markus that there are mechanisms (`id` and URLs) that allow us to point to other places on the Internet with the spec today.

**Comment by brentzundel** [comment]
Seeing no objections raised to closing this issue.

**Comment by kdenhartog** [comment]
> I don't think we even need publicKeyRef... why can't you just point to a key in another DID Document? In any case, I agree w/ Markus that there are mechanisms (`id` and URLs) that allow us to point to other places on the Internet with the spec today.

I suppose this is possible if people write their resolution process to handle this case. As Markus said, I think this doesn't necessarily belong in DID Core spec though as it has to do with the resolution process.
