### ISSUE TITLE
Add resolution procedure for relative URL references

### ISSUE THREAD

**Issue by msporny** [w3c/did-core#201]
A more general form of this was raised (in https://github.com/w3c-ccg/did-spec/issues/80 and https://github.com/w3c/did-core/issues/11) requesting that the group considers how relative URL references are resolved against a BASE URL (presumably, the DID subject identified by the DID Document).

The specification is currently silent wrt. what the BASE URL is and how relative URLs are resolved against that BASE URL.

We should specify that the BASE URL is the value of the top-level `id` property in the DID Document and relative URLs are resolved by normalizing them according to standard path/query transforms and then truncating the result to the BASE URL (which is more or less what happens in HTTP, Javascript libraries, and HTML links... so developers won't be surprised by the transformations).

**Comment by dhh1128** [comment]
+1 This feels like a reasonable plan to me.

**Comment by OR13** [comment]
Yes, having this would be very useful. There are lot of cases where EDV / DIDComm interoperability is impacted by the decision to use or not use `id` properties that look like `#primary` or `did:example:123#primary`... safest thing to do will probably always use `did:example:123#primary`, but it would be nice for the shorter variants to be formally supported.
