### ISSUE TITLE
JSON LD Explanatory Text is extraneous

### ISSUE THREAD

**Issue by jricher** [w3c/did-core#206]
The JSON LD explanation and justification text currently in the serialization section does not belong in this specification. Those using JSONLD will already know what it is and don't need to have it explained. Those not using JSONLD don't care. It should be removed from the document, and certainly doesn't belong in a section on how to represent content on the wire. It's our responsibility to tell people how to take a DID document to and from a given representation, not extol the virtues of any representation above another.

**Comment by OR13** [comment]
related: https://github.com/w3c/did-core-registry/issues/3

**Comment by rhiaro** [comment]
I can make a PR for this, and the editors (or group as a whole) can decide whether or not to merge it.

**Comment by rhiaro** [comment]
The text about JSON-LD from the serialization section is no longer present in the spec, since the restructure. Suggest that this issue can be closed.

**Comment by OR13** [comment]
This has been pending close with no objection for 14 days.

**Comment by jricher** [comment]
@OR13 @rhiaro Unless I'm missing something, it's still in Appendix E where I moved it when I submitted the restructure, and it has not been removed. This issue should remain open until that section is removed, potentially with its contents re-incorporated into appropriate parts of the document. I personally think the content does not add anything.

**Comment by OR13** [comment]
Ahh, you mean this section here: https://w3c.github.io/did-core/#json-ld-extensibility

I agree.

**Comment by brentzundel** [comment]
[this comment](https://github.com/w3c/did-core/issues/206#issuecomment-603327953) objects to closing. Removing `pending close` label.

**Comment by msporny** [comment]
I moved this to the DID Implementation Guide, which is what we agreed to do at the DID WG F2F meeting in Amsterdam: 

https://github.com/w3c/did-imp-guide/commit/304c6194f25acb0cb6208b526828ad62560030ea

Once I merge @jricher's PR, we can close this.
