### ISSUE TITLE
Add section on extensibility and conformance

### ISSUE THREAD

**Issue by jricher** [w3c/did-core#207]
This document defines how to create and use DIDs and documents that are conformant to a global international standard. In particular, the use of the registry for properties is the only guaranteed method for two independent implementations to be able to work together. However, it's always possible for two specific implementations to agree to use a property or encoding, or for an implementation to use something internally. 

Relates to #205

**Comment by OR13** [comment]
Should this be moved to did core registries?

**Comment by talltree** [comment]
This will be addressed by the Extensibility subsection of Section 6 that I'm writing on the Data Model. I plan to submit the PR this week and will include wording to this effect.

**Comment by talltree** [comment]
Update: please see [PR 241](https://github.com/w3c/did-core/pull/241) for the text of section 6 that addresses this issue. If folks are satisifed, this issue can be closed.

**Comment by rhiaro** [comment]
@jricher does the [additional text about extensibility](https://w3c.github.io/did-core/#extensibility) address this issue?

**Comment by brentzundel** [comment]
If there are no objections raised, we will close this issue in 7 days.

**Comment by brentzundel** [comment]
Marked `pending close` for more than a week with no comment, closing.
