### ISSUE TITLE
Who or what can be a DID Controller?

### ISSUE THREAD

**Issue by kdenhartog** [w3c/did-core#210]
As I've been reading through the issues trying to tease out who we're referring to when we use the term "DID Controller". There's a few edge cases I've been thinking about that I think make the usage a bit fuzzy.

Typically when I read issues ( #122 #4 ) we speak about a controller as "the entity (or entities) who has (have) the ability to change the DID Document". However, where this confuses me is that the "entity" is most often software, or a combination of software with human interactions (user says "create this DID for me"). Where this seems to stretch the thinking for me is what happens when the software behaves in a method incompatible with the expectation of the person who is the "controller". Is the controller the person (even though things didn't go as expected), the software, or maybe even the software author (in the case when the author intentionally designed the software incorrectly aka malware). Additionally what if the "entity" is incapable of making a decision (e.g. our classic IoT and guardianship use cases). Is the controller the software or the author of the software?

Finally, here's a really interesting way to bend the language. Imagine the subject is a plot of land and the agent acting on its behalf is a smart contract that automatically moves payment and updates possession of the deed by adding a public key to the DID Document. In this case, the smart contract doesn't present proof to commit an update but rather updates autonomously based on the logic within the contract. For example the current land owner (aka seller) submits a txn to the contract stating intent to sell and the price. This state indicates the land is "on the market". Then a buyer could submit payment to the contract such that the contract automatically moves payment to the sellers account and updates the key in the did document to the buyers public key. The land, which is the subject of the DID Document is now "owned" by the buyer (represented using the new public key), however, it could be argued the smart contract is really the "controller" because it was the one who "updated the key in the did document". 

With this in mind, I think we should be considering how software plays into the dynamic of the controller, so that we can more accurately describe the controller within the spec. However, before I submit a PR in this direction I want to see where other people land on this issue. 

@jandrieu thoughts on this?

**Comment by talltree** [comment]
@kdenhartog While I agree that all the permutations you describe can apply, I don't feel any of them need to change the definition of a DID controller as the entity that controls the DID document. 

(Note: I do think we need to tweak the definition slightly to say:)

> The entity that has the ability **to create or** make changes to a DID document.

But other than that, the role of software as a tool for such an entity to use to exert that control seems to be subsumed (and rightly so) by this definition. In fact different DID methods may specify different ways that control can be exerted by combinations of human and non-human actors and that's all fine.

**Comment by kdenhartog** [comment]
Sorry, I've been away on vacation so I'm just now getting back to this.

My take was that subsuming "entity" to mean both the entity and the software leads to a poor mental model about control. Specifically, because the entity is more than likely not evaluating the software to validate it's behaving in expected ways.

So why does this matter?
The main reason I believe this matter is because it explicitly calls out that the software that represents the entity serves a separate role that requires an explicit decision by the entity, or whoever makes decisions on behalf of the entity, to decide if the software can be trusted. While I think this is understood to a degree within the WG, I find that often times we forget about the edge cases because of the language we currently use. Specifically, the edge case of software behaving maliciously.

This also becomes useful for later readers to recognize very quickly that DIDs are used to identify meatspace entities and are not actually identifying the software that works on the entity's behalf (hopefully). Using the browser as an analogy, a DID would not represent the browser and the User. Rather it only represents the User, but the language currently doesn't identify this.

My proposal would be to change the definition of controller from
 > The entity that has the ability to make changes to a DID document. A DID can have more than one controller. The DID controller(s) are denoted by the controller property on the top level of the DID document. Note that the DID controller(s) might include the DID subject. 

To
> The entity that has the ability to authorize an entity agent to make changes to a DID Document. A DID can have more than one controller. The DID controller(s) are denoted by the controller property on the top level of the DID document. Note that the DID controller(s) might include the DID subject.

and to add the definition for entity agent:

> A piece of software that acts on behalf of a controller to make changes and represent the controller in digital form.

Side note: I'd like to add something about fiduciary responsibility to the controller, but I think that's a bit more contentious, so I left it out for now.

**Comment by kdenhartog** [comment]
@talltree so I've been thinking about this a bit more after reading through issue #213 and I think the part that trips me up is around the issue of sovereignty. If we assert that the controller is making statements about the subject then it's not the subject with sovereignty. Rather it's the controller (aka what I'm referring to as the entity agent) who possess sovereignty (aka software) and if the software is written to altruistically include the subject (aka the person) then combining the two makes sense. 

However, my concern is that if we assume that the two are combined (e.g. the software agent **is** the subject) but the software is malicious, then the reliability of the claims made by the subject are also put into question when facetious claims are made. By teasing these two apart, we allow for the ability to question the claims of the software and the subject independently, unless explicitly bound (e.g. entity agent has fiduciary responsibility). The reason I believe this is important is similar to the justification of why an IP address does not constitute a person similar to what was ruled in [Malibu Media, LLC, v. John Doe](https://www.scribd.com/document/214110295/213923681-Gov-uscourts-flsd-434635-10-0?ad_group=111346X1569475X3149821452016d325c03d3ffaefdf395&campaign=SkimbitLtd&keyword=660149026&medium=affiliate&source=hp_affiliate)

In practice today, as shown in the linked case, we cannot constitute the actions of software as being the same as the person who is using it. Therefore, I don't think it makes sense for us to assume the two are the same thing unless made explicit.

**Comment by msporny** [comment]
Looks like this may get resolved if the PRs referenced above make it into the spec. @kdenhartog, can you confirm, please?

**Comment by kdenhartog** [comment]
Agreed. Once those changes make it in I'll close this.
