### ISSUE TITLE
[Authentication] Is Authentication the correct mechanism for specifying the ownership of a Thing? 

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#22]
@mwherman2000 moved from CCG (https://github.com/w3c-ccg/did-spec/issues/148)

**Comment by msporny** [comment]
This may be a duplicate of issue #2.

**Comment by msporny** [comment]
This issue will be closed soon unless there is an objection to the changes made to address the issue.

**Comment by msporny** [comment]
The authentication section was expanded to address the issue raised. No further requests have been made to change the section. Closing.
