### ISSUE TITLE
Clarify language around what the items in `service` should/must be

### ISSUE THREAD

**Issue by llorllale** [w3c/did-core#234]
The definition for [`service`](https://w3c.github.io/did-core/#dfn-service) says (emphasis mine):

> If a DID document includes a service property, the value of the property **SHOULD** be an array of service endpoint objects. Each service endpoint MUST have type and serviceEndpoint properties, SHOULD have an id property, and MAY include additional properties. 

I'm confused by the first SHOULD in this definition. The array of items in the `service` property can either be a `serviceEndpoint` object or something else. If this is true by design then the normative language should be downgraded to *MAY*. But then the followup question would be, how are `service` and its items defined in the data model? Can't we define some base properties that a service must have (eg. "location")?

**Comment by rhiaro** [comment]
I'm not 100% sure so I'd like an editor's confirmation, but I think that SHOULD may imply that if it's not an array of objects, then it could be an array of URIs that point to objects.

I believe "how are `service` and its items defined" is answered by:

> Each service endpoint MUST have `id`, `type`, and `serviceEndpoint` properties, and MAY include additional properties. 

Perhaps what you're also asking is for the `serviceEndpoint` object (inside `service`) to have some properties defined?

which indeed defines some base properties that a service must have.

**Comment by llorllale** [comment]
@rhiaro your words and another read of the text clarifies things for me, thanks.

I was getting tripped up by the MUST that follows the SHOULD I highlighted above. My original and erroneous interpretation was: "the items in this list may or may not be service endpoint objects but they must have type and serviceEndpoint properties"
