### ISSUE TITLE
make publicKey section more explicit for understanding of DIDs reliance on public keys

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#24]
@kdenhartog moved from CCG (https://github.com/w3c-ccg/did-spec/issues/166)

**Comment by jandrieu** [comment]
Based on my review of the issue in the ccg did-spec, it seems there was consensus around my framing as stated:
>  Or more succinctly, the Subject is the resource *referred* to by a DID.
> The DID Document is the resource *resolved* by a DID and dereferenced by
> default. A service is the Resource *dereferenced* by a DID with a service
> component.
>
> In any case, the DID Document does not describe the subject. Framing it
> that way will lead to compromised privacy when people start putting PII in
> publicly retrievable DID Documents.

I'd like to get a sense of whether or not we've addressed this per Kyle's last comment in the current draft:
> Given the comments that have streamed from this discussion I better understand the context of why requiring keys is overly scoped because in many different use cases key management is not necessary. I feel satisfied in terms of understanding in how we're moving forward and would like to move forward with closing out this issue. What are the next steps we need to take given what appears to be consensus achieved on this subject?

**Comment by jandrieu** [comment]
@kdenhartog Have you seen the latest draft in relation to this issue?

**Comment by ChristopherA** [comment]
I do be believe that *currently* we are reliant on traditional public keys (aka one-to-one mapping of a private key and a public key). However, new forms of cryptography are emerging where the traditional public key one-to-one mapping are not true, for instance, multisigs, adaptor signatures, etc.

So we want to be careful to future proof this. 

-- Christopher Allen

**Comment by msporny** [comment]
@ChristopherA I believe we have future proofed this in the spec and there is a desire to be aware and continue to fight to do so in the WG. I also believe that @kdenhartog's concerns were addressed long ago.

This issue will be closed soon unless there is an objection.

**Comment by ChristopherA** [comment]
@msporny Can you point me to an anchor URL where you believe this future proofing is addressed? I didn’t spot it (spec is getting big! )

**Comment by msporny** [comment]
> @msporny Can you point me to an anchor URL where you believe this future proofing is addressed? I didn’t spot it (spec is getting big! )

See the note at the end of this section: https://w3c.github.io/did-core/#public-keys

Specifically, 

> A public key is just one type of verification method. A DID document expresses the relationship between the DID subject and a verification method using a verification relationship. Examples of verification relationships include: authentication, capabilityInvocation, capabilityDelegation, keyAgreement, and assertionMethod. A DID controller MUST be explicit about the verification relationship between the DID subject and the verification method. Verification methods that are not associated with a particular verification relationship MUST NOT be used for that verification relationship. See Section § 7.4 Authentication for a more detailed example of a verification relationship.

That section needs an editorial pass to make things more clear, but I believe that the intent is there and further editorial passes will further enforce these distinctions.

**Comment by kdenhartog** [comment]
yup, my concerns were addressed awhile back.
