### ISSUE TITLE
(Partially) Encrypting DID Documents 

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#25]
@RieksJ moved from the CCG (https://github.com/w3c-ccg/did-spec/issues/172)

**Comment by msporny** [comment]
Editors should add a section to the security considerations section of the specification stating that encryption can be used to encrypt data, but that encrypting data placed on DLTs is generally a bad idea, and should only be done for data that is sensitive in the short term (weeks, months), and not for data that's sensitive over years (e.g., banking records, long lived PII, etc.)

**Comment by dlongley** [comment]
Whether the data is on DLTs isn't necessarily the main thing that is relevant; it's more that it's a publicly available document. Encryption should be used in confidential channels -- or it should be assumed that it will eventually be broken and the cleartext information will be made available to the same audience that the encrypted information is available.

**Comment by talltree** [comment]
This security consideration continues to be raised, and I agree it that this consideration should be added to the Security Considerations section. I have this action item.

**Comment by talltree** [comment]
This is on the list of editorial tasks I have tasked for this week.

**Comment by rhiaro** [comment]
PR was merged to add text about this to security considerations. Can this be closed?

**Comment by RieksJ** [comment]
Yes. Thanks. Rieks

**Comment by peacekeeper** [comment]
Can this be closed now after @rhiaro 's PR https://github.com/w3c/did-core/pull/228 has been merged?

Perhaps @RieksJ has any further feedback, as the one who originally created the issue in the CCG?
