### ISSUE TITLE
List of early implementations conforming to spec?

### ISSUE THREAD

**Issue by codi0** [w3c/did-core#258]
I realise the spec itself wouldn't be the place for this (perhaps the implementation guide or something related to it?), but I've tried and failed to find a list of any existing / in progress implementations that are attempting to conform to v1.0 of the spec.

Do any such implementations exist? If so, is there a list of them somewhere or could one be created to list them somewhere?

**Comment by nikosft** [comment]
May be this list helps https://w3c-ccg.github.io/did-method-registry/
Furthermore I usually find useful DID and VC related software in these repositories

- https://github.com/decentralized-identity
- https://github.com/digitalbazaar/
- https://github.com/bcgov/

**Comment by OR13** [comment]
when we add support for this in the registry, we should make sure we can list multiple implementations for the same did method...

**Comment by msporny** [comment]
Migrating this issue to https://github.com/w3c/did-spec-registries/ where we should add a column for links to implementations.

Marking this as pending close.

**Comment by brentzundel** [comment]
No comments since marked pending close, closing.
