### ISSUE TITLE
Definition of the term "client" in regard to SSI principles

### ISSUE THREAD

**Issue by marceljay** [w3c/did-core#261]
I think it would help to clarify what the term `client` means in the current spec's context. Providing some pragmatic examples to illustrate the role in terms of e.g. DID creation, could help understanding.

The usage of the term confused me in regard to DID CRUD operations and storage of cryptographic key material. There is probably some connection to the term [DID Controller](https://www.w3.org/TR/did-core/#dfn-did-controllers), which likewise, is quite abstract. 

Especially if we discuss the significance of SSI (human identity) and it's second rule `Control. Users must control their identities.` I would like to understand the relation to decentralization aspects. This confusion on my part is furthermore amplified since some teams working on DIDs make use of the term `Self-Sovereign Identity Provider` which by itself sounds a bit centralized.

**Comment by kdenhartog** [comment]
This is a more simple way of wording the problem that I was trying to describe in #210 

It might be worth taking a look at that issue as well, but I'm in support of adding some language around what you've described.

Heads up @talltree this seems similar to that other discussion we were having over there.

**Comment by OR13** [comment]
client "a program that is capable of obtaining a service provided by another program."... in the context of DIDs, i think its the same... anything that uses a resolver is probably a client of a resolver... etc...

**Comment by peacekeeper** [comment]
I would be in favor of replacing "client" with "DID controller" in sections 7.2.1, 7.2.3, and 7.2.4, and replacing it with "requesting party" in section 7.2.2, in line with the recently merged https://github.com/w3c/did-core/pull/350.

As for other occurrences of the term "client" in the spec, I would replace or clarify them on a case-by-case basis. In some cases, I think we can replace "client" with "implementation" or "application" or "DID resolver".

**Comment by peacekeeper** [comment]
@marceljay do you have any further thoughts on this and about my last comment? I'd be happy to try write a PR to address this issue.

**Comment by peacekeeper** [comment]
@marceljay any further thoughts on this? Otherwise I will try to write a PR to replace or clarify the term "client" throughout the document.

**Comment by marceljay** [comment]
Sorry, I am working on a different project and haven't had looked into the spec ever since.

 I think your suggestions are very beneficial. I would add that in those cases where the spec refers to actual software, I would make that clear, just as you suggested. 
e.g. `client-application` or `client-implementation`could work well too.

**Comment by peacekeeper** [comment]
I think this was addressed by https://github.com/w3c/did-core/pull/393 and we should be able to close this issue.. Any objections?

**Comment by brentzundel** [comment]
No comments since marked pending close, closing.
