### ISSUE TITLE
did parameter equivilance

### ISSUE THREAD

**Issue by kdenhartog** [w3c/did-core#270]
As I understand it with the following did document

```
{
   "id": "did:example:123",
   "authentication": ["id": "did:example:123#key1"],
   "publicKey": [{
        "id": "did:example:123#key1",
        ......
    }]
}
```

if I'm checking the proofPurpose of authentication I think everyone would agree that `did:example:123#key1` would be valid and within the authentication proof purpose. However, what I'm less certain about is if `did:example:123?id=key1` would also be accepted as a valid didUrl that falls within the scope of the authentication proof purpose.

Any thoughts on this and is anyone aware of people using this didUrl format?

**Comment by peacekeeper** [comment]
@kdenhartog since https://github.com/w3c/did-core/pull/139 has been closed now, I think it's clear now that `did:example:123#key1` is the only DID URL that should be used to reference a public key inside a DID document, would you agree?

**Comment by kdenhartog** [comment]
Ahh didn't see that issue was closed. For the sake of simplicity, yes I would agree. Should be fine to close this one as well then. Thanks
