### ISSUE TITLE
Ambiguity around necessity of populated top-level DID Document 'id' property

### ISSUE THREAD

**Issue by csuwildcat** [w3c/did-core#274]
In the section (https://w3c.github.io/did-core/#did-subject) that talks about the `id` property at the top level of the DID Document, the text indicates the property must contain a single DID when resolved, but it brings up a question: does resolution include whatever JSON-LD would do to it? I ask because we are using the JSON-LD `@base` feature to project the ID to all the other references in the Doc, and if that is part of resolution, then technically you can leave the property as `id: ""` and the `@base` mechanics will populate the field with the ID string specified in the `@base` value. I would love if this was allowed, because I don't have to needlessly print that string in yet another place.

**Comment by kdenhartog** [comment]
I think this should be good, but @msporny @dlongley or @dmitrizagidulin would be best to take a look at it too. Additionally, how does this align with JSON compatibility would be an outstanding question I think needs more clarity in my mind?

**Comment by nikosft** [comment]
Does not the NOTE in the same section cover your question?

> DID method specifications can create intermediate representations of a DID document that do not contain the id key, such as when a DID resolver is performing DID resolution. However, the fully resolved DID document always contains a valid id property. The value of id in the resolved DID document is expected to match the DID that was resolved.

I understand that the resolved document must contain `id` but other intermediate representations of the document without the `id` can exist.

**Comment by csuwildcat** [comment]
This does seem specified clearly now, but I think we should add a note about the use of `@base` for JSON-LD representations so that relative IDs are populated throughout the document. I will open a new issue (if one does not exist) to address this.
