### ISSUE TITLE
Specifications needed for supported key representations publicKeyJwk, publcKeyPem, and publicKeyBase58

### ISSUE THREAD

**Issue by selfissued** [w3c/did-core#281]
The specification describes use of the key representations publicKeyJwk, publcKeyPem, and publicKeyBase58 that are not defined by the specification.  These need to be added to the specification so that their syntax and semantics are defined.

**Comment by kdenhartog** [comment]
related topics: #280 #63 #236 #23

**Comment by OR13** [comment]
Related: https://github.com/w3c/did-spec-registries/issues/46

**Comment by OR13** [comment]
We are going to discuss on the next topic call.

**Comment by msporny** [comment]
We should close this, but we might want to raise a new one about publicKeyPem... really, this is out of scope for the group (based on the special topic call).

**Comment by OR13** [comment]
recommend closing.

**Comment by OR13** [comment]
Raised https://github.com/w3c/did-core/issues/374 for removing publicKeyPem... suggest closing.

**Comment by msporny** [comment]
This issue has been marked pending close as the specification now defines publicKeyJwk, publcKeyPem, and publicKeyBase58. Additionally issue #374 exists to remove publicKeyPem and use publicKeyJwk instead.

This issue will be closed in 7 days unless there are objections.

**Comment by brentzundel** [comment]
No objections raised since marked pending close. Closing.
