### ISSUE TITLE
PING Horizontal Review

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#291]
- [x]  fill out the [Security and Privacy Questionnaire](https://www.w3.org/TR/security-privacy-questionnaire/) 
- [x] Contact the PING asking for review.

**Comment by brentzundel** [comment]
@jonathan-consensyshealth volunteered to fill out the questionairre

**Comment by jonnycrunch** [comment]
Will forward to my friend and colleague @jonathan-consensysHealth.   Would someone please forward me the submission from the VC working group.  Also, I'll need help with the threat model section.

**Comment by wyc** [comment]
@agropper and myself have volunteered to help draft the responses

**Comment by agropper** [comment]
https://www.eff.org/document/2020-08-04-letter-eff-and-aclu-opposing-ab-2004
seems related.

**Comment by wyc** [comment]
@agropper @jonnycrunch due to the time passed, would you like to reconvene later this week or early next week and prepare a working item for comments? hopefully there has been some progress on the service endpoint discussions

**Comment by jonnycrunch** [comment]
yep, how is Monday again?  I'll send an invite.

**Comment by wyc** [comment]
+1, probably a good idea to inform the public did wg list after we figure out where/when.

We can use the CCG Jitsi instance here: https://meet.w3c-ccg.org/DIDSecurityPrivacyReview

**Comment by agropper** [comment]
+1 for 2PM EST?

**Comment by brentzundel** [comment]
@agropper @wyc @jonathan-consensysHealth what is the status of the security and privacy questionnaire?

**Comment by wyc** [comment]
@brentzundel and those following, the latest response is here:
https://docs.google.com/document/d/13qLCZcks3OAb2V7GHcrSs8s9drA5OaqEPYPI1knmodc/edit#

My apologies, I think I was supposed to write an update to the list and forgot. We are preparing to begin work on sections 3 and 4, but we there were 2 major concerns around scope that would impact the models in those sections significantly:
- DID methods can vary wildly in their function, side effects, and privacy implications. To what point do we address this in the response? Based on his comments in the doc, Orie seems to think that we should focus only on the data models described and not delve too far into these.
- Same concern and question for service endpoints.

**Comment by msporny** [comment]
We need to have the Security Questionnaire done for this issue to be closed. We cannot close this issue until PING does a review on the specification.

**Comment by OR13** [comment]
I am adding myself to track contributing to the questionnaire.

**Comment by shigeya** [comment]
I added a few changes. Reviewed until 2.16.

**Comment by kdenhartog** [comment]
We're getting closer on the security questionaire with sections covering all of the security parts (section 3), but it appears that section 4 needs to be added still. Also, who is currently handling editorship of this document so that we can get the comments merged/resolved? If no one has time to do this I'm happy to step in and carry this to the end, but I'll need editor rights to the document.

@OR13 @wyc @agropper @jonnycrunch

**Comment by OR13** [comment]
@kdenhartog I added some details, but IMO this needs an editorial merging session, and then we should focus on the weakest parts.

**Comment by OR13** [comment]
I think the first checkbox is done now?

**Comment by brentzundel** [comment]
PING has been contacted for review.
Leaving this issue open to track horizontal review efforts.

**Comment by burnburn** [comment]
PING response of "no blocking issues":  https://lists.w3.org/Archives/Public/public-privacy/2021JanMar/0021.html

**Comment by agropper** [comment]
I'm reminded of the compiler message: "None of the errors detected."

Adrian

**Comment by brentzundel** [comment]
Link to invitation for Security review of Decentralized Identifier Specification v1.0: https://lists.w3.org/Archives/Public/public-web-security/2020Dec/0003.html

No response was received and no issues were raised.

**Comment by brentzundel** [comment]
Horizontal review is complete, closing
