### ISSUE TITLE
Should we be allowed to multi-reference keys through did documents?

### ISSUE THREAD

**Issue by kdenhartog** [w3c/did-core#301]
Imagine we've got the following did document structures:

```
{
  id: "did:example:conglomerate",
  publicKey: [
  {
    id: "did:example:conglomerate#key1",
    type: "EddsaVerificationKey2018",
    base58: "a-base58-encoded-key",
  }],
  assertionMethod: ["did:example:business-unit#key2", "did:example:conglomerate#key1"]
}
```

and did:example:business-unit did Document looks like this:
```
{
  id: "did:example:business-unit",
  publicKey: [
  {
    id: "did:example:business-unit#key1",
    type: "EddsaVerificationKey2018",
    base58: "a-base58-encoded-key",
  },
  {
    id: "did:example:business-unit#key2",
    type: "DidUrlKeyReference"
    reference: "did:example:sub-division#key1"
  }
],
  assertionMethod: [ "did:example:business-unit#key2", "did:example:business-unit#key1"]
}
```

and did:example:sub-division did doc looks like this:

```
{
  id: "did:example:sub-division",
  publicKey: [
  {
    id: "did:example:sub-division#key1",
    type: "EddsaVerificationKey2018",
    base58: "a-base58-encoded-key",
  }
],
  assertionMethod: [ "did:example:sub-division#key1"]
}
```

This is essentially the same as this pseudocode:
```
global var1 = memoryLocation(0x11111111)

callerFunction() => {
const booleanResult = function1(var1); // should return false because function1 negates it
expect(booleanResult).toBe(false);
}

function1(fnVar1) => {
  !function2(fnVar1);
};

function2(fnVar2) => {
 return fnVar2 === var1; // should return true because the memory locations match
}
```

The use case where I'm imaging this would be used is did:example:conglomerate is a business conglomerate with `did:example:business-unit` being a business unit of `did:example:conglomerate`. And `did:example:sub-division` is a sub-business division of business unit, `did:example:business-unit`.

What this means is that `did:example:bussiness-unit` can sign on behalf of `did:example:conglomerate` without `did:example:conglomerate` not needing to directly reference every key managed by it's sub-divisions of it's various business units.

However, there's an implicit trust relationship between `did:example:conglomerate` and it's reference to `did:example:business-unit#key2`. For example, an attacker could compromise `did:example:business-unit` and point `#key2` to `did:example:malicious-attacker#key1` and now malicious-attacker key1 can be used to sign on behalf of `did:example:conglomerate`. 

This is similar to booleanResults expected function1 contract that it will return false because it's negating the result of function2. If it were to stop negating function2, then the logical expectation in the callerFunction would fail.

Should this be allowed? 

I tend to lean towards the answer is "No, it shouldn't be allowed" because the implicit trust relationship will be abused at some point and keys will be able to falsely represent did subjects. If others agree with me, then we don't need to make any changes to the specification and this can be close. However, the flip side is multi referencing keys enables easier management of did-documents which can be a very powerful feature. I'm curious, where do others land on the topic?

@dlongley or @msporny I suspect you guys may have thought through this case already because I see JSON-LD examples that do the direct referencing use cases in the spec.

**Comment by peacekeeper** [comment]
I remember you discussed something similar at a DID Resolution call a while ago (see [here](https://github.com/w3c-ccg/meetings/tree/gh-pages/2020-01-23-did-resolution)), using matrix parameters back then.

I don't have a clear solution for this. One idea could be to use standard semantic web mechanisms such as `owl:sameAs` rather than introducing new terms `DidUrlKeyReference` and `reference`. E.g.:

```
{
  id: "did:example:business-unit",
  publicKey: [
  {
    id: "did:example:business-unit#key1",
    type: "EddsaVerificationKey2018",
    base58: "a-base58-encoded-key",
  },
  {
    id: "did:example:business-unit#key2",
    "owl:sameAs": "did:example:sub-division#key1"
  }
],
  assertionMethod: [ "did:example:business-unit#key2", "did:example:business-unit#key1"]
}

```

**Comment by kdenhartog** [comment]
Yeah pretty much the same. I like the reuse of the attribute `owl:sameAs` as well. I'm realizing this seems like a concern much more specific to how a resolver should work and falls squarely outside what we want to define here. With that, as much as I'd like to solve this here, I'm leaning towards solving these types of issues in the resolution spec.

Thoughts on just closing this and refiling on resolution spec @peacekeeper?

**Comment by peacekeeper** [comment]
> Thoughts on just closing this and refiling on resolution spec @peacekeeper?

Up to you I think.. There are already some potentially related issues in DID Resolution e.g. https://github.com/w3c-ccg/did-resolution/issues/7 or https://github.com/w3c-ccg/did-resolution/issues/36, so you could definitely re-create this issue over there. OTOH you could also first wait a few more days to see if others want to comment here..?

**Comment by peacekeeper** [comment]
@kdenhartog since there haven't been other comments, how about we close it here and re-open either in [DID Resolution](https://w3c-ccg.github.io/did-resolution/) or in the [Implementation Guide](https://github.com/w3c/did-imp-guide)?

**Comment by kdenhartog** [comment]
Ok migrated it to DID Resolution where I think it's best addressed. Closing this issue as well.
