### ISSUE TITLE
Add links to the definition of "lowercase"

### ISSUE THREAD

**Issue by xfq** [w3c/did-core#313]
In https://www.w3.org/TR/2020/WD-did-core-20200421/#normalization :

> The DID scheme name MUST be lowercase.
> The DID method name MUST be lowercase.

It would be useful to add a definition of "lowercase" and link to it.

For example, the definition can be:

> An **ASCII lowercase letter** is a Unicode code point in the range U+0061 (a) to U+007A (z), inclusive.

And the text in the normalization section can be changed to:

> The letters in the DID scheme name MUST be `<a>`ASCII lowercase`</a>`.
> The letters in the DID method name MUST be `<a>`ASCII lowercase`</a>`.

**Comment by rhiaro** [comment]
PR #319 updated to include this

**Comment by iherman** [comment]
@xfq can you check https://cdn.statically.io/gh/w3c/did-core/rhiaro-edit-methods/index.html#did-syntax to see if #319 answers your comment?

**Comment by iherman** [comment]
@xfq if you are satisfied, can you also sign off https://github.com/w3c/did-core/issues/105 to make it clear that the I18n review is satisfactorily closed?

**Comment by xfq** [comment]
> @xfq can you check https://cdn.statically.io/gh/w3c/did-core/rhiaro-edit-methods/index.html#did-syntax to see if #319 answers your comment?

Yes, it looks good to me. Thank you.

**Comment by xfq** [comment]
> @xfq if you are satisfied, can you also sign off #105 to make it clear that the I18n review is satisfactorily closed?

Just commented in https://github.com/w3c/did-core/issues/104
