### ISSUE TITLE
How are we distinguishing "core" properties vs "extension" properties?

### ISSUE THREAD

**Issue by kdenhartog** [w3c/did-core#317]
I've seen us discuss a few properties now as additions (current one is `representation` discussed in #199 ), but I haven't identified the distinction between what makes something a "core" property vs "extension" properties. As far as I can tell, core properties right now are probably best described as properties that are used by at least two did methods (and can be added while DID spec is still in flight). Does this align with others thoughts on the topic?

**Comment by rhiaro** [comment]
My understanding is "core" properties are defined in the DID Core spec, and go in by working group consensus.

I don't think we've formally set a bar for when a property can be 'nominated' for inclusion in the spec, but "used by at least two DID methods" seems reasonable and I've heard it mentioned as a criterion a few times.

I wouldn't assume that _only_ being used by two DID methods is enough though - someone still needs to propose adding them to the Core spec, and the WG needs to agree.

**Comment by kdenhartog** [comment]
That satisfies my concern, I'll plan on closing this issue here soon. Leaving it for a few days so others get a chance to comment as well.

**Comment by brentzundel** [comment]
No comments since marked pending close, closing.
