### ISSUE TITLE
Additional information/proxy service type

### ISSUE THREAD

**Issue by dlongley** [w3c/did-core#329]
We have had a number of discussions around supporting a service that could be expressed in a DID Document and used to provide additional information about the DID subject. We have closed a few issues that included comments related to this subject, such as:

https://github.com/w3c/did-core/issues/199#issuecomment-588296477
https://github.com/w3c/did-core/issues/64#issuecomment-587551401

...without adding a service type to the spec to handle the feature. The aim of this issue is to get a name for this service type and flesh out the definition so we can get this feature into the spec before we hit feature freeze in the near future.

One problem, of course, is naming/bikeshedding :). In an effort to move us towards a name and a definition that can go into the spec -- and based on the discussions that have been had, here's a description of the service I believe we're looking for:

**BikeshedServiceType** - A service of this type would be used to express additional information related to the DID subject. This service may or may not require authorization to access the information. The information provided by the service could be expressed using existing standards such as Verifiable Credentials. Such a service can be used to help prevent unwanted correlation or to express information that should not be expressed in a DID Document that is provided by a system that does not support data deletion.

Using such a service is expected to involve a simple HTTP GET -- which will either fail with an unauthorized error or it will return additional information about the DID subject that is self-describing, for example, in JSON-LD format, potentially including VCs. It could also express information using properties and values from the DID spec registries for other formats. If the endpoint requires authorization, it would be up to the requester to negotiate a means to obtain authorization from the DID controller, for example, the requester could be given a capability enabling access.

This service is not intended to have a significant amount of complexity in its protocol, rather, one use case for it is to enable expressing *additional* services that might have more complexity without having to express those services directly in the DID Document.

**Comment by agropper** [comment]
This issue overlaps with #324 as illustrated by @jandrieu https://github.com/w3c/did-core/issues/199#issuecomment-588321105 where he says: 

> In my professional opinion, the DID subject should ALWAYS be in the loop for any disclosure of information.

#324 uses SHOULD instead of @jandrieu ALWAYS but I think we're both making same point about privacy.

**Comment by dmitrizagidulin** [comment]
Bikeshed proposals for naming that Service Type:

* `ProfileProxy` orrrr
* `PrivacyProxy`

**Comment by agropper** [comment]
Mediator (as in
https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0046-mediators-and-relays/README.md)
could then point to either a messaging or an access control or a storage
endpoint.

**Comment by dlongley** [comment]
This can be discussed in a service endpoints special call.

**Comment by dlongley** [comment]
This issue depends on the discussion in #382.

**Comment by msporny** [comment]
This issue needs to result in a concrete PR before we go into CR. If it doesn't, the issue will be deferred to the next version of the specification. A PR needs to be submitted in the next 30 days.

**Comment by jandrieu** [comment]
The term that has settled in a few different requirements conversations I've been in is "negotiatior". That is, the service endpoint of type "negotiator" provides a means for negotiating an appropriate service for interacting. It may be that

1. the DID Controller doesn't want to reveal anything and the negotiatior (after some back and forth of some kind) will return no additional information, 
2. the parties are able to find a mutually satisfactory medium of interaction after a private set intersection, or
3. based on something revealed during negotiation, the Controller is willing to give a direct telephone number

That said, I think the actual service type should map directly to the API that will be used by the service endpoint. Although I describe a nice conceptual foundation for an interesting endpoint, the type should be set by the implementers/creators of the API that will be used for such negotiation.

I support closing this as we are unlikely to get that much detail in the next 30 days.

-j

**Comment by msporny** [comment]
Closing issue based on input from original issue submitter (@dlongley) -- if we need to define this, it will be done in the registries. No further action is required by the DID WG.

**Comment by OR13** [comment]
https://github.com/w3c/did-spec-registries/issues/157

^ i have opened this issue to remove the undefined term from the registry :)
