### ISSUE TITLE
DID Syntax

### ISSUE THREAD

**Issue by Crenshinibon** [w3c/did-core#333]
I'm not totally sure (because I don't really speak ABNF fluently, if at all) but there might be a slight flaw in the DID syntax spec. Just to reiterate:

> did                          = "did:" method-name ":" method-specific-id
> method-name         = 1*method-char
> method-char           = %x61-7A / DIGIT
> method-specific-id  = *( ":" *idchar ) 1\*idchar
> idchar                      = ALPHA / DIGIT / "." / "-" / "_"

I understand the intention, and from the examples of valid DIDs that I have come across so far, I think the "method-specific-id" part should allow defining "sub-methods" (separated with a colon) to enable the construction of a hierachy.

But the current spec has a problem here. Due to the fact, that the "method-name" part is already ending in a mandatory colon (first line) the current "method-specific-id" definition implies, that you have to have two colons if you intend to use the colon as a means to establish that hierarchy. Maybe an example helps:

did:web:someid123456789 (valid)

did:web:somesubmethod:someid123456789 (invalid! ... since the later colon isn't allowed, because it can't have other "idchar"s in front of it)

did:web::somesubmethod:evendeeper:someid123456789 (valid)

I'm not sure if this is intentional, since the examples I have seen so far don't include a double colon.

A simple fix might be:

> method-specific-id = *( ":" 1\*idchar ) / 1\*idchar

(the "or" to allow "idchar"s before the colon, and the additional 1* in the first part, to disallow multiple colons ...)

I'm pretty new to this stuff and stumbled in my test cases about this "problem", where I translated the ABNF to regexp for DID validation.

Just as a suggestion, it would be great if you could include validation RegExp into the Spec as well. That would be really handy, from an implementors perspective.

**Comment by peacekeeper** [comment]
@Crenshinibon thanks for this observation. The current ABNF was introduced by https://github.com/w3c/did-core/pull/216.

Allowing a double-colon was intentional.

But I completely agree that it looks like you found a bug here. And your fix looks good too. Do you want to raise a PR for this?

**Comment by peacekeeper** [comment]
@Crenshinibon thanks for this observation. The current ABNF was introduced by https://github.com/w3c/did-core/pull/216.

Allowing a double-colon was intentional. But I completely agree that it looks like you found a bug here.

**Comment by Crenshinibon** [comment]
Or maybe:

method-specific-id = *( ":" *idchar ) / 1*idchar

**Comment by peacekeeper** [comment]
> Or maybe:
> 
> method-specific-id = *( ":" *idchar ) / 1*idchar

Does this really solve the bug? I think it would still not allow e.g. `did:web:somesubmethod:someid123456789` for the same reasons you explained in your original message?

**Comment by Crenshinibon** [comment]
I think it would, because the second part (after the "or") kicks in after the mandatory "method-name" colon ... allowing "somesubmethod" ... and the rest is reflected by the first part

**Comment by peacekeeper** [comment]
No, it doesn't (I just tried it with [this](www.parse2.com/)). You're right that the second part after the "or" kicks in, but then it can't "go back" to the first part again, i.e. no more colons allowed.

**Comment by Crenshinibon** [comment]
Ah yes. I see. So you would have to change:

did = "did:" method-name ":" method-specific-id

to

did = "did:" method-name ":" 1\*method-specific-id

or do this:

method-specific-id = 1\*(*( ":" *idchar ) / 1\*idchar)

The solutions you proposed probably work as well.

**Comment by Crenshinibon** [comment]
While I'm still thinking about it. Why not explicitly introduce "sub-method-name"? Like so:

did  = "did:" method-name ":" *(sub-method-name ":") method-specific-id
sub-method-name = 1*idchar
method-specific-id = 1*idchar

Looks simple enough. Or am I missing something.

**Comment by peacekeeper** [comment]
We should probably not change the `did` rule, only the `method-specific-id` one. It seems we have the following proposals now:

- `method-specific-id = *( ":" / idchar ) 1*idchar`
- `method-specific-id = *( *idchar ":" ) 1*idchar`
- `method-specific-id = 1*(*( ":" *idchar ) / 1*idchar)`

**Comment by Crenshinibon** [comment]
I think the one in the middle is the most succinct definition. Not sure if I fully understand all edge cases, though.

**Comment by peacekeeper** [comment]
+1, the middle one also makes most sense to me..

**Comment by Crenshinibon** [comment]
I have created a pull request. It's been some time since my last one. So I hope I did everything right.

**Comment by peacekeeper** [comment]
Thanks! Let's wait a bit to give others some time to review..

**Comment by talltree** [comment]
I have reviewed and approved. Good catch, @Crenshinibon.

**Comment by talltree** [comment]
Recommend closing this issue as the PR has been merged. If no objection, it will be closed in 7 days.

**Comment by OR13** [comment]
lets close this :)
