### ISSUE TITLE
Add relative-ref DID URL parameter

### ISSUE THREAD

**Issue by peacekeeper** [w3c/did-core#349]
Since matrix parameters were removed from the DID URL syntax, one consequence is that an extra DID URL parameter is needed that can contain an encoded service endpoint path and query string. This has been originally mentioned by @dlongley in https://github.com/w3c/did-core/issues/159#issuecomment-598286814 and used again in an example use case described by @OR13 in https://github.com/w3c/did-core/issues/327. This DID URL parameter would always be used in conjunction with the `service` parameter which is already in the spec.

Example

`
did:ex:123?service=files&relative-ref=%2Fmyresume%2Fdoc%3Fversion%3Dlatest%23intro
`

**Comment by msporny** [comment]
Yes, we need to add this.
