### ISSUE TITLE
Confusing example in the section 3.2.1 - DID parameters are URI query strings

### ISSUE THREAD

**Issue by Fak3** [w3c/did-core#353]
There is a confusing sentence near the end of section [3.2.1](https://w3c.github.io/did-core/#generic-did-url-parameters):

> DID parameters SHOULD NOT be used if there are already other, equivalent ways of constructing URIs that fulfill the same purpose (for example, using other syntactical constructs such as URI query strings or URI fragments). 

The example in the parenthesis mentions "other syntactical constructs such as URI query strings or URI fragments", as an alternative to DID parameters, but DID parameters **are** URI query strings themselves. Perhaps this sentence was valid before the deprecation of matrix-parameters? Now it seems confusing - because according to the section 3.2.4 all URI query strings **MUST be** DID Parameters (generic or method-specific)

**Comment by peacekeeper** [comment]
@Fak3 I agree with you, this is a remnant of the version of the spec that had matrix parameters. I think the sentence should simply be removed. Do you agree with this? If yes, would you like to raise a PR to do this?
