### ISSUE TITLE
Restrict the number of key representation members

### ISSUE THREAD

**Issue by OR13** [w3c/did-core#356]
`publicKeyJwk`, `publicKeyBase58`.... you should only be allowed to use 1 of these in a did core vm.

Someday it will be obvious which of these is the most common for all key types.

**Comment by OR13** [comment]
cc @msporny as discussed on the call.

**Comment by msporny** [comment]
Yes, agreed... the reasoning being that we don't want people to try to express the same key in two different formats and accidentally put in two different keys. By restricting to one used vs. the other, we eliminate a lot of error checking code.

**Comment by OR13** [comment]
I believe a normative statement here, would address this issue:

https://w3c.github.io/did-core/#verification-methods

we should generalize this to account for non public key verification material.

**Comment by OR13** [comment]
We need to add guidance that you cannot include multiple key representations in the same verification method. needs pr.

**Comment by OR13** [comment]
Needs a PR saying "don't out private material" in did documents.

**Comment by rhiaro** [comment]
Looks like this is done and can be closed?

**Comment by OR13** [comment]
agreed, this should be closed.

**Comment by msporny** [comment]
Issue submitter agrees that the issue has been addressed. Closing.
