### ISSUE TITLE
Inconsistency between using key or value to define different types

### ISSUE THREAD

**Issue by JelleMillenaar** [w3c/did-core#358]
Recently, the DID standard got updated to include five verifiable relationships. The set of verifiable relationships are an array of authentication methods that all implement the same fields. The key has been used to differentiate the verifiable relationships from each other such instead of a field. This conflicts with how types are implemented for services and public keys.  This is seen back in the current DID working draft, which has to describe the different verifiable relationships while linking to the DID specification registries to add more. This is not the case for public key types as the different verification method types are not defined in the DID working draft, but are to be registered in the DID specification registry. 

I propose to clean up the DID working draft and simplify the DID Document structure by introducing a new optional field inside of a public key object called "purpose" (Happy to change the name). The purpose field will indicate what type of verifiable relationship the public key carries out. This will significantly reduce the complexity of a DID Document as the DID Documents will now consist of a set of base properties and two fields that contain arrays of objects, publicKey and service. In addition, similarly to service and public key types, the verifiable relationships are now out of scope for the DID working draft and should be registered at the DID specification registry. 

Example Old style:

    {
         ...
         "capabilityDelegation": [{ 
             "id": "did:example:123#z6MkpzW2izkFjNwMBwwvKqmELaQcH8t54QL5xmBdJg9Xh1y4",
             "type": "Ed25519VerificationKey2018",
             "controller": "did:example:123",
             "publicKeyBase58": "BYEz8kVpPqSt5T7DeGoPVUrcTZcDeX5jGkGhUQBWmoBg"
        }],
        ...
    }

Example new style:

     {
         ...
         "publicKey": [{ 
             "id": "did:example:123#z6MkpzW2izkFjNwMBwwvKqmELaQcH8t54QL5xmBdJg9Xh1y4",
             "type": "Ed25519VerificationKey2018",
             "purpose": "capabilityDelegation",
             "controller": "did:example:123",
             "publicKeyBase58": "BYEz8kVpPqSt5T7DeGoPVUrcTZcDeX5jGkGhUQBWmoBg"
         }],
         ...
    }

**Comment by dlongley** [comment]
This has been discussed before, see #273 and #294 for similar issues. I recommend we close this as as duplicate.

**Comment by msporny** [comment]
Duplicate, closing in 7 days unless @JelleMillenaar objects.

**Comment by brentzundel** [comment]
no objections raised, closing.
