### ISSUE TITLE
Fill or remove section on DID URL Dereferencing

### ISSUE THREAD

**Issue by peacekeeper** [w3c/did-core#364]
A section on [DID Resolution](https://w3c.github.io/did-core/#did-resolution) has been added (https://github.com/w3c/did-core/pull/331). A section on [Metadata Structure](https://w3c.github.io/did-core/#metadata-structure) has also been added (https://github.com/w3c/did-core/pull/347).

We also have an empty placeholder section on [DID URL Dereferencing](https://w3c.github.io/did-core/#did-url-dereferencing), which we should either fill, or remove. Let's discuss in this new issue.

If there is support for having this section, we should be able to re-use content from existing PRs such as https://github.com/w3c/did-core/pull/253/.

For example, an abstract DID URL dereferencing function could look like this (analogous to the `resolveStream` function):

```
dereferenceStream ( did-url, did-url-dereferencing-input-metadata ) ->
    ( did-url-dereferencing-metadata, content-stream, did-document-metadata )
```

**Comment by wyc** [comment]
@peacekeeper how does your work found in the CCG relate to this section?
https://w3c-ccg.github.io/did-resolution/

I have been reviewing https://github.com/w3c/did-core/pull/253

**Comment by peacekeeper** [comment]
@wyc the idea is that DID Core will only contain definitions of abstract functions with their inputs and outputs.  The `resolve()` function has already been added in https://w3c.github.io/did-core/#did-resolution. This issue is now about adding the `dereference()` function in a similar way.

DID Core however would leave out implementation details such as resolver architectures, protocols, metadata data formats, algorithms, etc.. The DID Resolution spec in the CCG is meant to be the place for such content that goes beyond the abstract function definition.

**Comment by peacekeeper** [comment]
This was addressed by https://github.com/w3c/did-core/pull/381. Closing.
