### ISSUE TITLE
Are we okay with not testing DID URL's query?

### ISSUE THREAD

**Issue by wyc** [w3c/did-core#385]
As we move towards progressing the test suite in https://github.com/w3c/did-test-suite, we have some final considerations around DID URL.

1. We use URI's [query definition](https://tools.ietf.org/html/rfc3986#section-3.4), which does not have a definitive stance on its content and interpretability, only its form of `query = *( pchar / "/" / "?" )`. It also hints that `query components are often used to carry identifying information in the form of "key=value" pairs`. Are we okay with this allowance? Namely we allow for DID URLs with a valid `query` that can have potentially unexpected forms, including but not limited to query parameters not conforming to the `name=value` style, duplicate entries, or character littering:
- `did:deadbeef:cafe?c0ffee`
- `did:deadbeef:cafe?proof=true&proof=false`
- `did:deadbeef:cafe?&&&&&&&&&&&&&&&&`

Note that https://github.com/w3c/did-core/issues/384 correctly captures the normative statement, and nothing past that.

2. We are committing to usage of URI's [path-abempty](https://tools.ietf.org/html/rfc3986#section-3.3).

If no one has objections in 2 weeks then I will simply close the issue.

**Comment by peacekeeper** [comment]
@wyc thanks for bringing this up. Based on your earlier insights regarding DID URL syntax, we merged https://github.com/w3c/did-core/pull/360 a few weeks ago, and we now simply use the RFC3986 `query` rule instead of enforcing a name=value pattern. I think this change was correct.

I don't think this means that we can't test the name=value pattern in DID URLs. After all, we're saying the following, which is also one of the normative statements in https://github.com/w3c/did-core/issues/384:

> If a DID query is present, it MUST be used as described in Sections § 3.2.1 Generic DID URL Parameters and § 3.2.2 Method-Specific DID URL Parameters.

I think this means we can and should test the name=value pattern, but by using a programmatic query parsing approach, instead of direct ABNF matching.

**Comment by peacekeeper** [comment]
Quick note that @OR13 has worked on tests for the DID URL query and DID parameters: https://github.com/w3c/did-test-suite/blob/master/packages/did-core-test-server/src/services/scenarios/did-parameters/did-parameters-positive-tests.js

This seems to use the https://www.npmjs.com/package/querystring library for parsing the query.

I think this works well even though the ABNF doesn't mandate the key=value format anymore.

@wyc do you still have concerns about this? What can we do to address this issue?

**Comment by peacekeeper** [comment]
@wyc any more thoughts on this? Personally I believe there is no problem here. The test suite already shows that we can test a DID URL's query even though we don't enfore the key=value pattern in the DID URL ABNF anymore.

You also mentioned you would close this in 2 weeks if there are no objections. So I'll mark this as "pending close", but feel free to add more thoughts and/or propose how to improve this.

**Comment by wyc** [comment]
No objections, thank you for your follow-up. You have already noted what would've been my only concern, that the test acceptance is implied by the functionality of the `querystring` package, which is acceptable to me.
