### ISSUE TITLE
[Absract] "proof purposes" is a new term but is not defined anywhere in the document

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#39]
@mwherman2000 moved from CCG (https://github.com/w3c-ccg/did-spec/issues/213)

**Comment by rhiaro** [comment]
"proof purpose" is no longer in the abstract (or anywhere except some example comments..), I think we can close this issue.

**Comment by dlongley** [comment]
We want to define the term, so we should keep the issue open. The way a DID controller expresses authorized verification methods is via proof purpose relations: i.e., "verification methods [X, Y, Z] can be used to verify proofs made for the purpose of Z (e.g., "authentication", "assertionMethod", "capabilityInvocation", ...)".
