### ISSUE TITLE
Section "Authentication and Verifiable Claims": Add language about legal identity

### ISSUE THREAD

**Issue by peacekeeper** [w3c/did-core#390]
Issue https://github.com/w3c/did-core/issues/151 was created a while ago in DID Core to consider mentioning of the E.U.'s [eIDAS framework](https://en.wikipedia.org/wiki/EIDAS). While in DID Core we probably don't want to go into details about eIDAS specifically, it could be useful to add some considerations about legal identity in general.

Section ["Authentication and Verifiable Claims"](https://w3c.github.io/did-core/#authentication-and-verifiable-claims) already talks a bit about binding a DID to something in the real world. We could do the following:

- Add a sentence or two to explicitly mention the possibility to bind DIDs to a legal identity (this has also been called LESS - Legally-Enabled Self-Sovereign Identity).
- Perhaps rename the section to "Real-World Identity".

----

This is one of four inter-related issues: https://github.com/w3c/did-core/issues/390 **(this one)**, https://github.com/w3c/did-core/issues/391, https://github.com/w3c/did-use-cases/issues/102, https://github.com/w3c/did-imp-guide/issues/2

**Comment by peacekeeper** [comment]
@Oskar-van-Deventer and/or others, would you be interested in adding some language about bindings DIDs to a legal identity? I can also work on this.

**Comment by peacekeeper** [comment]
@Oskar-van-Deventer and/or others, would you be interested in adding some language about binding DIDs to a legal identity? I can also work on this.

**Comment by Oskar-van-Deventer** [comment]
Markus @peacekeeper,
Within eSSIF-Lab, we have four partners that are all involved in binding SSI entities to legal identities (eIDAS).
-ComKYC - Commercio
-SSI4TDM - JoinYourBit SRL
-OBDID - OffBlocks
-SSI eIDAS Bridge - ValidatedId S.L.
Which of these four do you deem most competent on "Legally-Enabled Self-Sovereign Identity)"? Perhaps we should ask one of them to contribute here?
Oskar

**Comment by msporny** [comment]
We need this issue to result in a concrete PR to the specification in the next 30 days. If that doesn't happen, this issue will be deferred to a future version of the specification.

**Comment by peacekeeper** [comment]
I think this has been addressed by https://github.com/w3c/did-core/pull/466 and can be closed. @Oskar-van-Deventer do you agree?

**Comment by brentzundel** [comment]
No comments since marked pending close, closing.
