### ISSUE TITLE
Section "Authentication and Verifiable Claims": Add subsection about key security

### ISSUE THREAD

**Issue by peacekeeper** [w3c/did-core#391]
Issue https://github.com/w3c/did-core/issues/151 was created a while ago in DID Core to consider mentioning of the E.U.'s [eIDAS framework](https://en.wikipedia.org/wiki/EIDAS). While in DID Core we probably don't want to go into details about eIDAS specifically, it could be useful to add some considerations about the security of private keys and other secrets.

Section ["Security Considerations"](https://w3c.github.io/did-core/#security-considerations) already talks a bit about key expiration, revokation, recovery. We could do the following:

- Add a subsection with technical considerations about the security of keys, maybe with a reference to the FIDO attestations concept.

Issue https://github.com/w3c/did-core/issues/176 and PR https://github.com/w3c/did-core/pull/369 are loosely related to this.

----

This is one of four inter-related issues: https://github.com/w3c/did-core/issues/390, https://github.com/w3c/did-core/issues/391 **(this one)**, https://github.com/w3c/did-use-cases/issues/102, https://github.com/w3c/did-imp-guide/issues/2

**Comment by peacekeeper** [comment]
@awoie would you be interested in adding some content related to the security of keys, FIDO assertions, LoAs?

**Comment by peacekeeper** [comment]
@awoie or anyone else.. Any interest in contributing a few sentences about topics such as private key security, entropy, hardware security, FIDO attestations? Based on your comment here I thought you may have some ideas: https://github.com/w3c/did-core/issues/151#issuecomment-577619416

Otherwise, we will close this issue soon.

**Comment by peacekeeper** [comment]
https://github.com/w3c/did-core/pull/568 addresses this.

**Comment by msporny** [comment]
PR #568 has been merged, closing.
