### ISSUE TITLE
Abstract data model is not secure

### ISSUE THREAD

**Issue by OR13** [w3c/did-core#398]
It's not clear what types it can represent, which then prevents us from understanding what representations it can support.

Given that its "abstract", I assume given enough effort from the community it could eventually be as expressive as Haskell / INFRA... and that in theory... the abstract data model can represent any type....

In practice, I find handwaving about type support to be unhelpful for our working group and the spec.

Here are a couple of options:

### Abstract Data Model Type System

1. Define the Abstract Data Model as JSON
2. Define the Abstract Data Model with JSON Schema (JSON Types + specific structure for them in JSON)
3. Define the Abstract Data Model as CBOR
4. Define the Abstract Data Model as INFRA (sorta what we are doing, but its IMO more confusing than it is helpful... we still don't know how to support numbers....).

Assuming we have strong consensus on the ADM type system... we still need to define how it supports known and unknown properties (but now we don't have to worry about types!)....

IMO, the abstract data model MUST preserve all properties.

If a producer wants to drop properties, they should do that as part of their production process.... it should NOT be a side effect of "the abstract data model doesn't have that property defined".

The reason for this is meeting the expectations of JSON developers, and keeping the abstract data model rules simple and easy to understand, and keeping the responsibility for what is produced in the hands of the did method author who is ultimately responsible for the security implications of preserving or dropping properties (data sanitization is out of scope for did core).

The proposed changes would not prevent a did method author from dropping properties from a representation.... in fact, they make it clear that the DID Method is the only place that gets to decide about the properties in the abstract data model.

As far as I know, the only exception to this is the mandatory presence of the the `id` property in all did documents.

Here are some scenarios to consider:

1. A DID Method produces JSON that is valid JSON-LD, and no properties are dropped going back and forth between any JSON based representation.

2. A DID Method produces JSON that is not valid JSON-LD but contains an `@context`, some software guesses about the properties using the spec registries, and the rest of the "unknown" properties are dropped (only when consumed as JSON-LD, not when consumed as JSON).

3. A DID Method produces JSON that is not valid JSON-LD AND does not contain an `@context`, some software guesses about the properties using the spec registries, and the rest of the "unknown" properties are dropped (only when consumed as JSON-LD, no properties are dropped when consumed as JSON).

2 and 3 are not the same... 

- 2 uses JSON and JSON-LD, 100% of the JSON is preserved, and 90% of the JSON-LD is preserved (stuff in the registries, and stuff in the other contexts).
- 3 uses JSON and JSON-LD, 100% of the JSON is preserved, and 50% of the JSON-LD is preserved (only stuff in the registries).

This is what I would call expected behavior, as a JSON and JSON-LD Developer.

Its made possible by realizing that JSON-LD developers consider `@context` to be a property of a JSON document... which should be preserved.... removing this property is like removing the "manufacturer tag" from a part of clothing before the consumer buys it... its an attack of the integrity of the original JSON Document.

The Abstract Data Model cannot require that the integrity or representations be harmed as they move in and out of it.

What JSON-LD does WHEN properties are removed is a similar attack.... however, it does not occur in the same place.

It occurs ONLY on the consumer side... this is like when you buy a product and remove that tag... its ok, because its yours.

The abstract data model does not own representations, it should not attack them... it should facilitate their interoperability... the best way to preserve interoperability is to NOT DELETE THINGS, and instead IGNORE THEM.... thats the entire mantra of JSON extensibility.

If the abstract data model starts requiring that properties be dropped, it raises further questions about security... like... should the abstract data model drop properties that might be used to attack a specific language, `<script>`, `INSERT`, `__prototype__`.... data sanitization is not the job of this WG.... its the job of DID Method Authors.... 

We must clearly communicate this to them, or we are handing them a loaded gun, with the safety of.

But security in depth requires us to consider that producers / consumers will be handed malicious did document representations / abstract data models.

Here is where we can be clearer.

Since data sanitization cannot be applied to an abstract data model, the first step is to make a concrete representation. For JSON and JSON-LD, this means string serialization.

The next step, MUST be implemented in consumer software, the representation should be validated by the consumer... depending on the language, that might involve checking for structures that could lead to arbitrary code execution...

Unless DID Core intends to fully document the process the consumer will take to obtain a "safe" representation from a producer... we have a problem here.

Security best practices dictate that the DID Core spec warn implementers that producers/consumers WILL be attacked with malicious representations, and that implementers apply data sanitization procedures to protect their software from compromise. 

Link to https://cheatsheetseries.owasp.org/cheatsheets/Input_Validation_Cheat_Sheet.html

...and critically, we cannot say anything else... this group lacks the security expertise to provide additional guidance in this area.... JSON Schema / JSON-LD.... magical normative `deny-list` statements.... all are not a solution to this problem... we should not even hint that they are.... its a serious mistake to give implementers a false sense of confidence regarding the "safety" of representations.

The good news is that this is actually much simpler than what we have today, it better matches what JSON developers expect (they are used to being told to not trust user input), and best of all, it demonstrates that this WG takes security very seriously.

Since this is long, and potentially confusing, I will recap some of the potentially devise points.

1. JSON DID Documents MUST contain an `id` and MAY contain arbitrary unknown properties that MUST be preserved.
2. JSON and JSON-LD Representation processing happen AFTER JSON serialization  (meaning ANY representation can decide to sanitize ANY properties from the abstract data model, including `@context` / unknown properties).
3. All producers / consumers MUST be warned that consuming un-sanitized inputs can result in arbitrary code execution.

**Comment by jonnycrunch** [comment]
@OR13 This was very helpful and put last week's call into perspective.

**Comment by jonnycrunch** [comment]
After reading this again, I'm still in favor of CDDL for the Data Definition representation aspects of the ADM.    I think that the CDDL will help protect from malicious representations.

**Comment by msporny** [comment]
-1 to switching to CDDL at this point. We have a spec that is implementable now using INFRA... and we're only missing two core types for INFRA (Datetimes and Numbers, both of which are easy to add).

Let's see where the group lands tomorrow wrt. the Abstract Data Model and then see what we can do with this issue.

Without a concrete set of PRs for this issue, it will either be closed before CR or deferred to another version.

**Comment by OR13** [comment]
Im strongly in favor of switching to CDDL, I fear it if we don't we won't ever be able to define the ADM in a way that gathers consensus... which will hamstring all representations.

**Comment by msporny** [comment]
> Im strongly in favor of switching to CDDL, I fear it if we don't we won't ever be able to define the ADM in a way that gathers consensus... which will hamstring all representations.

What does "switching to CDDL" mean?

**Comment by OR13** [comment]
I hope it means using CDDL to define the ADM in did core... because right now, I think we are handwaving at INFRA, and it's leading to no shared understanding about how the ADM actually works.

> In computer science, an abstract data type (ADT) is a mathematical model for data types. An abstract data type is defined by its behavior (semantics) from the point of view of a user, of the data, specifically in terms of possible values, possible operations on data of this type, and the behavior of these operations.

currently, the production / consumption rules are incomprehensible due to a lack of clearly defined ADM... for example, its not clear how to support new representations at all, and the domain of types and their expression for those new representations is not defined in did core... similarly, `resolveRepresentation` which ostensibly relies on `accept` and some representations production rules is not defined in a way that eliminates the ambiguity at the heart of the ADM.

My feeling is that one solution to this, is to stop trying to be "vague" and start using CDDL to define exactly what we mean.

**Comment by peacekeeper** [comment]
I also support adding CDDL to DID Core to define the Core Properties in the ADM (minus the open question if representation-specific things like `@context` belong there or not).

**Comment by msporny** [comment]
As soon as concrete Vanilla CBOR/JSON/JSON-LD CDDL definitions are in wrt. DID Spec Registries, this can be closed as resolved.

**Comment by OR13** [comment]
This is done IMO, I'm closing since we have CDDL in the registries and better language regarding production / consumption in did core.
