### ISSUE TITLE
Incompatibilities in the fragment definitions

### ISSUE THREAD

**Issue by iherman** [w3c/did-core#400]
If, as said in #399, the resource whose fragment ID is to be taken into account, is a DID document, then the spec should say what that means. Per the current spec, the media type is `application/did+json`, `application/did+ld+json`, or `application/did+cbor`. The meaning of the fragment id is defined as follows:

1. [§B1 `application/did+json`](https://w3c.github.io/did-core/#application-did-json) as well as for [§B3 `application/did+cbor`](https://w3c.github.io/did-core/#application-did-cbor) the spec says "treated according to the rules defined in [DID Core v1.0, Fragment](https://w3c.github.io/did-core/#fragment)", which is §3.2.4. That section is a bit vague as for what exactly this means: "identify a component of the document" 
2. [§B2 `application/did+ld+json`](https://w3c.github.io/did-core/#application-did-ld-json)  says "treated according to the rules associated with the JSON-LD 1.1: application/ld+json media type". Following the reference chain §B.2->[JSON-LD](https://www.w3.org/TR/json-ld11/#iana-considerations)->[RDF 1.1](https://www.w3.org/TR/rdf11-concepts/#section-fragID) we get to the RDF specification essentially says: 

    > In RDF-bearing representations of a primary resource `<foo>`, the secondary resource identified by a fragment bar is the resource denoted by the full IRI `<foo#bar>` in the RDF graph. Since IRIs in RDF graphs can denote anything, this can be something external to the representation, or even external to the web.

    I.e., to paraphrase, in RDF, a URI with a fragment ID can mean _anything_, ie, a resource which may have no connection to the resource of the base URL. This is _not what §3.2.4 says in DID Core_, namely: "A DID fragment is used as method-independent reference _into the DID document_ to identify a component of the document" (emphasis is mine).

I.e., we do have a not-too-subtle difference between the JSON-LD and the JSON representations in this case.

**Comment by OR13** [comment]
IMO, the service endpoint use case means that the 1st section is not correct.... consider:

`did:example:123?service=agent&relativeRef=/credential-manifest#citizenship-credential`

I think in pure JSON, we want this ^ to identify a resource that is NOT in the did document.

**Comment by msporny** [comment]
What is the status of this issue, @OR13 ?

**Comment by OR13** [comment]
@msporny I think I resolved it, but would like @iherman to confirm.

**Comment by iherman** [comment]
> @msporny I think I resolved it, but would like @iherman to confirm.

I do:-) 

As far as I am concerned, this can be closed.

**Comment by msporny** [comment]
Thanks @iherman -- marking as pending close.

This issue will be closed in 7 days if there are no objections raised.

**Comment by brentzundel** [comment]
No comments since marked pending close, closing
