### ISSUE TITLE
DID Core editorial review (1)

### ISSUE THREAD

**Issue by iherman** [w3c/did-core#401]
I spent some time today on thoroughly re-reading the core spec. I did not complete the whole document, only up to §5.3.1, but I thought I would dump my issues here, and continue on another day with the rest.

There are lots of mini issues, and many (most?) of them are minor editorial issues. Some are more complex, but still editorial I believe.

## Abstract

* [x] "DIDs are URLs": Strictly speaking, they are not. They are URI-s and there is a thing called DID URL… This is only an abstract, but it should still be precise…
* [x] "A DID document might contain the DID subject itself (e.g. a data model).": I do not understand this statement. The DID subject is defined as: _"The entity identified by a DID and described by a DID document. A DID has exactly one DID subject. Anything can be a DID subject: person, group, organization, physical thing, digital thing, logical thing, etc."_ But the document cannot contain a person…

## Introduction

* [ ] Just a food for thought: wouldn't it be a better style to use a neutral form in this section? I.e., "Because the user controls" instead of "Because we control", for example?
* [x] "This specification does not require any particular technology or cryptography to underpin the generation, persistence, resolution or interpretation of DIDs." I am not sure this is well formulated. The _specification_ does not require, but implementations _do_ require a bunch of particular technologies. I think the intention here is to say something like "This specification does not _depend_ on any particular technology…"
* [x] "(e.g., blockchain, distributed ledger, ...)": isn't blockchain a specific form of distributed ledger? In this context I would propose to remove the reference to blockchain, as too specific.
  
## 1.2 Design Goals (Table)

* [x] Introductory paragraph: the second sentence sounds like repeating the essence of the first one, with the repeated term "design goals for this specification".
* [ ] **Decentralization**, "Eliminate the requirement for centralized authorities or single point failure in identifier management...": playing possible opponent here I could say that the _specification_ of, say, the HTTP URL scheme does not _require_ the existence of a DNS either and, similarly, the _specification_ of a DID does not _eliminate_ this. I think it is better to say that the definition of DID-s "makes it possible" or "makes it easier" (or something like that) to be implemented without the requirement of central authorities.
* [ ] **Interoperability** and **Portability**: both of these statements are, though true, a bit too obvious for my taste. These statements are true for all Standards, W3C or otherwise. (I would think just removing these two would be fine.)
* [ ] **Simplicity**: this again is some sort of a generic, feel-good statement. Let alone the fact that simplicity is a matter of personal opinion, and others may not agree that DIDs are simple...
  
## 1.3 Architectural overview

* [x] DID Controllers, "and the controller(s) may include the DID subject.": it took me a while to understand what is meant here. Maybe it is better to be a bit more explicit: "and the DID subject may be a controller, too"
* [x] DID documents, "A DID document is serialized according to a particular syntax (see § 6. Core Representations)." while that is true, it may be better to emphasize that a DID document represents a precise data model _and_ can be expressed via different syntaxes. B.t.w., the sentence right after this refers to the `id` property, but the term "property" is not defined in this terminology but only in the data model, so it is not 100% clear at this point what it means... Maybe it is better to swap that sentence with the sentence right after it ('The generic properties supported...')
* [x] Note after methods: "namespace definition," : the comma seems to be superfluous.

## 2 Terminology

* [ ] **decentralized identifier (DID)**, "The generic format of a DID is defined in the DID Core specification.": this sentence does look a bit strange when referring to the specification whose terminology one is reading...
* [x] **decentralized public key infrastructure (DPKI)**, "DID documents)": superfluous ')' character
* [x] **DID URL**: just for consistency, I think the fragment "(and its leading '/' character)" should be added after the term DID path
* [x] **DID URL Dereferencing**, "it use the DID resolution function to fetch": "use" -> "uses"
* [ ] **distributed ledger (DLT)**: this is a technical question and I may be wrong: isn't a DLT immutable, ie, "nodes" cannot change? If so, worth emphasizing for laypeople.
* [ ] **representation**: same comment as before: referring to the "DID Core specification" as it was an external document does read very strange
  
## 3.1 DID syntax

* [ ] shouldn't the ABNF syntax for `method-char` say `%x61-%x7A`? (The second `%x` is missing in the text)

## 3.2.1. DID Parameters

* [x] Section right after Example 4: I find it a bit strange that somehow, out of the blue, the input metadata for a DID resolver are discussed here. The section begins by "The DID URL syntax supports a simple format for parameters based on the query component", setting the tone of the section, and we are suddenly talking about something else. I think there should be a totally separate paragraph, possibly subsection, that talks about DID resolver metadata.

## 5.1 DID Subject

* [ ] The property `id` is presented in the section as _the_ property to designate the subject. However, the same property is also used elsewhere and referred to in, say, the §5.3 on verification method. Very formally, the `id` property in that position is not really well defined but, mostly, it has a very very different _role_ as at the top level.

    I wonder whether we should not have a _separate_ `subject` property for, well, the subject, usable on the top level only. That would clearly separate the semantics. For the hard-core JSON-LD usage the `subject` property can be aliased to `@id` (just as `id` is) in the `@context`, ie, it would not mean a significant semantic change.

## 5.3 Verification Methods

* [x] paragraph after example 11, "(see § 5.4 Verification Relationships.": missing closing parenthesis.
* [ ] algorithmic steps (1)-(4) between example 11 and example 12: the abstract data model follows the INFRA terminology; I believe that the algorithms should follow it, too. Meaning that the value is not an "object" but a "map"; usage, when applicable the notation of INFRA like `a -> b`, etc. (A good example of a structurally similar (but much more complicated) algorithm edited this way may be in the [Publication manifest spec](https://www.w3.org/TR/pub-manifest/#manifest-processing).) Obviously, this comment is a generic one for the document as a whole.
* [ ] Example 12: The example uses the `publicKeyBase58` property. This is not a core property defined by this specification but, rather, a registered property in our separate document. This fact should be made clear for the user somewhere and, actually, I would consider using a typographic difference in _all_ the examples (e.g., different colors) to separate the core properties from the separately registered one. It would greatly improve the readability of the examples. (This is, obviously, a comment for _all_ examples.)
    
    The current way of presenting examples becomes problematic for larger examples, see, e.g., [Example 13](https://w3c.github.io/did-core/#example-13-various-public-keys) where there is a proliferation of various property names and it becomes confusing as for where the various properties are defined, which are standards, etc.

## 5.3.1. Key types and formats

* [ ] Introductory paragraph, "The specific types of key formats that are supported in this specification are listed here.": what does "supported" means in this context? (The properties themselves are defined elsewhere and registered separately.) This needs clarification.

To be continued…

**Comment by rhiaro** [comment]
> The generic format of a DID is defined in the DID Core specification.": this sentence does look a bit strange when referring to the specification whose terminology one is reading...

Evergreen problem. The terms file gets pulled into other documents, like the use cases, where saying "defined in this specification" doesn't make sense. Not sure what the best approach is. Possibly when external documents get frozen this issue will go away and we can rephrase this in DID Core.

> I wonder whether we should not have a separate subject property

If you haven't already, I suspect you might want to spin this out into a separate issue..

> typographic difference in all the examples (e.g., different colors) to separate the core properties from the separately registered one

Agreed. I think in the case of `publicKeyBase58` though this is expected to go into Core at some point.. though I will need to double check. I actually think that in the end we shouldn't have any non-Core properties in examples when everything is cleaned up.

Otherwise, I agree with this editorial feedback, and can put in a PR for most of it. A couple of things I think I'd want to run by others, but perhaps a PR is the place to do that anyway.

**Comment by iherman** [comment]
>>I wonder whether we should not have a separate subject property
>
> If you haven't already, I suspect you might want to spin this out into a separate issue..

Yes, this is now out in the open :-)

> Agreed. I think in the case of publicKeyBase58 though this is expected to go into Core at some point.. though I will need to double check. I actually think that in the end we shouldn't have any non-Core properties in examples when everything is cleaned up.

Exactly. We should not add non-Core properties, or make it clear when they are. A special case may be the JWK structures, where the terms may be defined elsewhere (where? Reference?)

**Comment by rhiaro** [comment]
> Just a food for thought: wouldn't it be a better style to use a neutral form in this section? I.e., "Because the user controls" instead of "Because we control", for example?

I had a go at rewording to use passive language but it became increasingly dry and awkward, especially when trying to avoid terms that have been contentious in the past like "user" and "entity".

> the HTTP URL scheme does not require the existence of a DNS either and, similarly, the specification of a DID does not eliminate this

Struggling with this a bit because these are "goals" rather than stated as results. The DID infrastructure does not eliminate *the existence* of central authorities, but may eliminate the *requirement for* them? Leaving the design goals alone for now. I'm not sure I'd want to remove any either as the statement that they are important - eg. cannot be compromised on - even if they're obvious, seems useful, especially as some of them can be at odds with each other and it's always a balance.

> distributed ledger (DLT): this is a technical question and I may be wrong: isn't a DLT immutable, ie, "nodes" cannot change? If so, worth emphasizing for laypeople.

Deferring to someone else - maybe a new issue to improve the definition?

>  shouldn't the ABNF syntax for method-char say %x61-%x7A? (The second %x is missing in the text)

I don't think so... the `%x` only needs to be at the start of that statement for lowercase ascii letters.

> "The specific types of key formats that are supported in this specification are listed here.": what does "supported" means in this context?

I thiiiink it means the ones that are explicitly restricted in some way by this specification. *If* you use these, you *MUST* use them in this way. But I'd like confirmation from someone else before changing anything there.

Meanwhile, most other points covered in PR https://github.com/w3c/did-core/pull/414

**Comment by iherman** [comment]
I have ticked off the items that are covered by #414

**Comment by msporny** [comment]
Closing based on request by @iherman since many changes have been made based on this issue and another re-read will be required at this point to see if the original unresolved issues remain.
