### ISSUE TITLE
Is this a misspelling? 32 vs. 33 bit for publicKeyBase58

### ISSUE THREAD

**Issue by iherman** [w3c/did-core#405]
(This may reflect my ignorance in crypto...)

The [Table on key types](https://www.w3.org/TR/did-core/#key-types-and-formats) includes a reference to the `publicKeyBase58` key. The text always says:

> be encoded as the raw 32-byte public key value encoded in Base58 Bitcoin format [BASE58] using the publicKeyBase58 property

_except_ for `secp256k1-koblitz` where it refers to 33-byte instead of 32. Is that intentional?

Also, while I am at it: the example below the table includes an example referring to the `JwsVerificationKey2020` class. This class is not defined in the table. Either define it as an official core class, or remove it from the example.

**Comment by OR13** [comment]
`JwsVerificationKey2020` is a VM type... it is in the did spec registries as `JsonWebKey2020` I will correct the type.

IMO, almost all of the key representation stuff in did core should be removed, did method authors can represent keys however they want.... we created the did spec registries to show them how to have representations that are interoperable.

**Comment by OR13** [comment]
33 is not a typo here is an example:

```
 {
          "id": "#zQ3shptjE6JwdkeKN4fcpnYQY3m9Cet3NiHdAfpvSUZBFoKBj",
          "type": "EcdsaSecp256k1VerificationKey2019",
          "controller": "did:key:zQ3shptjE6JwdkeKN4fcpnYQY3m9Cet3NiHdAfpvSUZBFoKBj",
          "publicKeyBase58": "24waDFAUAS16UpZwQQTXVEAmm17rQRjadjuAeBDW8aqL1"
        }
```

**Comment by iherman** [comment]
Ok, so 33 bits is o.k. Thanks for checking

**Comment by iherman** [comment]
> IMO, almost all of the key representation stuff in did core should be removed, did method authors can represent keys however they want.... we created the did spec registries to show them how to have representations that are interoperable.

That is an altogether different question and is one of the questions I asked in https://github.com/w3c/did-core/issues/403 on §5.3.1. To avoid confusion, and based on https://github.com/w3c/did-core/issues/405#issuecomment-695802241 I propose to close this issue.

**Comment by brentzundel** [comment]
No comments since marked pending close, closing.

**Comment by zamicol** [comment]
I'm looking for a definition of DID/multibase key types, and the [link above appears dead](https://www.w3.org/TR/did-core/#key-types-and-formats).  Is there someplace where the public key formats are defined?  Or is it assumes that all primitives will adequately describe a public key serialization format so only encoding is a concern?

**Comment by seabass-labrax** [comment]
Multibase is was originally developed on GitHub at <https://github.com/multiformats/multibase>. The recent standardisation efforts in the IETF can be found at <https://datatracker.ietf.org/doc/draft-multiformats-multibase/>; these are at the draft stage currently.

**Comment by msporny** [comment]
@zamicol wrote:
> I'm looking for a definition of DID/multibase key types, and the [link above appears dead](https://www.w3.org/TR/did-core/#key-types-and-formats). Is there someplace where the public key formats are defined? Or is it assumed that all primitives will adequately describe a public key serialization format so only encoding is a concern?

The latter, all primitives will adequately describe a public key serialization so only multibase encoding is a concern. That said, here's the precise definition for an Ed25519 public key:

https://www.w3.org/TR/vc-di-eddsa/#multikey

and ECDSA keys:

https://www.w3.org/TR/vc-di-ecdsa/#multikey

If you need to encode other key formats, you can find their headers in the multicodec table here (by searching for "key"):

https://github.com/multiformats/multicodec/blob/master/table.csv

Hope that answers your question, let us know if it doesn't.

**Comment by zamicol** [comment]
@msporny Yes, that's exactly it.  Thank you.
