### ISSUE TITLE
Ordered set of links for controllers?

### ISSUE THREAD

**Issue by iherman** [w3c/did-core#411]
There is a difference between the way controllers and `alsoKnownAs` values are defined:

> The value of the controller property MUST be a string or an ordered set of strings 

as opposed to

> The value of alsoKnownAs MUST be a list where each item in the list is a URI conforming to [RFC3986]

Two issues there:

1. Why are the values of a controller property _ordered_? What does the order mean (there is no word of it in the spec)?
2. The two properties are very much alike (although the semantics are different), meaning that it would be worth harmonizing their definition. E.g., at present a single string is not valid for `alsoKnownAs` whereas it is for `controller`...

**Comment by rhiaro** [comment]
1. My understanding is that all of the list-y data structures in INFRA are ordered, but for our cases the fact that it is ordered doesn't matter. [INFRA says](https://infra.spec.whatwg.org/#ordered-set):

> NOTE: Almost all cases on the web platform require an *ordered* set, instead of an unordered one, since interoperability requires that any developer-exposed enumeration of the set’s contents be consistent between browsers. In those cases where order is not important, we still use ordered sets; implementations can optimize based on the fact that the order is not observable.

2. Agreed we should have consistency with whether things are always lists even when there's only one or can sometimes be a single item. Mostly I think this is a preference.. when I'm processing JSON I prefer to know I can treat everything as a list without having to check, but others may not agree. Probably something to do a WG vote on and then clean up all relevant properties.

**Comment by iherman** [comment]
@rhiaro 

That is a Note. https://infra.spec.whatwg.org/#lists talks about 'lists' but with the definition:

> A list is a specification type consisting of a finite ordered sequence of items.

There is no mention of ordering. Then it says

> Some lists are designated as ordered sets.

in [§5.1.3](https://infra.spec.whatwg.org/#ordered-set). It is a bit messy, but my interpretation is that a 'list', by default, is not ordered (in contrast to the usual meaning of the term) and has to be designated explicitly as an ordered set.

But that is a detail, we have to specifiy whether we want ordered or not ordered. Note, however, that if the controller is considered as _ordered_ then the modeling in RDF should be done via an RDF List, and the `@context` file should include the necessary directive to make it clear that the value is a list. We should do that only if this is really necessary, and I do not see why it would be...

**Comment by rhiaro** [comment]
> A list is a specification type consisting of a finite *ordered* sequence of items.

My reading of that is that lists are ordered. The difference between an INFRA list and an INFRA ordered set is that the latter cannot contain duplicates. But that they are the same with regards to ordering.

I don't think any of the DID Core properties need ordering. I don't think using INFRA definitions which include potentially non-deterministic ordering hurts, or affect any of the supported representations in DID Core.

**Comment by iherman** [comment]
Yeah, maybe you are right per ordered set. But then _our_ specification should make it clear that ordering does _not_ count (it does now).

**Comment by rhiaro** [comment]
I think this was addressed by https://github.com/w3c/did-core/commit/58225f14c334c97e54e71c4a2b457db7509b5806 - okay to close @iherman ?

**Comment by brentzundel** [comment]
Labelled `pending close` for over 7 days. No status change. Closing.
