### ISSUE TITLE
Add NOTE about Verification Method types and remove the redundant languages on key representations from DID Core

### ISSUE THREAD

**Issue by OR13** [w3c/did-core#423]
https://github.com/w3c/did-core/pull/406#discussion_r498455863

I think we are wasting our time defining the same thing with slight differences 4 or 5 times in difference places.

We have the ADM, it defines supported key types (actually it doesn't but I am assuming it will, possibly by using the `type` property value.).

We have the did spec registries, it defines supported key types for all supported representations, in some cases it also links to the definitions elsewhere.

We have the linked data signature suites, like `Ed25519Signature2018` and `JsonWebSignature2020` which define the verification method types, like : `Ed25519VerificationKey2018` and `JsonWebKey2020`.

Regardless of opinions on JWK vs not JWK....

We really ought not to need to define "all supported key types" in did core and did spec registries.... We should be able to say something like:

"Verification Methods are responsible for defining what key representations and proof formats are supported, for example:
P-256 JWK supports ES256, and `Ed25519VerificationKey2018` supports `Ed25519Signature2018`."

"DID Core defines support for a few verification methods, and additional methods may be found in the did spec registries."

Then list the Verification Method types that DID Core Supports ( without any extensions )...

Then delete the entire section about verification method types, but leave the details about required properties such as `id`, `type`, `controller`, `publicKeyBase58` and `publicKeyJwk`...

**Comment by OR13** [comment]
We also want to be able to explain support for `secp256r1` aka P-256 and the other curves listed here:

https://www.iana.org/assignments/jose/jose.xhtml#web-key-elliptic-curve

I personally don't think its wise for us to repeat a version of this table in DID Core, and instead I advocate for relying on the Linked Data Suite to define the supported crypto and note that JsonWebSignature2020 was created to resolve this exact issue... If you don't want agility, don't use it :)

**Comment by msporny** [comment]
Agree on the proposal, this issue will need to result in a PR in the next 30 days or the spec text will remain as it is right now.

**Comment by msporny** [comment]
This issue is related to issue #240 and will be closed when there is a PR for that issue (or this issue).

**Comment by msporny** [comment]
Issue #240 was closed via PR #490, which removed redundant language regarding key representations from DID Core and has been merged. Closing.
