### ISSUE TITLE
DID Test Suite and untestable normative statements

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#44]
@kimdhamilton moved from CCG (https://github.com/w3c-ccg/did-spec/issues/228)

**Comment by msporny** [comment]
I believe PR w3c-ccg/did-spec#210 addressed this issue. @rhiaro and @aljones15 can you please confirm?

**Comment by rhiaro** [comment]
I think so, best effort for the time being at least.

**Comment by msporny** [comment]
This has now been resolved, closing in 7 days.

**Comment by aljones15** [comment]
This looks fine and the first release of the test suite is in master. So good work and thanks.
