### ISSUE TITLE
Differentiate external properties in examples

### ISSUE THREAD

**Issue by rhiaro** [w3c/did-core#447]
Suggested by @iherman in #401 and #403 - some examples necessarily use properties or types that aren't part of DID Core. It would be helpful to differentiate these, using different typography or to make a list in a note somewhere for avoidance of doubt by anyone new to the spec. For terms that aren't just made up examples, links to where they are defined should be provided.

I'll do this, later when the examples and Core term definitions are more stable.

**Comment by msporny** [comment]
PR #562 addresses this issue. This issue will be closed once PR #562 has been merged.
