### ISSUE TITLE
Compound key is not clear and points to wikipedia not a normative definition

### ISSUE THREAD

**Issue by jonnycrunch** [w3c/did-core#452]
In an attempt at solidifying concrete representations of key formats I found that `compound key` description of the `id` property in the [Verification Methods](https://www.w3.org/TR/did-core/#verification-methods) section lacking in substance.  In points to [Composite_key](  https://en.wikipedia.org/wiki/Composite_key) on wikipedia.  I need something more explicit and unambiguous to complete the CDDL representations and I find the current MAY, MUST, RECOMMENDED insufficient to implement the representations in CDDL.  

The text currently states MUST be URI, but seems that this really should be a MUST be a [DID-URL](https://www.w3.org/TR/did-core/#dfn-did-urls)

**Comment by OR13** [comment]
agree, perhaps we should just say a DID URL with a fragment.

**Comment by OR13** [comment]
by compound key, we mean: "did:example:123#kid` per https://tools.ietf.org/html/rfc7638

**Comment by jonnycrunch** [comment]
@OR13, yes In general that is what belong on the right-hand side of the `#`, but the concept of string concatenation of `did:example:123` with '#` and the fingerprint with what need to be normatively capture for the abstract data model.  


here is what I think would be the best `rule`:

https://tools.ietf.org/html/rfc5234#section-3.1


and for representation specific implementations in CDDL: 

https://tools.ietf.org/id/draft-bormann-cbor-cddl-control-02.html#section-2.1

**Comment by OR13** [comment]
Really, we are saying that `id` is an IRI that can contain a fragment, where the fragment is determined according to another RFC, I welcome any PRs that better express this.

**Comment by msporny** [comment]
PR #571 addresses this issue, which will be closed when that PR is merged.

**Comment by msporny** [comment]
PR #571 has been merged, closing.
