### ISSUE TITLE
Data Model and Representations "Value and Lexical Space"

### ISSUE THREAD

**Issue by OR13** [w3c/did-core#456]
Prefer to see clear explanation of how the data model is:

"Value Space / Abstract"

representations are:

"Lexical Space / Testable", CDDL is useful at this level... constrained to mime-types.

I think we need some helpful informative statements regarding the relationship between these concepts, to avoid confusion.

**Comment by OR13** [comment]
I plan on trying to add a comment to this effect once the changes have been merged, no need to obstruct the current PRs.

**Comment by peacekeeper** [comment]
While exploring this in https://github.com/w3c/did-spec-registries/pull/136#issuecomment-697961819 and subsequent comments, we thought we could say that:

- we use the value space of XML Schema data types such as https://www.w3.org/TR/xmlschema-2/#dateTime in our abstract data model (PR https://github.com/w3c/did-core/pull/455 accomplishes this).
- we recommend that representations SHOULD use the lexical representation of those same XML Schema data types (e.g. JSON-LD does this), but representation MAY also choose to represent the data types differently (e.g. CBOR-LD would do this).

**Comment by msporny** [comment]
This issue will be closed once PR #486 is merged.

**Comment by msporny** [comment]
PR #486 has been merged, closing.
