### ISSUE TITLE
It would be useful to have `services` as a mapping instead of an `array`

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#46]
@aaitor moved from CCG (https://github.com/w3c-ccg/did-spec/issues/224)

**Comment by dlongley** [comment]
Part of this will depend on https://github.com/w3c/did-spec/issues/47 -- whether or not IDs are required, so we must wait on a decision over there. While it would be useful to have `services` be a mapping, I suspect we want to support services that do not require identifiers.

**Comment by dlongley** [comment]
As #47 was merged, we should close this.
