### ISSUE TITLE
DID Core must define how to compute the digest to secure did spec registry entries contexts

### ISSUE THREAD

**Issue by OR13** [w3c/did-core#464]
https://github.com/w3c/did-spec-registries/pull/146

This is pretty straightforward,  we need to explain how you use curl + SHA-256, to get a hash, and compare it with an expected value.

If we don't do this, folks will be registering multihashes, MD5, Blake2b, etc... and its won't be useful at all...

this is an option:

```
curl -s https://www.w3.org/ns/did/v1  | openssl sha256
```

**Comment by msporny** [comment]
This feels like a reasonable way to provide guidance for how developers should generate a hash.

**Comment by msporny** [comment]
This issue will be closed once #485 is merged.

**Comment by msporny** [comment]
PR #485 has been merged, closing.
