### ISSUE TITLE
How should contributors register the same DID Method on multiple networks?

### ISSUE THREAD

**Issue by OR13** [w3c/did-core#478]
Some related conversation in the sidetree / ethereum ecosystem: https://github.com/decentralized-identity/element/issues/207

There has been discussion in the Indy community regarding best practices for this.

We should provide guidance in DID Method Registry regarding this.

**Comment by peacekeeper** [comment]
I believe that most implementers are now favoring a design that doesn't consider multiple instances of the same technology/network to be different DID methods, but actually use a single DID method with multiple colons in the method-specific-id (as described in https://github.com/w3c/did-core/pull/387).

So I think we should close this. But @talltree should also comment.

**Comment by OR13** [comment]
Agree this should be closed.

**Comment by OR13** [comment]
There is not action on this issue, its assigned to me, I am marking it pending close, since its a question asked and answered.

**Comment by msporny** [comment]
It has been 8 days since this issue was marked pending close... there have been no objections, closing.
