### ISSUE TITLE
Provide better service.type examples

### ISSUE THREAD

**Issue by OR13** [w3c/did-core#479]
we talk about service types, but we don't have a good list of examples, and we have not registered any service types in the did spec registries.

Some hypothetical service types we might want to add:

- DIDComm
- LinkedDomains
- GS1Resolver
- EncryptedDataVault
- ConfidentialStore

**Comment by OR13** [comment]
per your request @jandrieu 

ping @philarcher @csuwildcat

**Comment by ChristopherA** [comment]
I see that list and can’t help but wonder how many of them would be better served by a VC offering signed by that DID “this is my EncryptedDataVault”.

I can see having one service that the controller uses to negotiate with a holder that wants more info, but I don’t like all those endpoints being public in the DID document.

**Comment by OR13** [comment]
yes, this has been discussed extensively... many of them belong in VCs and not in the did doc imo.

**Comment by agropper** [comment]
There needs to be some authorization demarcation point in the DID document.
VCs alone don't do that because of privacy and herd immunity
considerations.

**Comment by OR13** [comment]
Of the list only `LinkedDomains` has a compatible defintion IMO

**Comment by msporny** [comment]
The `LinkedDomains` example has been merged. Can we close this @OR13, or were you expecting more changes to be made to the specification based on this issue?

**Comment by msporny** [comment]
Marked this issue as pending close. The issue will be closed in 7 days if there are no objections.

**Comment by msporny** [comment]
No objections to closing this issue. Closing.
