### ISSUE TITLE
Section 6.3.3.1 DAG CBOR spec link

### ISSUE THREAD

**Issue by manicprogrammer** [w3c/did-core#481]
Part 6.3.3.1 addresses DAG-CBOR but there is no link to the specification. What is the link to the DAG-CBOR specification?
A quick google search returns this for me but I can't know if that is the definitive source or even the proper source for this document.
https://github.com/ipld/specs/blob/master/block-layer/codecs/dag-cbor.md

**Comment by jonnycrunch** [comment]
DagCBOR extends "vanilla CBOR" with tag 42 in IANA.  See: https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml.

**Comment by manicprogrammer** [comment]
Thank you. Closing as answered.
