### ISSUE TITLE
If an existing DID Document has a Service Endpoint fragment, what are the primary keys to be used if that Service Endpoint needs to be replaced, updated, or deleted?

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#49]
@mwherman2000 moved from CCG (https://github.com/w3c-ccg/did-spec/issues/268)

**Comment by ChristopherA** [comment]
@rwherman2000 wrote:
> If an existing DID Document has a Service Endpoint fragment, what are the primary keys to be used if the Service Endpoint (or elements of the Service Endpoint) need to be replaced, updated, or deleted?

This issue is out-of-scope — it is specific to the service endpoint, and there will be many different service endpoints types, each with different requirements. It would need to be specified in the Service Endpoint spec.

-- Christopher Allen

**Comment by ewelton** [comment]
just a quick question here, i'd like to understand the Service Endpoint spec a bit more deeply.  What is the best place to go for information about the current and historical thinking on how service endpoints are to be handled?

**Comment by msporny** [comment]
> What is the best place to go for information about the current and historical thinking on how service endpoints are to be handled?

It's tribal knowledge, yet to be documented, the only stuff that really exists are buried in call logs long ago and in the current spec. It's a terrible answer, but that's where we are today. There is also no "Service Endpoint spec" -- people haven't documented service endpoints yet. Digital Bazaar hopes to document at least one (for a GDPR compliant verifiable credential publication endpoint) before the DID WG closes.
