### ISSUE TITLE
DID method name should be ASCII alphanumeric in lowercase

### ISSUE THREAD

**Issue by shigeya** [w3c/did-core#491]
In the DID Syntax description, the ABNF definition describes that `method-char` may include digits.
But the text prior to the ABNF refers to INFRA's ASCII lowercase string.

Unfortunately, INFRA currently does not have the definition for ASCII lower alphanumeric yet.
So the (incoming) proposed fix refers to ASCII lower alpha and ASCII digit definitions.

**Comment by shigeya** [comment]
I think INFRA should have an `ASCII lower alphanumeric` definition.

**Comment by peacekeeper** [comment]
Thank you, I agree this seems to be a mistake! We have several DID method names that include digits (e.g. `did:v1`, `did:erc725`).

**Comment by msporny** [comment]
This was fixed in PR #492, which has been merged, closing.
