### ISSUE TITLE
Discussion on "localized rules for handling properties" not described anywhere

### ISSUE THREAD

**Issue by shigeya** [w3c/did-core#494]
In Sec. 6. Representation, 

> Deployments of this speciﬁcation MAY use a custom agreed-upon representation, including localized rules for handling properties not listed in the registry. See section § 4.1 Extensibility for more information.

There is no discussion on "localized rules," not only in sec. 4.1, but also anywhere in the doc.

**Comment by msporny** [comment]
This is addressed by PR #507 and will be closed when that PR is merged.
