### ISSUE TITLE
`updated` property's initial value is not defined clearly

### ISSUE THREAD

**Issue by shigeya** [w3c/did-core#495]
In Sec. 8.1.3:
> DID document metadata SHOULD include an updated property to indicate the timestamp of the last Update operation. This property MAY not be supported by a given DID method.

It seems necessary to define the case when there is no update to a DID Document since its initial creation. Two options:

- set `updated` = `created` on creation
- set `updated` to an undefined value.

**Comment by peacekeeper** [comment]
Thanks for bringing this up @shigeya ! In my opinion, the existing language in the specification is sufficient. If there has been no update to a DID document since its initial creation, then by definition there has never been an Update operation, and therefore there is no `updated` property (i.e. it is missing). I guess we could add a sentence to clarify this if you like?

Setting `updated` = `created` is definitely wrong, unless there is a situation where a Create and an Update operation really happen at exactly the same time. I suppose this is theoretically possible, but in practice I don't think we will see any DID method where this occurs.

**Comment by shigeya** [comment]
Thanks for your comment. 

> In my opinion, the existing language in the specification is sufficient. If there has been no update to a DID document since its initial creation, then by definition there has never been an Update operation, and therefore there is no updated property (i.e. it is missing). I guess we could add a sentence to clarify this if you like?

If I read the spec text carefully, I can read as you said. Also, I agree that the second option is way wrong.

But in the reality, there is some database framework implementation that does this style of update timestamp management.  Ruby on Rails is one of them. [Section 2.2 Schema Conventions in Active Record Basics of Rails Guide](https://guides.rubyonrails.org/active_record_basics.html#schema-conventions) states:

> updated_at - Automatically gets set to the current date and time whenever the record is created or updated.

So, as the spec text wise, it is not necessary. But for some careless guys like me, some clarification help to avoid making mistakes. A developer naively maps `ActiveRecord` to DID Document may implement in the wrong way. 

I suspect even some of the method implementation may handle `updated` property similar way.

**Comment by peacekeeper** [comment]
> some clarification help to avoid making mistakes

+1, I agree. Perhaps you could raise a PR to add such clarification? Or would you like me to propose something?

**Comment by shigeya** [comment]
Thanks. I will create a PR later today.

**Comment by shigeya** [comment]
I've been thinking of the relationship between the spec text of this topic and the sameness of two timestamps without having sub-second precision, related to #498 (PR #509). I will find good wording soon.

**Comment by peacekeeper** [comment]
@shigeya are you still planning to raise a PR to add some clarification around this?

**Comment by shigeya** [comment]
@peacekeeper Yes, I do. I will have a proposal soon.

**Comment by rhiaro** [comment]
@shigeya were you thinking something like (addition in bold):

> DID document metadata SHOULD include an `updated` property to indicate the timestamp of the last Update operation for the document version which was resolved. The value of the property MUST follow the same formatting rules as the `created` property. **The `updated` property is omitted if an Update operation has never been performed on the DID document.**

**Comment by shigeya** [comment]
@rhiaro Thanks for writing up the sample text. That's almost what I want to express. I think we need to add a clarification possibly as a note.

 I believe I can use my time later today -- I'm unexpectedly busy at this moment. I may able to use enough time starting later this week.

**Comment by msporny** [comment]
PR #540 has been raised to address this issue. This issue will be closed once PR #540 is merged.

**Comment by brentzundel** [comment]
#540 has been merged, closing this issue.
