### ISSUE TITLE
 Inconsistent definition/name of DID Document (or abstract data model?)

### ISSUE THREAD

**Issue by shigeya** [w3c/did-core#496]
There are several places describing what DID document is. There are inconsistencies among them, which need to be resolved. The relationship between DID Document and Abstract Data Model is unclear.

Followings are part of major inconsistencies:

- 1 Introduction
    - "on the metadata associated with a DID (called the DID document)."

- 1.1 A Simple Example
   -  "A DID document contains information associated with the DID, such as ways to cryptographically authenticate the DID controller, as well as services that can be used to interact with the DID subject."

- 1.3 Architecture Overview
    - "DID documents contain metadata associated with a DID."
    - "DID document is represents an abstract data model"  (It includes a typo. I'll send out a PR quickly)

- 2 Terminology
    - "A DID document is a representation of information describing a DID subject."

- 4 Data Model
    - "This speciﬁcation deﬁnes an abstract data model for DID documents that is capable of being serialized into multiple concrete representations."

- 5 Core properties
    - "DID documents are the serialization of the data model outlined in Section § 4. Data Model."

- 6 Representations
    - "translation between any two representations is done by parsing the source format into <<a DID document model>> and then serializing the DID document model into the target representation.
    - "consumed to the abstract data model"

- 6.1 Representation requirements
    - "The data model"
    - "the DID document data model"
    - "the abstract data model"

- 6.3.1 Production
    - "the abstract data model"

- 6.4 CBOR
    - "CBOR can support all JSON data types for translation between the DID document model (described in Data Model and the Core Properties section of the DID Document)."

- 6.4.1 Production
    - "the Abstract Data Model"
    - "the Data Model"

- 6.5 Converting Data between Core Representations
    - "the Abstract DID Document Data Model (see § 4. Data Model and Production and Consumptions rules between core representation via the Abstract Data Model).

I think we need to discuss a consistent way to describe this.

**Comment by msporny** [comment]
> I think we need to discuss a consistent way to describe this.

Agreed, working on an editorial commit to address this issue.

**Comment by msporny** [comment]
Commit 24b049f45284d852e2da6796c96de87abcf94ef9 attempts to address the terminology misalignment by doing the following:

* It changes all instances of "DID Document Data Model", "DID Document model", "abstract data model", "Abstract DID Document Model" to "data model" (and links to the data model section).
* It refers to the DID Document containing "information related to the DID Subject" throughout the specification.

I believe these two changes address the inconsistent definition/name you were referring to @shigeya. Happy to change any remaining things I missed as a result.

**Comment by shigeya** [comment]
Besides the comment in the commit 24b049f, it looks good to me.
