### ISSUE TITLE
Metadata properties don't define data model and serialization format

### ISSUE THREAD

**Issue by msporny** [w3c/did-core#499]
The current metadata properties in the specification don't define data model and serialization formats for all metadata properties. This should be fairly straightforward to fix by defining this sort of stuff in the definitions for each metadata property.

**Comment by peacekeeper** [comment]
Section ["Metadata Structure"](https://w3c.github.io/did-core/#metadata-structure) says:

> The structure used to communicate this metadata MUST be a map of properties. Each property name MUST be a string. Each property value MUST be a string, map, list, boolean, or null. The values within any complex data structures such as maps and lists MUST be one of these data types as well.

I think you're correct that some metadata properties such as `created` define the data type of their value, whereas this is currently missing for others such as `accept`.

**Comment by msporny** [comment]
PR #516 addresses this issue. This issue will be closed when PR #516 is merged.

**Comment by msporny** [comment]
PR #516 has been merged, closing.
