### ISSUE TITLE
Representation property or representation-specific property ?

### ISSUE THREAD

**Issue by shigeya** [w3c/did-core#500]
In Sec. 4 Data Model, the last statement of the second paragraph:

> The second class of properties are called representation properties, and are speciﬁed in section § 6. Representations.

I think `representation properties` does not correctly express its property.

I propose adding `-specific` like `representation -specific properties`.

**Comment by peacekeeper** [comment]
Our understanding after the TPAC Virtual F2F meeting was that we would not call them properties at all, but rather "representation-specific syntax". This terminology should be discussed in https://github.com/w3c/did-core/issues/463.

**Comment by kdenhartog** [comment]
@shigeya are you alright if I move your comment onto #463 and close this in an effort to consolidate common issues?

**Comment by shigeya** [comment]
@kdenhartog I'm fine to move to #463 and close. thanks:)

**Comment by kdenhartog** [comment]
Thanks, I copied the point raised here into that (I couldn't find a way to transfer the comment directly) and am closing this with a reference back in the comment as well. Thanks for the review!
