### ISSUE TITLE
Correct the serviceEndpoint property to allow for a string or array of strings

### ISSUE THREAD

**Issue by csuwildcat** [w3c/did-core#506]
The current text in the spec says that the `serviceEndpoint` property in Service Endpoint entries must be either a string or an object. Apparently this is not what it should have been (per @msporny), so it should be corrected to allow an array.

See this earlier Issue for history on this: https://github.com/w3c/did-core/issues/359

**Comment by msporny** [comment]
@csuwildcat I've created PR #510 to address this issue. Please review. 

This issue will be closed once that PR is merged.

**Comment by msporny** [comment]
PR #510 has been merged. Closing.
