### ISSUE TITLE
Minor editorial issue: discrepancy between alsoKnownAs and others

### ISSUE THREAD

**Issue by iherman** [w3c/did-core#518]
At present, `alsoKnownAs` is defined as 

> be a list where each item in the list is a URI conforming to [RFC3986].

In all other, similar occurrences of URI-s, like e.g. for controllers, the definition is of the sort:

>  a string or an **ordered set** of strings that conform to the rules in Section § 3.1 DID Syntax.

(Emphasis is mine). Any reason why using lists for one and ordered sets for the others? This is actually the only place where lists are used for the core property definition.

B.t.w., the only other place in the document where lists are used is for `equivalentID`. The same question may apply there: isn't it better to use ordered sets everywhere? One less INFRA notion to be used in the spec...

**Comment by csuwildcat** [comment]
Honestly wasn't aware of the discrepancy until now - is there any practical effect? If not, I don't care personally.

**Comment by TallTed** [comment]
Defining something as an "ordered set" (or an ordered list) implies that there is some importance, some meaning, to that order.

If (as I believe) there is no importance to the ordering of some, any, or all of these, then I suggest that those definitions be changed to say "unordered" (or to have no mention of order).

I have no immediate opinion about "set" vs "list" or "collection" or other group noun/structure, but perhaps we should explore whether there are any implications or stronger meanings associated with these (as has been the case in some other similar situations).

**Comment by iherman** [comment]
@TallTed,

while I agree with your general comments, we have to rely here on the Infra](https://infra.spec.whatwg.org) standard, because that is what we refer to.

As far as I could see, the available data structures in [Infra](https://infra.spec.whatwg.org) are lists, stacks, queues, ordered sets, maps, and structs.  Strangely enough, there are no explicit _unordered_ sets, and the document says, in the [relevant section](https://infra.spec.whatwg.org/#sets):

> Almost all cases on the web platform require an ordered set, instead of an unordered one, since interoperability requires that any developer-exposed enumeration of the set’s contents be consistent between browsers. In those cases where order is not important, we still use ordered sets; implementations can optimize based on the fact that the order is not observable.

(I personally do not agree with the direction taken in Infra, and I think having an explicit unordered set would be a welcome addition to Infra, but that is not a matter of discussion here…)

I.e.: the choice we have is to use either [lists](https://infra.spec.whatwg.org/#lists) or [ordered sets](https://infra.spec.whatwg.org/#sets). (We may add a note somewhere (e.g., in [§4](https://www.w3.org/TR/did-core//#data-model)) that, in case of the DID Core spec, orders are ignored, in line with the Infra note above.)

The semantic difference between the two is that no repeated items are allowed in the case of ordered sets. Basically, my original question can be refined by asking

- is there a case when a repeated item makes sense for `alsoKnownAs` and/or `equivalentID`?

My impression is that the answer is 'no', meaning that these two usages of lists should be exchanged for ordered sets, and the reference to lists could also be removed from the table in [§4](https://www.w3.org/TR/did-core//#data-model).

**Comment by csuwildcat** [comment]
@iherman afaik, there's no case in which an equivalence value would ever be repeated under the same property, so I think your assumption holds and we could go with ordered sets.

**Comment by iherman** [comment]
Minor change on my [proposal](https://github.com/w3c/did-core/issues/518#issuecomment-752373455): there is already a note in §5 stating that orders are irrelevant. No need to add anything.

**Comment by iherman** [comment]
Added PR #522 to speed up processing in case we agree with the conclusions here.

**Comment by rhiaro** [comment]
+1 for consistent use of INFRA ordered sets instead of INFRA [implicitly ordered] lists

**Comment by brentzundel** [comment]
Merging #522 will close this issue

**Comment by iherman** [comment]
@brentzundel #522 has been merged. O.k. for me to close this?

**Comment by msporny** [comment]
PR #522 has been merged, closing.
