### ISSUE TITLE
missing comma in example 37

### ISSUE THREAD

**Issue by bshambaugh** [w3c/did-core#520]
I am a part of the CG, not the working group, but I am trying to put this here to avoid cluttering the list.
Example 37 , in https://www.w3.org/TR/did-core/ may be missing a comma after "EC"

 { "id": "did:example:123#_TKzHv2jFIyvdTGF1Dsgwngfdg3SH6TpDv0Ta1aOEkw", "type": "JsonWebKey2020", "controller": "did:example:123", "publicKeyJwk": { "kty": "EC" "crv": "P-256", "x": "38M1FDts7Oea7urmseiugGW7tWc3mLpJh6rKe7xINZ8", "y": "nDQW6XZ7b_u2Sy9slofYLlG03sOEoug3I0aAPQ0exs4" } }

should be(?):

 { "id": "did:example:123#_TKzHv2jFIyvdTGF1Dsgwngfdg3SH6TpDv0Ta1aOEkw", "type": "JsonWebKey2020", "controller": "did:example:123", "publicKeyJwk": { "kty": "EC", "crv": "P-256", "x": "38M1FDts7Oea7urmseiugGW7tWc3mLpJh6rKe7xINZ8", "y": "nDQW6XZ7b_u2Sy9slofYLlG03sOEoug3I0aAPQ0exs4" } }

**Comment by msporny** [comment]
Thank you @bshambaugh -- editorial and merged PR #521 to fix this issue. Closing issue.
