### ISSUE TITLE
one more `the Data Model` needs to be linked

### ISSUE THREAD

**Issue by TallTed** [w3c/did-core#527]
(creating issue to track this to completion)

@msporny

Direct commits should be avoided as much as possible.

They don't offer a way to ignore white-space changes during review, nor to make suggestions before merge... and making a PR to adjust a tiny piece of a direct commit is a much heavier lift since it's a PR against the whole document(s) involved in that direct commit.

Also, comments made on that commit don't have the same impact as comments or change suggestions on a PR, e.g., https://github.com/w3c/did-core/commit/24b049f45284d852e2da6796c96de87abcf94ef9#r45310176 from @shigeya, which doesn't appear to have been acted on nor responded to.

_Originally posted by @TallTed in https://github.com/w3c/did-core/issues/505#issuecomment-753724753_

**Comment by rhiaro** [comment]
Thanks for noticing the comment and tracking the issue, @TallTed. This specific missing link will be caught by https://github.com/w3c/did-core/issues/163 which is open to track reviewing all such internal refs and definitions.

**Comment by rhiaro** [comment]
pending close as covered by #163

**Comment by brentzundel** [comment]
Covered by #163, no objections raised, closing.
