### ISSUE TITLE
Requirement of MUST for `id` in Verfication Methods and Service Endpoints?

### ISSUE THREAD

**Issue by iherman** [w3c/did-core#529]
At the moment the spec _REQUIRES_ the presence of an `id` attribute for verification methods and service endpoints (see [§5.3](https://w3c.github.io/did-core/#verification-methods) and [§5.5](https://w3c.github.io/did-core/#service-endpoints)). Is this _MUST_ necessary? Isn't it enough to use a _SHOULD_?

The only case where it is (obviously) a must is when the verification method is re-used. But I do not think the spec says that a specific verification method _must_ be reused, in which case the `id` value seems to be superfluous.

(I realize that, in the RDF case, that would mean the usage of a blank node for that specific instance, and there is an aversion against blank nodes in some part of the Semantic Web community. I do not think that is a good enough argument to make it a requirement, though. And this argument is meaningless for the JSON and CBOR serializations.)

**Comment by peacekeeper** [comment]
I originally raised the same question back in the CCG (https://github.com/w3c-ccg/did-spec/issues/247, then continued in https://github.com/w3c/did-core/issues/47), and we indeed changed _MUST_ to _SHOULD_ in https://github.com/w3c/did-core/pull/66.

Then after further discussion in https://github.com/w3c/did-core/issues/134, it was changed back to _MUST_ in https://github.com/w3c/did-core/pull/225.

Personally, my slight preference would be SHOULD rather than MUST. Even though `id` values are useful in many ways, I didn't think that from a data model perspective they should be mandatory. If we want to change this again, others from the previous discussions should also weigh in again.

**Comment by iherman** [comment]
Thanks @peacekeeper I did not remember issue #134. However, in that issue the only technical argument for making it mandatory is https://github.com/w3c/did-core/issues/134#issuecomment-594886651 (by @OR13), the rest of the issue was more a matter of a discrepancy in the spec of the time. I am not an implementer, and I cannot really judge the strength of the arguments in https://github.com/w3c/did-core/issues/134#issuecomment-594886651; I must admit it is not very convincing to me personally.

However. Procedurally, we should not reopen closed issues unless new arguments come to the fore. The only new situation is a systematic cleanup of the vocabulary (see also issue #404, as well as PR  #528) which forces us to re-evaluate some of these details. If the judgement of the chairs and editors is that this is not a good enough reason to reopen the issue, I will accept it.

**Comment by OR13** [comment]
I prefer MUST, because it simplifies consuming logic, callers can rely on the presence of the field instead of checking for it in every did document they encounter.

**Comment by msporny** [comment]
> I prefer MUST, because it simplifies consuming logic, callers can rely on the presence of the field instead of checking for it in every did document they encounter.

Agree.

**Comment by iherman** [comment]
ok. This is not the issue on which I would lie down on the road :-) @msporny, is the protocol such that I can simply close this issue?

**Comment by msporny** [comment]
> @msporny, is the protocol such that I can simply close this issue?

Yes, the person that opens the issue can always decide to close the issue IF there doesn't seem like there is someone else that wants to keep fighting for any particular position. That is, as long as @peacekeeper feels it's ok to close, we can close the issue.

**Comment by msporny** [comment]
@peacekeeper is fine with closing this issue. Closing.
