### ISSUE TITLE
Normative vs. non-normative references

### ISSUE THREAD

**Issue by iherman** [w3c/did-core#53]
There are some document references that are done in a normative section and have a normative reference role, although the target is currently just an IETF draft, a note of the CG, etc. It is not a problem _now_ but may become when the document becomes a Rec (unless the target documents become standards by then). The ones I spotted (and there may be more):

- Section 4.3 is normative, and defines the generic DID parameter name `hl` referring to the [Hashlink spec](https://tools.ietf.org/html/draft-sporny-hashlink-02) (which is a draft)
- Sections 4.3, 4.7, and 8 are normative, and normatively refer to the [DID resolution](https://w3c-ccg.github.io/did-resolution/) document (which is a CG report)
- Section 5.9 are normative and normatively refers to the [Linked Data Proofs](https://w3c-dvcg.github.io/ld-signatures/) (which is a CG report; note that this reference also bypasses the references at the end of the document, which I am not sure is o.k.)
- Section 7.1 refers to a DID registry, which is "a type of Verifiable Data Registry", referring to an [informative section of the VC data model](https://www.w3.org/TR/vc-data-model/#ecosystem-overview). Although the reference here is a _MAY_, so it may not be a normative one, but it may be better to make this somehow clearer.
 
---

<s>I am also not sure how we should handle the registries ([LD Cryptographic Suite Registry](https://w3c-ccg.github.io/ld-cryptosuite-registry/), [DID method registry](https://w3c-ccg.github.io/did-method-registry/)) listed in Appendix A. There are discussions at W3C on setting up a somewhat more controlled approach for such registries, and this may be at our disposal in the lifetime of this WG. Alternatively, we may want to publish them as WG notes, to give them somewhat more weight. Something to keep an eye on. </s>

**Comment by msporny** [comment]
> I am also not sure how we should handle the registries (LD Cryptographic Suite Registry, DID method registry) listed in Appendix A. There are discussions at W3C on setting up a somewhat more controlled approach for such registries, and this may be at our disposal in the lifetime of this WG. Alternatively, we may want to publish them as WG notes, to give them somewhat more weight. Something to keep an eye on.

@iherman, can you split the above out into a separate issue, please? That one needs discussion by the group, but the other stuff you mention is purely editorial.

**Comment by iherman** [comment]
@msporny, right, I should have known better. I have created #58 for the registry handling problem.

**Comment by msporny** [comment]
I'll update all the normative and non-normative references in the spec.

**Comment by rhiaro** [comment]
PR to fix references was merged a month ago, can we close this?

**Comment by msporny** [comment]
Yes, stale issue, closing unless there is an objection from @iherman.

**Comment by brentzundel** [comment]
No objections, closing.
