### ISSUE TITLE
Some Question About DID

### ISSUE THREAD

**Issue by zhanb** [w3c/did-core#532]
Hi, I've been following did for a long time. At present, I'd like to ask some questions about DIDs:
1. In addition to the @content, ID, pubkey and so on mentioned in the did core, can different did methods  specification add new fields? If so, is there a limit on the number of fields, or is there a limit on the size of the whole did document? And how can other people resolve and distinguish the newly added fields
2. The did-resolution only defines a DID resolver binding which exposes the DID resolution and/or DID URL dereferencing functions (including all input metadata properties and output data) via an HTTP(S) endpoint. Is there a standard similar to DNS resolving 
 based on UDP / TCP resolving

**Comment by OR13** [comment]
@zhanb 

different did methods may add fields, but the fields that can be added are limited by the representation.

for example, json cannot have integer keys, but cbor can, xml cannot have `@` in key names, etc...

Its also not a good idea to add fields that might be used to decrease the anonymity set of the did subject (reduce privacy).

If you want to add new fields to JSON, JSON-LD and CBOR and have them all be understood, you need to describe the field in the the `@context` (for JSON-LD), JSON will ignore this description and CBOR is just JSON today.

so for example, this is valid:

```
{
"@context": [
      "https://www.w3.org/ns/did/v1",
{  "email": "https://schema.org/email"}
  
    ],
 "id": "did:key:z6MkfTAj5oWwHdhzuUM57oH1bvt3gkoiUNkBBQw8s37wcAff",
  "email": "customer-support@example.com"
}
```

You might also choose to register that extension in the did spec registries which a url like:

 "https://example.com/did-extensions/v1",
 
 here are some other examples from the did spec registries:
 
 adding support for GPG keys: https://w3c.github.io/did-spec-registries/#gpgverificationkey2020
 
 adding support for ethereumAddress: https://w3c.github.io/did-spec-registries/#ethereumaddress
 
 Again, you should avoid putting anything but cryptographic verification material and correlation safe identifiers in a did document.

**Comment by OR13** [comment]
@zhanb does my reply address your question? If so I would like to close this issue, if not, I am happy to provide additional details.

**Comment by zhanb** [comment]
> @zhanb does my reply address your question? If so I would like to close this issue, if not, I am happy to provide additional details.

Thanks a lot
