### ISSUE TITLE
DID URL dereferencing term definition is inconsistent with its section

### ISSUE THREAD

**Issue by peacekeeper** [w3c/did-core#545]
The "DID URL dereferencing" [definition in the Terminology](https://w3c.github.io/did-core/#dfn-did-url-dereferencing) says:

> The function that takes as its input a DID URL, a DID document, plus a set of dereferencing options, and returns a resource

But the [DID URL Dereferencing section](https://w3c.github.io/did-core/#did-url-dereferencing) doesn't mention that the input can be a DID document. Therefore, "DID document" as an input should be removed from the Terminology definition.

**Comment by msporny** [comment]
PR #546 has been raised. This issue will be closed once that PR has been merged.

**Comment by msporny** [comment]
PR #546 has been merged, closing.
