### ISSUE TITLE
Replace undefined term "resolving party" in equivalence properties

### ISSUE THREAD

**Issue by peacekeeper** [w3c/did-core#563]
The sections on equivalence properties "equivalentId" and "canonicalId" use the term "resolving party". We decided previously that we would use the term "requesting party" for this role. See https://github.com/w3c/did-core/pull/350 and https://github.com/w3c/did-core/pull/393.

@csuwildcat maybe you want to make that change, otherwise I can do it too.

**Comment by msporny** [comment]
PR #567 has been created to address this issue, which will be closed once the PR has been merged.

**Comment by msporny** [comment]
PR #567 has been merged, closing.
