### ISSUE TITLE
Registry handling

### ISSUE THREAD

**Issue by iherman** [w3c/did-core#58]
I am not sure how we should handle the registries ([LD Cryptographic Suite Registry](https://w3c-ccg.github.io/ld-cryptosuite-registry/), [DID method registry](https://w3c-ccg.github.io/did-method-registry/)) listed in Appendix A. There are discussions at W3C on setting up a somewhat more controlled approach for such registries, and this may be at our disposal in the lifetime of this WG. Alternatively, we may want to publish them as WG notes, to give them somewhat more weight. Something to keep an eye on.

**Comment by jandrieu** [comment]
The CCG is still figuring out its process. Our intention is to specify an extremely lightweight approach, something like: registries must be created in accordance with W3C policy. That policy is TBD, **and** the CCG co-chairs are still working through both charter and election issues at the moment.

**Comment by OR13** [comment]
Please see also: https://github.com/w3c/did-core-registries

**Comment by OR13** [comment]
I think this has been mostly fixed, I have made a lot of updates to:

- https://github.com/w3c-ccg/security-vocab

- https://github.com/w3c-ccg/ld-cryptosuite-registry

**Comment by msporny** [comment]
This is being discussed in W3C CCG and the hope is we take the best of the DID Spec Registries process, the VCWG Maintenance WG process delegated to W3C CCG, and apply them to how these registries are handled.

**Comment by msporny** [comment]
Conversation is ongoing, no resolution yet.

**Comment by msporny** [comment]
We need to clearly document the process of how the registry is updated. This issue will be closed when we can point to a clearly documented process in the CCG.

**Comment by selfissued** [comment]
We had agreement in issue #169 to replace dependencies on registries administered by community groups to registries administered by this working group.  Therefore, I consider it a strange proposed regression that we're even talking about "a clearly documented process in the CCG".  We should instead be talking about "a clearly documented process described in a DID working group specification".

**Comment by msporny** [comment]
> We had agreement in issue #169 to replace dependencies on registries administered by community groups to registries administered by this working group. Therefore, I consider it a strange proposed regression that we're even talking about "a clearly documented process in the CCG". We should instead be talking about "a clearly documented process described in a DID working group specification".

At some point, this WG will end and the question of who will maintain the registry then will need to be answered. This was answered in the W3C VCWG by delegating the day-to-day management to the W3C CCG. This group will most likely take the same path... a DID Maintenance WG will be set up where consensus decisions are made in the CCG and then elevated to the DID Maintenance WG for a thumbs up/ thumbs down vote (as a safe guard against bad decisions or things outside of the WG Charter. The process will be defined in the DID Spec Registries document, but the execution of those rules will be delegated to the CCG. The CCG needs a documented process for how they're going to handle their side of this. That has not been completed yet. That's the document we need to be able to point to to ensure that the process on both sides is set up correctly.

**Comment by selfissued** [comment]
I disagree that this working group will delegate administration of its registries to any community group or other working group.  All of those will eventually end.  Rather, as discussed during the face-to-face working group meeting in January 2020, the W3C is developing procedures to operate registries itself.  We should turn administration of the registries over the W3C when the working group terminates - just as IETF specs turn over ongoing registry administration to IANA - which is constituted for that purpose.

@iherman , can you update us on the progress made in establishing W3C registry procedures since January?  Thanks!

**Comment by msporny** [comment]
> Rather, as discussed during the face-to-face working group meeting in January 2020, the W3C is developing procedures to operate registries itself.

Yes, I've participated in those discussions. Here was the latest attempt at the process:

https://w3c.github.io/w3process/registries/#registries

The work item has been deferred to next years W3C Process. We are aligned with the latest thinking wrt. registries. That is the process that is defined in the DID Spec registries, we haven't named a maintainer yet, the W3C CCG is a natural maintainer for the registry. 

We have picked the W3C CCG in the past (for VCWG maintenance, Linked Data Security Maintenance, etc.) because it has existed for many years, is composed of 400+ people, has a stable process that we can depend on, and we can always fall back to W3C Team as backup in case the W3C CCG fails... it also offloads that work from the W3C Team, whose time is very limited and precious.

If you'd like to name some entity other than the W3C CCG as the maintainer, @selfissued, I suggest you make a concrete proposal and put it in front of the group.

**Comment by iherman** [comment]
> @iherman, can you update us on the progress made in establishing W3C registry procedures since January? Thanks!

I am afraid there is nothing new to report on this subject, @selfissued; as @msporny said, the issue will be picked up in the process discussions in 2021.

Just some comments on what has been said so far:

- Yes, the current approach is to transform a WG that has finished its work into a "maintenance" WG. Such a WG is there to make minor changes to its published Recommendations but will not engage in significant new work items. This is the approach in the VC and JSON-LD case, for example, which both have become "maintenance" groups. (The new 2020 process will actually allow for more possibilities in adding features to a standard, so these maintenance groups may become more active in the future.)
- It is to be expected that the maintenance of registries may be the job of these maintenance WG-s, too. The details will also depend on the work done in 2021 on registries in general.
- I do not fully agree with @msporny on the description of the CCG's role. When the time comes, the maintenance WG will have to work out its procedures on maintaining the registries.  I would agree with @selfissued that the maintenance of the registry must be formally under the future WG's control, it will have the final say. Whether the WG will involve the CCG or not, whether the technical discussions will be delegated to the CCG or not, etc, is up to the WG to decide when the time comes.

    In practice, of course, I do expect that the practical work will be done at the CCG, which represents the community (similarly to the aforementioned JSON-LD and VC cases). But I think discussing the formal aspects is way too early right now.  All this will have to be handled when we recharter the WG at the end of its current charter, and circumstances may have been changed by then.

**Comment by wyc** [comment]
Hi, the CCG is happy to facilitate involvement at whatever desired level as a work item, whether it's the work done in CCG and registry accepted in the DID WG, or any less or greater level of involvement. What do the contributors prefer?

**Comment by msporny** [comment]
If this WG is going to be changed into a maintenance WG, then there is nothing to do. If this WG is going to hand over maintenance of the registry to the CCG (just like the VCWG did), then there is nothing to do. The DID Spec Registries document already outlines a process, it needs to be updated, and an issue should be raised over there if anything more needs to be done.

Marking this issue as pending close. It will be closed in 7 days unless there are objections.

**Comment by selfissued** [comment]
As I wrote in August:
> I disagree that this working group will delegate administration of its registries to any community group or other working group. All of those will eventually end. Rather, as discussed during the face-to-face working group meeting in January 2020, the W3C is developing procedures to operate registries itself. We should turn administration of the registries over the W3C when the working group terminates - just as IETF specs turn over ongoing registry administration to IANA - which is constituted for that purpose.

We should make an affirmative decision to turn administration over to the W3C after the working group ends.  We should also go on record that the registries will not be turned over to any community group.

**Comment by OR13** [comment]
@selfissued who will manage pull requests, W3C Staff?

I think the amount of work that is necessary to safely support the registry is not comprehended by anyone in the working group.... We need to support:

1. registration of new did document properties
2. registration of new did parameters
3. registration of new did document representations (including production / consumption)
4. registration of new did methods (including checks for conformance).

As long as the WG commits to these things happening.... I don't care who the registries is delegated too... but if any of these things are jeopardized by handing the registry maintenance to some hyper biased / closed / opaque / slow process... This will kill DIDs.... I agree this needs to be defined clearly ASAP.

**Comment by iherman** [comment]
> We should make an affirmative decision to turn administration over to the W3C after the working group ends.

There is no affirmative decision needed in my view. W3C owns the rights to the DID Core spec as well as the Registry document. The copyright statement is part of the header of all those documents. 

When the Working Group charter runs out, it is up to the W3C membership to decide on what happens there, based on the _proposal_ of interested parties. As long as this decision is pending, W3C, as owner of the spec, indeed "administers" the specification.

I am not sure what decision this W3C could take.

> We should also go on record that the registries will not be turned over to any community group.

"turned over" would mean that W3C abandons its copyright. I do not see that happening. However, the ultimate decision of that lies in the hands of the W3C Members; the AC members may vote of, say, rescinding a recommendation and any other document. Legally speaking this WG cannot do anything against that, so such "record" does not really carry any weight in my view.

However. The WG can of course go on record, as a group resolution, on a _preferred_ set of actions as for the future of the registries. Following the current practice, the expected approach is to set up a maintenance DID WG (provided, of course, that the W3C Membership votes for such a maintenance group). Such a group does not really do new development, but maintains the IPR on the documents and maintains the registry. The group could then "administer" or "control" the WG registry.  The charter of the maintenance WG _may_ include a cooperation with the CCG that could act as an incubator group. All this is the subject of the membership's review vote.

---

There are recent examples. In my own practice only I am staff contact for the VC and JSON-LD "maintenance" Working Groups, and the vote has just ended for the Audiobooks Working Group. All following the same model. Each of those have a strong cooperation with a CG (the CCG for the VC, the JSON-LD CG for, well, JSON-LD, and the Publishing CG for the upcoming Audiobook Working Group).

**Comment by msporny** [comment]
The proposal is to:

1. Raise an issue on DID Spec Registries about how the registry will be maintained after the WG shuts down.
2. Close this issue, because this is the issue tracker for DID Core, which shouldn't have a say on did-spec-registries.

I have done the first item here: https://github.com/w3c/did-spec-registries/issues/149

... which means the only thing left to do is close this issue.

**Comment by kdenhartog** [comment]
I see this was marked pending close 9 days ago, but it appears @selfissued still believes differently. I'll leave this one open while we await response on the options presented by @msporny to go forward.

**Comment by msporny** [comment]
> I see this was marked pending close 9 days ago, but it appears @selfissued still believes differently. I'll leave this one open while we await response on the options presented by @msporny to go forward (which would leave this issue to be closed).

Thanks @kdenhartog -- since @selfissued is disagreeing, we'll have to take it up in a call and get a formal resolution to close this.

**Comment by OR13** [comment]
@selfissued would you mind making a proposal in advance of the special topic call that addresses my concerns raised here: https://github.com/w3c/did-core/issues/58#issuecomment-72068113.

I think we can potentially resolve this on this thread if we can make clear proposals,

**Comment by ChristopherA** [comment]
@jandrieu and I are currently assigned this issue, but are no longer CCG co-chairs.

You probably should make it clear/explicitly invite all three CCG co-chairs to this special meeting. Not all are members of DID-core.

**Comment by brentzundel** [comment]
@wyc and @kimdhamilton are assigned to this issue and have been since June, when @jandrieu and @ChristopherA were unassigned.

This issue will be the topic of discussion during a special DID WG call Thursday, December 17, 2020.

**Comment by wyc** [comment]
Hi @brentzundel, I plan to attend tomorrow. Basically we need to group to decide what is acceptable for the administration of registries, and we are happy to support any work items if it is agreed that CCG is the right place.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2019/did-wg/Meetings/Minutes/2020-12-17-did-topic#section1) on 2020-12-17

List of resolutions:

- ***[Resolution No. 1](https://www.w3.org/2019/did-wg/Meetings/Minutes/2020-12-17-did-topic#resolution1):  The DID Working Group will maintain the DID Spec Registries until the end of its charter. The DID Working Group plans to request the management of W3C to submit a charter for a maintenance DID Working Group to the W3C Advisory Committee as a successor to this Working Group. Per the planned charter of that Working Group, that group would officially manage the registry, and would do that in cooperation with the W3C Credentials Community Group.***

<details><summary><i>View the transcript</i></summary>

### 1. Registry ownership and maintenance roadmap 

_See github issue [#58](https://github.com/w3c/did-core/issues/58), [did-spec-registries#149](https://github.com/w3c/did-spec-registries/issues/149)._




**Brent Zundel:** we have a large enough group to get started.  
… manu and ivan have proposals to put before the group.  

**Ivan Herman:** let me try to summarise some things that were discussed.  
… there were two issues that were used for the same problem.  
… (58 and 149).  
… the Registries is published as w3c working group note.  
… the first thing that's very formal is that only a WG has the right to reissue a note.  
… if we do any kind of update on the Spec Registries there must be a WG or the Team to republish a note.  
… this is the first thing we should not forget..  
… the second is that by now we have this practice of having continuation working groups which have to be approved by the AC, so it is always conditional.  
… but my mental model is that this WG when it finishes will create a continuation WG.  
… but probably only maintenance.  
… this is something we can decide later.  
… that seems to be a natural place which formally speaking maintains the registry and has the right to republish it and do things.  
… this is the formal part..  
… In practice, the same way as we have in other groups, there is a CG somewhere in the background which is active because the WG will not have regular meetings.  
… and that's how I came up with the proposal.  
… for me this is a clear path, and no disagreement with mike who is adamant on saying the w3c must continue to have control over the registry which I agree with.  
… and there are practicalities to work out, and what the CG process is.  
… but that's way down the line, not something we have to worry about right now.  

**Manu Sporny:** agree with ivan.  
… I did a minor reword of the original proposal to align it with the others.  
… I'd like to see if we can get ivan's proposal passed, that shortcuts a lot of the other discussions we could have.  
… there are other things that have come up wrt the registries.  
… one has to do with a copyright trademark/legal concerns.  
… the other has to do with security and privacy concerns.  
… and how much power the registry editors have to say no.  
… we've traditionally had the position that we can't block anything from getting in.  
… and some of our members rightly pointed out that no that's really dangerous to not be able to stop things that are racist, trademark violations, a whole class of things we would not want.  
… being able to say no is important.  
… if the editors can say no, people have said they want a process that allows them to override the editors, what is the escalation process.  
… so the proposals are meant to address all of those questions when we put them forward.  

**Ivan Herman:** we should try to separate those things.  
… the proposal I had was on the ownership of the registry.  
… and the way it is managed later.  
… that is something that can be agreed upon.  
… and then we can get it out of the way.  
… the second question you have is regardless of that problem. We have to discuss it, but it's a separate issue.  

**Manu Sporny:** +1.  

**Brent Zundel:** I think we can put those proposals forward.  

> **Proposed resolution: The DID Working Group will maintain the DID Spec Registries until the end of its charter. The DID Working Group plans to request the management of W3C to submit a charter for a maintenance DID Working Group to the W3C Advisory Committee as a successor to this Working Group. Per the planned charter of that Working Group, that group would officially manage the registry, and would do that in cooperation with the W3C Credentials.** *(Ivan Herman)*

> *Manu Sporny:* +1.

> *Orie Steele:* +1.

> *Shigeya Suzuki:* +1.

> *Amy Guy:* +1.

> **Proposed resolution: The DID Working Group will maintain the DID Spec Registries until the end of its charter. The DID Working Group plans to request the management of W3C to submit a charter for a maintenance DID Working Group to the W3C Advisory Committee as a successor to this Working Group. Per the planned charter of that Working Group, that group would officially manage the registry, and would do that in cooperation with the W3C Credentials Community Group.** *(Ivan Herman)*

> *Manu Sporny:* +1.

> *Ivan Herman:* +1.

> *Shigeya Suzuki:* +1.

> *Joe Andrieu:* +1.

> *Amy Guy:* +1.

> *Drummond Reed:* +1.

> *Brent Zundel:* +1.

> ***Resolution #1: The DID Working Group will maintain the DID Spec Registries until the end of its charter. The DID Working Group plans to request the management of W3C to submit a charter for a maintenance DID Working Group to the W3C Advisory Committee as a successor to this Working Group. Per the planned charter of that Working Group, that group would officially manage the registry, and would do that in cooperation with the W3C Credentials Community Group.***

**Ivan Herman:** we should be formal, this is a long term commitment. The resolution of this call is not formal, so that should be reaffirmed by the WG next week if possible.  

**Brent Zundel:** will add to agenda.  

**Ivan Herman:** should be administrative, but prefer to have something like that.  

> *Drummond Reed:* +1 to have this reaffirmed in the full WG meeting.

**Brent Zundel:** next tuesday is last calls of the year, normal call and special topic call.  
… and it's an asia time call... which means there is no special topic call....  
… just one next Tuesday.  

</details>

**Comment by jricher** [comment]
As of 2020-12-22, deadline for objecting to resolutions has been extended to 2021-01-05 (tuesday).

**Comment by iherman** [comment]
Resolution 1 on the call on [2021-01-05](https://www.w3.org/2019/did-wg/Meetings/Minutes/2021-01-05-did#resolution1] charts a way forward for registry handling once the current WG is closed. Closing issue.
