### ISSUE TITLE
"Personal data" or "PII"

### ISSUE THREAD

**Issue by peacekeeper** [w3c/did-core#590]
In some sections we use the term "personal data", in others we use "personally-identifiable information".

There have been various PRs that changed one to the other and back (e.g. https://github.com/w3c/did-core/pull/232 or https://github.com/w3c/did-core/pull/535). We should pick one of the terms and use it consistently.

I hereby propose that "personal data" is the more modern one of the two terms and that we should use this one everywhere.

**Comment by agropper** [comment]
I agree with "personal data". The two terms are not interchangeable. For example, correlation and potential re-identification of two health records from different hospitals that have a pair of blood test results reported as 5.36 and 467 might suffice even though all PII has been removed from both files.
