### ISSUE TITLE
Is this a bug in the spec?

### ISSUE THREAD

**Issue by iherman** [w3c/did-core#647]
The spec says, in [§3.2](https://w3c.github.io/did-core/#did-url-syntax)

> A DID URL is a network location identifier for a specific resource. It can be used to identify things like DID subjects, verification methods, services, specific parts of a DID document, or other resources.

Without wanting to open a can of worms on identification, is it correct to say that DID URL-s can be used to identify a DID subject? I though that DID subjects are identified by _DIDs_ not _DID URLs_.

(If this is indeed a bug, I am happy to submit a PR to remove this, but I wanted to be sure.)

**Comment by peacekeeper** [comment]
I don't think it's a bug, since a DID URL can consist of only a DID itself (without path, query, fragment), in which case I think it's correct to say that the DID URL can identify a DID subject.

**Comment by iherman** [comment]
> I don't think it's a bug, since a DID URL can consist of only a DID itself (without path, query, fragment), in which case I think it's correct to say that the DID URL can identify a DID subject.

Sigh... in another universe I would have preferred to use a different syntax and not mix these two concepts as it is in the current document. I do believe that the current syntax and formulation is confusing...

But I will not lie down the road on this. Happy to close this if the current text reflects WG consensus.

**Comment by jandrieu** [comment]
I think Ivan is right on this one.

The DID identifies the DID subject.

A DID URL provides a means to interact with a resource associated with that subject.

The language cited should be changed. 

Perhaps to something like 
> A DID URL is a network location identifier for a specific resource. It can be used to retrieve things like representations 
> of DID subjects, verification methods, services, specific parts of a DID document, or other resources.

**Comment by iherman** [comment]
Created #655 with the proposed change of @jandrieu. Better continue the discussion there.

**Comment by peacekeeper** [comment]
I also agree with @jandrieu 's change.

**Comment by iherman** [comment]
Related #655 has been merged. This issue can be closed, @brentzundel @msporny
