### ISSUE TITLE
Solution for production of representation specific properties

### ISSUE THREAD

**Issue by OR13** [w3c/did-core#662]
instead of thinking about production as a function of the ADM, let us think of it as a function of the ADM and the representation.... 

So for example:

```ts
const produce = (adm: infra<map>, representation: infra<map>) => {
  let didDocument = {...adm, ...representation};
  return serialize(didDocument);
}
```

the production rules can then apply normative requirements to both the adm and the representation, and their combination....

consumption remains the same, no need for "special buckets" or dangerous complexity.... if you consume JSON-LD and produce JSON, `@context` is preserved... if you consume JSON and produce JSON-LD you add the context during production and it never gets added to the ADM...

The same would apply to any representation specific properties... they are ALWAYS preserved on consumption, and ALWAYS required as a second argument of production.

**Comment by msporny** [comment]
Doh, didn't see this before creating https://github.com/w3c/did-core/issues/664 -- the issues are related, don't know if you agree that overlap is 100%... you make the call -- do you want to merge, or keep these separate?

**Comment by OR13** [comment]
Also related: https://github.com/w3c/did-core/pull/654#issuecomment-780635390
