### ISSUE TITLE
DID Document, Representation, and Representation-Entries data model?

### ISSUE THREAD

**Issue by msporny** [w3c/did-core#664]
At present, the DID Core specification only has one data model -- the one that's used to express DID Documents and their sub data structures (verification methods, services, identifiers, etc.)

This has always given a subset of the group heartburn -- @peacekeeper has wanted to separate representation-specific entries from the DID Document entries. There is a valid argument to do so, in order to not mix one set of map entries with another set of map entries.

There is also an open question related to: "What data model holds the data structures that you have after you process the input bytes during consumption?" For example, our current CBOR rules require you to preserve CBOR Tags, but we do a giant handwave over exactly how that's accomplished. It would typically be accomplished by working on the map data structures that you get after you do CBOR.decode(...) in most libraries.

So, this raises two questions:

1. Do we want to introduce the concept of a **representation data model**, which will be vaguely defined with no normative statements associated with it, but can answer the question of "What data model holds the data structures that you have after you process the input bytes during consumption?"
2. Do we want to introduce the concept of a **representation-entries data model**, which would hold representation-specific entries that could be used by any production process and would aid in cross-representation conversion w/o dumping representation-specific garbage into the **DID Document** data model?

**Comment by OR13** [comment]
See also : https://github.com/w3c/did-core/pull/654#issuecomment-780635390

**Comment by OR13** [comment]
1. is probably DOA... I think we will not be able to agree to 1 (some of us think JSON-LD and JSON Schema are JSON, others don't).... I think we have beaten this topic to death, multiple special topic calls, many resolutions, including preserving unregistered properties, etc... I really don't want to re-litigate this issue... especially at the last minute.

2. I can get behind 2 but only as long as it stays limited to production.... and its still dangerous / harmful complexity...

**Comment by TallTed** [comment]
@OR13 - The very long inline comments on Option 3 are hard to digest in this form. Would you please break those comments into multiple shorter lines?

**Comment by peacekeeper** [comment]
From my perspective, Option 3.1 and Option 3.3 would both work. In my mind it has always been like that anyway. There is an abstract data model that contains services, verification methods, etc. And then there are representation-specific things such as CBOR tags or `@context` that should not be mixed with the abstract (representation-independent) things.

Both Options would also allow @OR13 and @msporny to put `@context` into an `application/did+json` DID document (even though personally I think that's a bad idea that contradicts why we introduced the abstract data model concept in the first place).

**Comment by msporny** [comment]
PR #679 has been opened to address this issue. This issue will be closed once PR #679 is merged.

**Comment by peacekeeper** [comment]
Can this be closed now that https://github.com/w3c/did-core/pull/679 has been merged?

**Comment by msporny** [comment]
> Can this be closed now that #679 has been merged?

Yes. :)

PR #679 has been merged. Closing.
