### ISSUE TITLE
(editorial) Erroneous causality in the terminology item on DID?

### ISSUE THREAD

**Issue by iherman** [w3c/did-core#672]
The [terminology section](https://w3c.github.io/did-core/#terminology) section says: 

> **decentralized identifier (DID)**
> A globally unique persistent identifier that does not require a centralized registration authority because it is generated and/or registered cryptographically. (…)

I do not think there is, strictly speaking a causality between "does not require a centralized registration authority" and "generated and/or registered cryptographically". My ORCID ID (https://orcid.org/0000-0003-0782-2704) is probably generated by some crypto method (looking at the ID URL above), but the ORCID ID is still centralized.

What about, simply:

> **decentralized identifier (DID)**
> A globally unique persistent identifier that does not require a centralized registration authority **and** it is generated and/or registered cryptographically. (…) [Emphasis is mine]

(I am happy to submit a PR if there is an agreement on this)

**Comment by msporny** [comment]
> A globally unique persistent identifier that does not require a centralized registration authority and it is generated and/or registered cryptographically.

It doesn't need to be generated cryptographically if the registry is centralized. How about:

> A globally unique persistent identifier that does not require a centralized registration authority and is often generated and/or registered cryptographically.

**Comment by iherman** [comment]
> 
> > A globally unique persistent identifier that does not require a centralized registration authority and is **often** generated and/or registered cryptographically.

That works for me. Should I do a PR or do we want others to chime in?

**Comment by iherman** [comment]
I went ahead and made a PR (#676) for this. Let us move the discussion (if any) there.

**Comment by TallTed** [comment]
I just know that someone's going to question what "often" means, and how we know it...

**Comment by msporny** [comment]
PR #676 has been merged, closing.
