### ISSUE TITLE
The definition of dereference output in Sec. 1.3 is not in sync with the definition of contentStream in Sec. 8.2

### ISSUE THREAD

**Issue by shigeya** [w3c/did-core#680]
Related to PR #634, I found the following discrepancy:

In [Sec.1.3](https://w3c.github.io/did-core/#architecture-overview):
*DID URL dereferencers and DID URL dereferencing*
> A DID URL dereferencer is a system component that takes a DID URL as input and produces a serialized resource as output.

In [Sec 8.2 URL Dereferencing](https://w3c.github.io/did-core/#did-url-dereferencing):
*contentStream*
> If the dereferencing function was called and successful, this MUST contain a resource corresponding to the DID URL. The contentStream MAY be a resource such as a DID Document that is serializable in one of the conformant representations, a Verification Method, a service, or any other resource format that can be identified via a MIME type and obtained through the resolution process. If the dereferencing is unsuccessful, this value MUST be empty.

Do we need to adjust the text in Sec 1.3?

If we don't need adjustment, the diagram in Sec 1.3 can be simpler :)

**Comment by msporny** [comment]
We don't need to adjust. The language in Section 1.3 is meant to just provide a simple overview, not be an exhaustive normative description (which is what Sec 8.2 is for).

**Comment by shigeya** [comment]
As far as the whole text in the section and the diagram are in sync, I'm okay.
(assuming you're going to adjust the diagram in Sec. 1.3.)

**Comment by shigeya** [comment]
Closing this issue since I agreed.
