### ISSUE TITLE
This may be a minor bug: media type file extensions

### ISSUE THREAD

**Issue by iherman** [w3c/did-core#684]
At present all file extensions for the media types in the [IANA considerations section](https://w3c.github.io/did-core/#iana-considerations) are identical: `.did`. I would think this is a copy/paste bug...

**Comment by msporny** [comment]
PR #701 has been raised to fix this bug. This issue will be closed once that PR is merged.

**Comment by msporny** [comment]
PR #701 has been merged, closing.
