### ISSUE TITLE
references to RFC 7159

### ISSUE THREAD

**Issue by reschke** [w3c/did-core#685]
https://www.w3.org/TR/did-core/#data-model has still references to the obsoleted JSON spec.

**Comment by OR13** [comment]
@reschke can you point us to the "non obsoleted JSON" spec.

**Comment by reschke** [comment]
That's RFC 8259, also cited in this document.

**Comment by msporny** [comment]
> That's RFC 8259, also cited in this document.

Fixed in fb8f6f5232b7749e5cac9d971381fcd79c4d82a6.

Thank you @reschke!

Also, "Hi!" -- it's been a while... out of curiosity, why are you looking at this spec? :)

**Comment by reschke** [comment]
some mail to an IETF mailing list (media type? URI?) dragged me here :-)

**Comment by msporny** [comment]
> some mail to an IETF mailing list (media type? URI?) dragged me here :-)

Ah, right... been watching that thread with great interest. We do need "application/did+ld+json" -- all other alternatives we've looked at have fairly terrible downsides. I've been waiting for enough people to get their concerns registered on the mailing list, and for the Decentralized Identifiers specification to go into Candidate Recommendation (expected early March 2021), to do a final push for "application/did+ld+json" (and retroactive rationale for structured media types) on the IETF media types mailing list.

Thanks for the catch, @reschke, much appreciated. :)

**Comment by msporny** [comment]
This issue has been addressed in the spec, closing.
