### ISSUE TITLE
Deactivated is not an errror

### ISSUE THREAD

**Issue by OR13** [w3c/did-core#687]
The spec incorrectly lists "deactivated" as an error for resolution... however, deactivated
 is a valid state for a DID Document, and resolving a deactivated DID MUST NOT produce an error.

<img width="928" alt="Screen Shot 2021-02-20 at 12 59 00 PM" src="https://user-images.githubusercontent.com/8295856/108605710-943b0680-737b-11eb-94eb-9a7162bfecb0.png">

**Comment by OR13** [comment]
@jricher @peacekeeper would either of you resolution experts care to fix this? :)

completing a valid DID Operation should not produce permanent errors during resolution.

**Comment by peacekeeper** [comment]
Hmm we fixed this already in https://github.com/w3c/did-core/pull/581, but then it looks like it got unfixed in https://github.com/w3c/did-core/pull/601 :)

**Comment by peacekeeper** [comment]
Fixed by https://github.com/w3c/did-core/pull/691. Closing.
