### ISSUE TITLE
typo: This property is OPTIONAL for the resolveResolution

### ISSUE THREAD

**Issue by OR13** [w3c/did-core#688]
<img width="841" alt="Screen Shot 2021-02-20 at 1 10 36 PM" src="https://user-images.githubusercontent.com/8295856/108606012-1a0b8180-737d-11eb-8ab3-782bb8aa71f3.png">

Should be resolveRepresentation

**Comment by OR13** [comment]
also terrible normative requirement "and MUST NOT be used with the resolve function."

**Comment by OR13** [comment]
@jricher @peacekeeper

**Comment by msporny** [comment]
Fixed in 9b7cc174624f866fd217bd251e0122461c8f76df. Closing.
