### ISSUE TITLE
What is the non empty value didResolutionMetadata when `resolve` is called

### ISSUE THREAD

**Issue by OR13** [w3c/did-core#689]
<img width="841" alt="Screen Shot 2021-02-20 at 3 55 51 PM" src="https://user-images.githubusercontent.com/8295856/108609532-1f27fb00-7394-11eb-9ef9-f2bcdf6d2827.png">

This seems like a mistake... its not like you know the contentType of an Abstract Data Model did document....

**Comment by OR13** [comment]
@peacekeeper @jricher @msporny

**Comment by msporny** [comment]
> This seems like a mistake.

Nice catch, I agree; that's a bug. I believe this is a hold over from the original write up from @peacekeeper and @jricher -- defer to them to note what's going on in that text.

**Comment by peacekeeper** [comment]
I agree this feels like a bug. Looks like this was introduced in https://github.com/w3c/did-core/commit/6cb86a38.

I suspect this was meant to say _"... in the case of an error in the resolution process, this MUST NOT be empty."_

(This would be parallel to the language about **dereferencingMetadata** in https://w3c.github.io/did-core/#did-url-dereferencing).

@jricher do you agree?

**Comment by peacekeeper** [comment]
I believe this has been fixed by https://github.com/w3c/did-core/pull/696 and can be closed. @OR13 do you agree?

**Comment by msporny** [comment]
PR #696 has been merged, waiting on confirmation from @OR13 to close.

**Comment by OR13** [comment]
yes, this can be closed.
