### ISSUE TITLE
Path semantics (general vs method-specific)

### ISSUE THREAD

**Issue by dmitrizagidulin** [w3c/did-core#698]
One thing that's unclear about the current DID Core spec is the semantics of the Path portion of DID URIs. So, the syntax is clear (same ABNF as RFC3254 URI paths). But what DID paths mean or what they're used for is not mentioned.

I'd like to add PR with a sentence to the [path section](https://w3c.github.io/did-core/#path) of DID URI Syntax, that states "path semantics are specified by DID Methods".

Any objections?

**Comment by peacekeeper** [comment]
I think I disagree slightly that path semantics are exclusively determined by DID methods. I think they may also be determined by DID controllers. Some DID methods may specify exactly what the path means and how it is used; others may allow the DID controller to do whatever they want with the path.

How about adding a sentence that says "path semantics are specified by DID methods and DID controllers"?

Anyway just a suggestion, I wouldn't object to your sentence either :)

**Comment by TallTed** [comment]
> Some DID methods may specify exactly what the path means and how it is used; others may allow the DID controller to do whatever they want with the path.

I think that in the latter case, those DID methods have specified that they are delegating (*cough*) control of the path semantics to the DID controllers.  Without such specific delegation, the DID controllers do not have control of the path semantics.

It's a little hand-wavy, but I think that "path semantics are specified by DID methods and DID controllers" will lead readers to think that DID controllers can specify path semantics in cases where the DID method has *not* delegated that control, and *that* would be incorrect and problematic.

**Comment by OR13** [comment]
> path semantics are specified by DID methods and DID controllers

+1

**Comment by msporny** [comment]
Suggestion by the Editors (could wordsmith further): Path semantics, as with URIs, can be specified by DID Methods, which in turn might enable DID controllers to further specialize those semantics.

**Comment by msporny** [comment]
PR #702 has been opened to address this issue. This issue will be closed once PR #702 is merged.

**Comment by msporny** [comment]
PR #702 has been merged, closing.
