### ISSUE TITLE
Example 1 in spec is perhaps not "minimal", as its caption suggests

### ISSUE THREAD

**Issue by ssstolk** [w3c/did-core#723]
Currently, the caption of example 1 is "A minimal DID document".
Given the only core property that is mandatory is "id", the example in 1 is small but perhaps not minimal.
In order to avoid suggesting the "authentication" property is mandatory in the example, I would suggest rephrasing the caption to smth along the lines of "A concise DID document"?
(Of course, this is from the point of me, as non-native English speaker, as to the meaning of 'minimal' being the smallest possible.)

**Comment by msporny** [comment]
PR #725 has been raised to address your concern, @ssstolk. 

Do the changes in that PR address your concern?

**Comment by msporny** [comment]
Note that @ssstolk has confirmed that this change works for them. Closing.
