### ISSUE TITLE
Bikeshed the DID specification short name

### ISSUE THREAD

**Issue by msporny** [w3c/did-core#76]
One of the things the WG needs to do is pick a short name for the specification. Let's use this issue to do that. Here are the bike shedding rules:

1. One short name proposal per comment. You can explain why it's a good or bad option in the comment.
2. Only thumbs up and thumbs down will be counted. All other emojis will be ignored for the purposes of voting, but feel free to emoji your heart out.
3. The Chairs and W3C Staff Contact have the final say, this is just a way to gather data for them and avoid `didy-mc-didface` short name scenarios.
4. Comments that put too much distance between voting options may be deleted/moved to bunch the options near the top.

Ready... GO!

**Comment by msporny** [comment]
Short name: `did-spec`
URL: https://www.w3.org/TR/did-spec/

This is what the spec is named now. It's probably a bad short name because there may be other DID specs, like did-resolution, or (in time) did method specs.

**Comment by msporny** [comment]
Short name: `did-data-model`
URL: https://www.w3.org/TR/did-data-model/

This proposal follows the pattern we did for Verifiable Credentials. It is a data model spec, but it's also a DID Method Requirements and DID Syntax document as well, which makes it not an entirely ideal name.

**Comment by msporny** [comment]
Short name: `did-core`
URL: https://www.w3.org/TR/did-core/

Feels like the right direction... this is the core DID spec, and it allows for other did-* specs to surface in time... like did-resolution, and did-method-foo, etc.

**Comment by msporny** [comment]
Short name: `did`
URL: https://www.w3.org/TR/did/

This was suggested on the call. Seems to have the same problems as did-spec... there may be a few other did-* specs... it's not as bad as did-spec, but it's close.

**Comment by msporny** [comment]
Short name: `did-layer1`
URL: https://www.w3.org/TR/did-layer1/

This is an attempt to model the name after CSS Level 1. Ambivalent.

**Comment by iherman** [comment]
Can we declare victory for  https://www.w3.org/TR/did-spec/ ?

Cc: @burnburn @brentzundel

**Comment by dlongley** [comment]
@iherman,

Did you mean https://www.w3.org/TR/did-core/ ?

**Comment by iherman** [comment]
@dlongley Sorry. Indeed; edited the comment

**Comment by msporny** [comment]
> Can we declare victory for https://www.w3.org/TR/did-core/ ?

Let's announce this is where we are during the upcoming call... I'm a bit concerned that not enough people participated... we can take care of it on the 2019-10-22 call, just show people the issue, tell people that the decision will be final at the end of the call, so speak now before it's too late... then go with where we are at the end of the call..

**Comment by TallTed** [comment]
@msporny @iherman -- If not enough people participated here, I would think the question should be announced on the WG mailing list (which probably should have been done already), with a date-certain for the decision, and a request for active participation (perhaps adding a "don't care"/abstain option, so as to be clear that people have seen the question, and are actively choosing not to voice an opinion). Votes may then be submitted via messages to the mailing list, `+1`/`-1` here, or proxy...

**Comment by msporny** [comment]
> If not enough people participated here, I would think the question should be announced on the WG mailing list 

Yes, in hindsight, probably should've done that (but there is a part of me that is saying "we do our work in Github, not on the mailing list... so people should be subscribed to this repo and paying attention to Github")... was trying to go for something lighter weight from a process perspective. 

We have *lots* of people on the weekly calls --  20+ -- that's enough of a sample set to make me feel comfortable. After all, we're just gathering data for the Chairs/Staff to make the final decision.

**Comment by msporny** [comment]
Short name: `didy-mc-didface`
URL: https://www.w3.org/TR/didy-mc-didface/

Requested by the community...

**Comment by kdenhartog-sybil1** [comment]
+1 from @kdenhartog sybil for `didy-mc-didface`

**Comment by kimdhamilton** [comment]
bike shedding rule 3 appears to be in conflict with the will of the people

**Comment by msporny** [comment]
We've had at least 16 people participating in this thread, group has been notified twice (via the call, and via the mailing list) to participate. We've had enough participation to provide input to the Chairs and Staff.

The option that gained the most support is `did-core` followed closely behind by `didy-mc-didface`.

@iherman, @brentzundel, and @burnburn -- please rename this repo to `did-core`. I will put the modifications into the fpwd PR to update the spec to match the new short name.

**Comment by burnburn** [comment]
As chair I agree with this.  `did-core` it is.

**Comment by iherman** [comment]
> @iherman, @brentzundel, and @burnburn -- please rename this repo to did-core. I will put the modifications into the fpwd PR to update the spec to match the new short name.

Done.

I propose to close this issue.

**Comment by brentzundel** [comment]
Closing, as a short name has been selected and the necessary changes have been made.
