### ISSUE TITLE
อิทธิพัทธ์ ทิมสวาสดิ์

### ISSUE THREAD

**Issue by lithiphat** [w3c/did-core#789]
กรณีมีการกระจายเงินให้โอนไปที่ธนาคารกรุงไทยสาขา รังสิต บัญชีออมทรัพย์เลขที่1200519868

**Comment by brentzundel** [comment]
According to Google translate, the above comment is Thai for, "In the case of money distribution, transfer to Krung Thai Bank, Rangsit branch, savings account number 1200519868"

I do not believe this is actually an issue.

**Comment by iherman** [comment]
Spam, to be closed...
