### ISSUE TITLE
Possible typos

### ISSUE THREAD

**Issue by shujikamitsuna** [w3c/did-core#794]
Hi, This is KAMITSUNA Shuji from Japan.

Thank you for the great specification.

 I found some possible typos in the specification:

1) In the long description of Figure 9, "dotted blue arrow" might be "blue arrow". There seems to be no dotted arrow in the figure 9.

2) In the same long description, "the Describes rectangle" might be "the rectangle, labeled "DID Document",".

3) In the long description of the Figure 10, "A green points" might be "A green arrow points".

Best regards,

KAMITSUNA, Shuji

**Comment by brentzundel** [comment]
Thank you for raising this issue, and for your detailed reading of the specification.
I have raised PR #795 to address this.
