### ISSUE TITLE
Formal objections need a separate response

### ISSUE THREAD

**Issue by rxgrant** [w3c/did-core#797]
In [did-imp-guide pull/27](/w3c/did-imp-guide/pull/27) there is an attempt to address the formal objections with wording that cannot in detail meet the concerns of the objectors, and that - in its current vague disapproval of proof-of-work DID methods as shown by calling them out under special requirements - cannot gain consensus.

It is possible to meet some possible concerns of the formal objectors with DID method specific wording, and a new work product should be approved for that task.

As one of the authors of a DID method relying on proof-of-work, I'm volunteering to lead writing a response that other WG members may sign on to if they agree.  

In particular, I believe that along with practical reasoning, a [causal model](https://plato.stanford.edu/entries/causal-models/#fig3) connecting the anchoring of DIDs on the Bitcoin blockchain to the alleged "fail" of the [TAG/EWP sustainability goal](https://www.w3.org/2001/tag/doc/ethical-web-principles/#sustainable) will help all parties speak more intelligently about the issue.  

Using this form of reasoning it is possible to examine the addition of each DID method anchoring transaction to the Bitcoin blockchain and quantify the additional motive to burn carbon-based fuels for electricity.  This metric can be used to offset the carbon polluted into the atmosphere.

Two DID methods that will be discussed are did:btcr and did:ion.  I will also critique conflicting TAG/EWP goals, discuss other moral concerns, point to transistions underway in the energy sector and speak about the economic incentives to use renewable energy, offer an example criteria to add to the Rubric so that end users can make later use of the reasoning, and offer to act as editor coordinating sections on other aspects of the formal objections, such as the request for a mandatory reference method.

**Comment by csuwildcat** [comment]
@rxgrant I don't believe DID Core is the place for this, as it should remain completely neutral in its description of the DID data model and DID related functions. Additionally, as an implementer of one of the methods mentioned, it seems inappropriate to discuss any specific DID methods in DID Core, or their underlying technical choices, which should remain in the realm of market choice. The implementers guide is a fine place for non-normative discussion/notes, so I think it's best if we keep it there.

**Comment by OR13** [comment]
The https://github.com/w3c/did-rubric is also a great place to discuss specific did methods.

The did core spec is a specification for a data model, and has nothing to do with implementations, other than the normative requirements it places on did method specifications.

**Comment by rxgrant** [comment]
I agree that did-core is not the right place for this.  I intended to ask did-wg to consider whether to add a new non-normative note, and pasted the URL over in a late-night error.  I will close the issue.
