### ISSUE TITLE
"id" property missing in examples

### ISSUE THREAD

**Issue by chrisiba** [w3c/did-core#800]
In [Example 31](https://w3c.github.io/did-core/#example-did-document-with-many-different-key-types) and [Example 32](https://w3c.github.io/did-core/#example-did-document-with-different-verification-method-types) the `id` property in the root map as required for all DID Documents by the [DID Document properties](https://w3c.github.io/did-core/#did-document-properties) is missing.

**Comment by danpape** [comment]
Just getting my feet wet -- since #801 was merged a few days ago, shouldn't we close this issue?

**Comment by msporny** [comment]
> Just getting my feet wet -- since #801 was merged a few days ago, shouldn't we close this issue?

Yes, good catch; we should. The process usually goes like this when you raise a PR to address the issue. You raise a PR, then you go to the issue and explicitly state:

> PR #NNN has been raised to address this issue. This issue will be closed when PR #NNN has been merged. 

We do this so everyone in the issue thread is notified that there is a PR active for the issue -- gives them an explicit heads-up to review if they want to. Once the PR is merged, and we believe the original issue has been dealt with (no additional PRs requested, no objections to the fix, etc.), we usually do something like the following:

> PR #NNN has been merged. Closing.

So, in this case:

PR #801 has been merged. Closing.
