### ISSUE TITLE
IANA file extension and mime type for JSON-LD represenation

### ISSUE THREAD

**Issue by gribneau** [w3c/did-core#804]
I couldn't help but notice that the file extension and mime type for the JSON-LD representation of a DID document reverse the order of "JSON" and "LD":

 ```
.didjsonld

application/did+ld+json
```
This can be seen in the [IANA Considerations](https://w3c.github.io/did-core/#iana-considerations) section. 

Is it possible (and reasonable) to standardize the order between the file extension and the mime type?

**Comment by TallTed** [comment]
This is one of those "no win" situations.

The file extension of JSON-LD is `jsonld`, and its media type, conforming to related RFCs, is `application/ld+json`.

The JSON-LD representations of DID documents are based on those, and we have found (after long effort!) no way to improve the media type beyond what we've done with `application/did+ld+json`.

It might make sense to change our file extension recommendation to `.jsonlddid`, but it's a bit late in the process to make that change (and there are definitely many who find the current extension of `.didjsonld` better).

**Comment by gribneau** [comment]
That's more or less what I anticipated.

Thanks. Closing.
