### ISSUE TITLE
Update github link to use TR instead of github.io

### ISSUE THREAD

**Issue by OR13** [w3c/did-core#810]
![Screen Shot 2021-12-16 at 11 04 20 AM](https://user-images.githubusercontent.com/8295856/146416311-4b5225d0-83c3-42c4-b3c3-3476d04269a4.png)

Possibly holding off on this until W3C process has been refined further... though I personally would do it ASAP, given the better link is available and resolvable.

**Comment by iherman** [comment]
That was a bug. Changed.
