### ISSUE TITLE
typo: "point *of* failure"

### ISSUE THREAD

**Issue by koalie** [w3c/did-core#816]
First row under [https://www.w3.org/TR/2021/PR-did-core-20210803/#design-goals](1.2 Design Goals) is missing "of" in "single point failure"

**Comment by TallTed** [comment]
@koalie -- Not important here & now, but for future reference... The GitHub markdown for a link is `[text](uri)`, not `[uri](text)` -- so `[https://www.w3.org/TR/2021/PR-did-core-20210803/#design-goals](1.2 Design Goals)` should be `[1.2 Design Goals](https://www.w3.org/TR/2021/PR-did-core-20210803/#design-goals)`, which then renders like this -- [1.2 Design Goals](https://www.w3.org/TR/2021/PR-did-core-20210803/#design-goals).  :-)

**Comment by brentzundel** [comment]
great catch, thanks for the close reading!

**Comment by msporny** [comment]
PR #817 was merged to address this issue.
