### ISSUE TITLE
[Question] Confusion about DID creation process

### ISSUE THREAD

**Issue by Michele971** [w3c/did-core#825]
I don't understand who will have the power to create a new identifier? Every user could create their own DID themselves? 
What ensures us that these DIDs are unique globally?

Has DID already become a W3C standard?

**Comment by talltree** [comment]
@Michele971 A core concept of DIDs as decentralized identifiers is that they are cryptographically generated (analogous to the way that [UUIDs](http://en.wikipedia.org/wiki/Uuid) are machine-generated), so they are inherently globally unique without needing a centralized registry. See [section 8.1](https://www.w3.org/TR/did-core/#method-syntax) of the DID 1.0 specification, which is in the final process of full W3C standardization.

**Comment by kdenhartog** [comment]
We should probably be careful stating that they are cryptographically generated these days. While that's true for almost all methods today, section 8.1 doesn't define it that way. Instead it states that they need to be globally unique, but not requiring cryptographic generation as the method which in turn means it's up to the method to define how that requirement is met. 

For example @Michele971, in [did:web](https://github.com/w3c-ccg/did-method-web) the method relies upon the domain name system to guarantee the identifiers are globally unique while in turn accepting tradeoffs in other areas.

**Comment by talltree** [comment]
@kdenhartog You are right; I updated my comment to reflect that they "can be" cryptographically generated, not that they have to be.

**Comment by Michele971** [comment]
@kdenhartog thank you guys. So if I am a Company, I can create my DIDs. The only things that I have to ensure is that DIDs have to unique. Right?

**Comment by peacekeeper** [comment]
@Michele971 Yes if you are a company, then you can create a DID for the company itself. And individuals (your customers, employees, or anyone else in the world) can also create their own DIDs.

But I think it is not helpful to think that a company creates DIDs for others, or that a company ensures that DIDs are unique.

It is the DID technology itself (or to be precise, the DID methods) that ensure that DIDs are unique. If your company, or some individuals, create a new DID, then it WILL be unique. This is ensures by the design of the DID methods themselves, and by the cryptography that is typically (not always) used.

**Comment by Michele971** [comment]
@peacekeeper Got it! Thank you, very helpful!!
