### ISSUE TITLE
Dock throws exception while verifying VC

### ISSUE THREAD

**Issue by Muthurajj** [w3c/did-core#833]
Hi below is the exception from dock https://certs.dock.io/credentials/verify

"A DID document lookup was successful, but the DID in question does not exist. This is different from a network error"

below is the VC

{
    "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://www.w3.org/2018/credentials/examples/v1"
    ],
    "type": [
        "UniversityDegreeCredential",
        "VerifiableCredential"
    ],
    "issuer": "did:sov:danube:8ZU1hh1zD9VQSWfhHPajaA",
    "issuanceDate": "2019-06-16T18:56:59Z",
    "expirationDate": "2023-06-17T18:56:59Z",
    "credentialSubject": {
        "degree": {
            "name": "Bachelor of Science and Arts",
            "type": "BachelorDegree"
        }
    },
    "proof": {
        "type": "Ed25519Signature2018",
        "created": "2022-09-28T05:12:46Z",
        "proofPurpose": "assertionMethod",
        "verificationMethod": "did:sov:danube:8ZU1hh1zD9VQSWfhHPajaA#key-1",
        "jws": "eyJiNjQiOmZhbHNlLCJjcml0IjpbImI2NCJdLCJhbGciOiJFZERTQSJ9..TznhWGfjwDc_0wiiR9rTCiGKjEciz_BYXb4aAJY8PEKXzTBDP-F-0c-LtipLGpheOeLwTVpahIHfbhfideF_Dg"
    }
}

below is the did document prepared in [godiddy](https://godiddy.com/app/manage/create)

{
  "@context": [
    "https://www.w3.org/ns/did/v1",
    "https://w3id.org/security/suites/ed25519-2018/v1",
    "https://w3id.org/security/suites/x25519-2019/v1"
  ],
  "id": "did:sov:danube:8ZU1hh1zD9VQSWfhHPajaA",
  "verificationMethod": [
    {
      "type": "Ed25519VerificationKey2018",
      "id": "did:sov:danube:8ZU1hh1zD9VQSWfhHPajaA#key-1",
      "controller": "did:sov:danube:8ZU1hh1zD9VQSWfhHPajaA",
      "publicKeyBase58": "57ymRkRYAFRuNzCDwW8H7wavyETAHydStJkmcFDpeQR3"
    },
    {
      "type": "X25519KeyAgreementKey2019",
      "id": "did:sov:danube:8ZU1hh1zD9VQSWfhHPajaA#key-agreement-1",
      "controller": "did:sov:danube:8ZU1hh1zD9VQSWfhHPajaA",
      "publicKeyBase58": "C6qjDgZpWWNENh42jcAywSHzpWL8dgmhzVDWNvkCahkv"
    }
  ],
  "authentication": [
    "did:sov:danube:8ZU1hh1zD9VQSWfhHPajaA#key-1"
  ],
  "assertionMethod": [
    "did:sov:danube:8ZU1hh1zD9VQSWfhHPajaA#key-1"
  ],
  "keyAgreement": [
    "did:sov:danube:8ZU1hh1zD9VQSWfhHPajaA#key-agreement-1"
  ],
  "service": []
}

**Comment by kdenhartog** [comment]
I suggest reporting this to https://github.com/docknetwork

This isn't the correct repo for this issue to be filed.
