### ISSUE TITLE
Can we create DID in godiddy ?

### ISSUE THREAD

**Issue by Muthurajj** [w3c/did-core#834]
The did create in godiddy site can we access globally?

**Comment by peacekeeper** [comment]
@Muthurajj This is the repository for the DID Core specification. As you already saw in your other issue https://github.com/w3c/did-core/issues/833, this is not the right place for asking questions about specific products. Please ask your questions at those other websites/companies.

**Comment by Muthurajj** [comment]
Sorry @peacekeeper
