### ISSUE TITLE
Update JsonWebKey2020 to JsonWebKey

### ISSUE THREAD

**Issue by decentralgabe** [w3c/did-core#850]
As per https://w3c.github.io/vc-jose-cose/

**Comment by peacekeeper** [comment]
Makes sense to align with VC specs.

**Comment by decentralgabe** [comment]
As @msporny mentioned today we can either update the existing context or create a new one.
My guess is we'll probably need a new context for 1.1 anyway, so we could have this issue follow that one.
Alternatively, we could create a new examples context and solve this quicker.

I'm fine with either path.

**Comment by iherman** [comment]
> My guess is we'll probably need a new context for 1.1 anyway

I am not so sure. I would not think we would add new properties for DID Documents (we may not even be allowed to do so), and that would be the only reason to change the context.

**Comment by msporny** [comment]
PR https://github.com/w3c/did-core/pull/867 has been raised to address this issue. This issue will be closed once PR https://github.com/w3c/did-core/pull/867 has been merged.

**Comment by msporny** [comment]
PR #867 has been merged, closing.
