### ISSUE TITLE
Move DID Resolution topics from DID Core to the DID Resolution spec

### ISSUE THREAD

**Issue by peacekeeper** [w3c/did-core#857]
The [DID Core specification](https://w3c.github.io/did-core/) contains a section called "Resolution", and also some term definitions and other aspects about DID Resolution. It has been suggested that those parts should be moved to the [DID Resolution specification](https://w3c.github.io/did-resolution/), so that everything related to DID Resolution is in one place.

E.g. these parts should be moved:
- https://w3c.github.io/did-core/#dfn-did-resolvers
- https://w3c.github.io/did-core/#resolution
- https://w3c.github.io/did-core/#choosing-did-resolvers

**Comment by wip-abramson** [comment]
Suggest this is good to close

**Comment by peacekeeper** [comment]
Both PRs that address this issue have been approved and merged. Closing.
