### ISSUE TITLE
`application/did+ld+json` should be revisited

### ISSUE THREAD

**Issue by TallTed** [w3c/did-core#863]
_Originally posted by @TallTed in https://github.com/w3c/did-resolution/pull/88#discussion_r1747431386_

Multiple `+` have been disallowed in IETF/IANA media types. 

`application/ld+json` might be sufficient.

This needs to be applied throughout [`did-resolution`](https://github.com/w3c/did-resolution/) as well as [`did-core`](https://github.com/w3c/did-core/).

**Comment by pchampin** [comment]
This was discussed during the [#did meeting on 19 September 2024](https://www.w3.org/2024/09/19-did-minutes.html#t06).

<details><summary><i>View the transcript</i></summary>

<h4><a href="https://github.com/w3c/did-core/issues/863" rel="noopener noreferrer">w3c/<wbr>did-core#863</a> application/did+ld+json should be revisited</h4>
<p><cite>manu:</cite> Strategy to discuss the big rocks first. Class 3, then 2 then 1<br>
<span>… 863 is about the media type. In did-core we said application/did+ld+json</span><br>
<span>… open question what the media type should be. Cannot have did+ld+json</span><br>
<span>… some implementors want to use json serialization others jsonld</span><br>
<span>… Looking at potentially 2 media types</span><br>
<span>… we could try application/did as the media type</span><br>
<span>… with the new controller document which supports context injection. We can parse as json if it doesnt have a json if it does have a @context you can parse as jsonld</span><br>
<span>… if you want to parse as jsonld but it doesn't have a context you can inject one</span></p>
<p><cite>&lt;ivan&gt;</cite> <a href="https://www.w3.org/TR/controller-document/#context-injection" rel="noopener noreferrer">Controller document context injection section</a></p>
<p><cite>manu:</cite> Strongly suggesting we just do application/did to keep it simple<br>
<span>… Need to be clear we are not allowing two different processing models</span><br>
<span>… thoughts concerns about application/did</span></p>
<p><cite>&lt;bigbluehat&gt;</cite> +1 to `application/did`</p>
<p><cite>&lt;dmitriz&gt;</cite> my vote would be for application/did+json.  To enable the eventual (and inevitable?) application/did+cbor</p>
<p><cite>markus_sabadello:</cite> What does this mean for the abstract data model, if the controller document allows context injection</p>
<p><cite>&lt;Zakim&gt;</cite> manu, you wanted to go into polyglot response if it becomes an issue.</p>
<p><cite>manu:</cite> Still have the abstract data model. You would still be able to use JSON. Or you can use jsonld. Fundamentally these are interpretted the same. The meaning is the same</p>
<p><cite>markus_sabadello:</cite> I want to do this. Seems like we don't need the different representations anymore.</p>
<p><cite>dmitriz:</cite> In JSON vs JSONLD we loose track of other things like CBOR and YAML. My vote is for application/did+json<br>
<span>… implementations need to know how to parse the document</span></p>
<p><cite>ivan:</cite> Understand dmitriz opinion. But, the VCWG has decided to use application/vc for verifiable credentials</p>
<p><cite>&lt;Zakim&gt;</cite> manu, you wanted to note that we could have CBOR in the future. and to ask if it's "application/json", then what do we do for JSON-LD?</p>
<p><cite>manu:</cite> Not closed the door on CBOR or YAML. Could have did+cbor or did+yaml. But what do we do about jsonld. We could say application/did is jsonld<br>
<span>… Or we would have to get a new suffix through the jsonld working group</span><br>
<span>… Markus, the reason we would have different representations is to support CBOR and YAML</span><br>
<span>… One more option, for JSONLD DID documents jsonld/we could use application/ld+json/jsonld</span></p>
<p><cite>decentralgabe:</cite> encourage people to consider discussion on an issue</p>
<p><cite>decentralgabe:</cite> time for one or two more</p>

<hr /></details>

**Comment by pchampin** [comment]
This was discussed during the [did meeting on 10 October 2024](https://www.w3.org/2024/10/10-did-minutes.html#47b6).

<details><summary><i>View the transcript</i></summary>

<h4><a href="https://github.com/w3c/did-core/issues/863" rel="noopener noreferrer">w3c/<wbr>did-core#863</a></h4>
<p><cite>manu:</cite> something to think about. Issue 863 about our media type<br>
<span>… We should reconsider application/vc and application/vp</span><br>
<span>… We had a conversation with TAG, when you are using JSON-LD and it could also be JSON, we'd feel better if the spec says ANY interpretation cannot be different between the two. Any difference is either a specification bug or an implementation bug.</span><br>
<span>… This feels like it addresses some outstanding confusion.</span><br>
<span>… In which case we can just be application/did</span><br>
<span>… but fundamentally, no software system should interpret one over the other.</span><br>
<span>… I'll bring this up again the next time we discuss the issue</span></p>
<p><cite>burn:</cite> Any other items?</p>
<p><cite>burn:</cite> Thanks everyone</p>

<hr /></details>

**Comment by msporny** [comment]
PR #868 has been raised to address this issue. This issue will be closed once PR #868 has been merged.

**Comment by msporny** [comment]
PR #868 has been merged, closing.
