### ISSUE TITLE
Replace RsaSignature2017 by a standard JWA signature

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#9]
@AxelNennker moved from CCG (https://github.com/w3c-ccg/did-spec/issues/39)

**Comment by selfissued** [comment]
I agree that we should replace RSASignature2017 with use of the JWS and JWA standards.  This will increase interop and reduce the footprint of new standards we need to create to finish the DID spec and things that it relies upon.

**Comment by msporny** [comment]
The specification should clearly state that proof mechanisms are outside of the scope of the specification. I'd argue that the specification should probably remove the `proof` property as well. If people want to use JSON-LD + Linked Data Security mechanisms they can do that... if folks want to use JWS, they can do that too, but protecting DID Documents using either mechanisms shouldn't be mandated or prevented by the spec.

**Comment by jricher** [comment]
I think that specifying the proofing mechanism is outside the scope of this spec, but the data model itself needs to have a notional place for the proof and define aspects of that proof. I would go so far as to say that we also need to have a set of requirements that proofing mechanisms fulfill, in addition to a way to signal the mechanism in use on a document. The details are the trick here, for instance requiring that the signature method is itself covered by the signature.

**Comment by msporny** [comment]
I'll try to write a PR for this.

**Comment by OR13** [comment]
This issue is stale... there are no references to "RsaSignature2017" in the current spec... There is a reference to proof https://w3c.github.io/did-core/#proof

I don't think this issue is ready for a PR... I created a new ticket for:

Define "proof" property of did document. https://github.com/w3c/did-core/issues/223

@jricher  @selfissued @msporny If there is consensus on this approach, please close this issue and add any comments to the one linked above.

**Comment by msporny** [comment]
RsaVerificationKey2018 still exists in the spec - I expect @selfissued will have a concern with that... and we may change to Ed25519VerificationKey2020 for examples, which I expect @selfissued may still have a concern with.

**Comment by msporny** [comment]
The RSA Verification Key examples have been changed to Ed25519 ones. There is a different issue opened for updating the JWK examples, see #171.

That means that this issue can be closed now.

**Comment by brentzundel** [comment]
No comments since marked pending close, closing.
